### PR TITLE
Raspberry pi code a22083 is 3B+ Model

### PR DESCRIPTION
**Pull request by arbabseyfola**

### CODE REVIEW

**Comment by lurch** [comment]
That's not what #1108 says? :confused:

**Comment by arbabseyfola** [comment]
> That's not what #1108 says? 😕
Why board revision is 1.3? What is the difference between 1.2 and 1.31?

**Comment by lurch** [comment]
> Why board revision is 1.3? What is the difference between 1.2 and 1.31?

AFAIK Raspberry Pi doesn't provide that level of detail about their hardware.

**Comment by JamesH65** [comment]
Closing, that revision code is definitely a 3B, not a Plus.

**Pull request closed without merging**
