### PR TITLE
Using the Fing app to get Raspi's IP adress

### PR DESCRIPTION
**Pull request by Lukas-J**

### CODE REVIEW

**Comment by bennuttall** [comment]
Useful suggestion, thanks.

I think maybe it should go under a heading of "more tools" (maybe just the links without the text), or at least underneath nmap.

**Comment by Lukas-J** [comment]
I think, that the Fing app should be a the position I put it, because as a beginner, I don't want the first problems before I started to use my Raspi. I know it from my own experience.

**Comment by JamesH65** [comment]
I think Fing should have its own section, BUT that it should be after the nmap section. The title should also be improved to show its a phone based approach, so people can find the section easily. There's also a few typos/misspellings in the text. Fix up those and I will push it to copy edit.

**Comment by Lukas-J** [comment]
Hi, unfortunately I am not a native speaker. Please could someone else improve the title and the typos and misspellings in the text.
Thanks.

**Comment by JamesH65** [comment]
OK, will do it.

**Comment by JamesH65** [comment]
OK, have fixed up any issues i can see and pushed to copy edit.

**Pull request merged**
