### PR TITLE
Add Etcher to MacOS documentation RE: #455

### PR DESCRIPTION
**Pull request by brianjking**
If this is accepted I'd be happy to add this to the [Windows](https://github.com/raspberrypi/documentation/blob/master/installation/installing-images/windows.md) file as well. This is mentioned in #450.

### CODE REVIEW

**Comment by JamesH65** [comment]
Looks good, forwarding for copy edit and merge. Thanks.

**Comment by LornaLynch** [comment]
Copy edited. I believe I am supposed to add the 'Requires technical check' for a final once-over, @JamesH65, @ghollingworth?

**Comment by JamesH65** [comment]
Yes, the requires technical check indicates to tech people that it's been copy edited, and can be merged if the tech check is OK. If the copy edit has cause a technical issue, it will be flagged up and returned to the ready for copy edit label.

**Comment by LornaLynch** [comment]
Thanks, @JamesH65: that clears things up :)

**Pull request merged**
