### PR TITLE
dd showing write progress status

### PR DESCRIPTION
**Pull request by twikedk**
As of GNU Coreutils 8.24+ dd is able to show progress with the option status=progress

### CODE REVIEW

**Comment by XECDesign** [comment]
What percentage of the top 10 distros ship with that version of dd in their stable repos?

**Comment by twikedk** [comment]
Taken from distrowatch.com?? I would say more than 50% of the top 10 and
basically every new distro from this year.

--
Ole

2016-11-27 15:35 GMT+01:00 XECDesign <notifications@github.com>:

**Comment by XECDesign** [comment]
Then this would error out for a lot of people. Given that the documentation is for beginners, that probably wouldn't be the best start for them.

**Comment by twikedk** [comment]
No you are probably right I guess it is better that the page recommend the
use of 'dcfldd' which is not even part of a default installation.
If you look at my suggestion I didn't remove the old command just added
another with status=progress option and sync included.
By the way Linux Mint, all Ubuntu derivatives, Fedora and openSUSE holds
the new coreutils today which probably also is the start
point for a lot of new comer, but never mind just reject it and close the
request again.

--
Ole

2016-11-27 17:14 GMT+01:00 XECDesign <notifications@github.com>:

**Comment by XECDesign** [comment]
I am not accepting or rejecting anything, only commenting. I don't have write access to this repo.

Adding a command without removing the old one does not make it any clearer.
Just a note that mentions the use of status= would probably be useful.

Changing sdd to sdX without changing the references to sdd is another issue.

Is the added sync needed? AFAIK, dd won't return until all the data is actually written.

**Comment by twikedk** [comment]
The sdX was a last minute add, sorry for not completing it but I always
believe having example code that isn't directly destructible is a good
thing. For the sync command flushing your cache before removing drives just
seems like a reasonable ending as far as I know even dd uses cache unless
clearly set with an option not to do so.

--
Ole

2016-11-27 17:56 GMT+01:00 XECDesign <notifications@github.com>:

**Comment by gelliott181** [comment]
Just a thought, but the `dd` command outputs it's current state with Ctrl-T. If I'm not mistaken that's the command for a SIGINFO?

**Comment by gelliott181** [comment]
I figure if we mention `status=progress` the old school way could also make an appearance.

**Comment by lurch** [comment]
@gelliott181 see #446

**Comment by JamesH65** [comment]
Duplicate of #350. Please use that one for further comments.

I think I'd happy to have the status=progress added as the default, with a disclaimer to remove if it doesn't work.

**Pull request closed without merging**
