### PR TITLE
Update external link to HTTPS to squash a Travis warning

### PR DESCRIPTION
**Pull request by lurch**

### CODE REVIEW

**Comment by bennuttall** [comment]
No luck!

**Comment by lurch** [comment]
> No luck!

Huh? It's knocked the HTML-Proofer 'failures' down from 4 to 3.

**Comment by bennuttall** [comment]
> External link https://www.arm.com/products/processors/classic/arm11/arm1176.php failed: response code 0 means something's wrong.

**Comment by lurch** [comment]
Oh yeah, doh! I was just comparing the numbers at the bottom of https://travis-ci.org/raspberrypi/documentation/builds/208932949 and https://travis-ci.org/raspberrypi/documentation/builds/208954791

But at least it's now a 'code 0' (which we can't do anything about) rather than a 'code 302' ;-)

**Pull request merged**
