### PR TITLE
Update uart.md

### PR DESCRIPTION
**Pull request by bsimmo**
updating DT overlay links to now default branch rpi-5.4.y  from rpi-4.9.
(unless anyone knows how to link to the default so it doesn't need to be changed each time?)

### CODE REVIEW

**Comment by lurch** [comment]
ping @pelwell 
From a quick `git grep`, looks like `configuration/cmdline-txt.md` also has an `rpi-4.19.y` link - all the other files (with links to https://github.com/raspberrypi/linux ) in this repo are already linking to a `rpi-5.4.y` URL.

**Comment by pelwell** [comment]
Did you really need to involve me in this? Merge this and fix the cmdline link.

**Comment by JamesH65** [comment]
Thanks!

**Comment by lurch** [comment]
Sorry Phil, I was pinging you in case you "knows how to link to the default so it doesn't need to be changed each time".

**Comment by pelwell** [comment]
The only options I can think of are to specifically create a branch to track the current default (e.g. `current`), or to use `HEAD` as the branch in URLs - what do you think, @popcornmix?

**Pull request merged**
