### PR TITLE
update for zh-CN manual of audio guide!

### PR DESCRIPTION
**Pull request by xgqfrms**
**update for zh-CN manual of audio guide!**

---

---

 raspberry is so cool for the anybody learning programming!
pi01

### CODE REVIEW

**Comment by JamesH65** [comment]
@bennuttall @LornaLynch What is our policy on translations? I cannot see any other languages anywhere.

**Comment by LornaLynch** [comment]
As far as I'm aware, we don't host translated material in the documentation repo at all. I'll dig around and see what information I can track down.

**Comment by bennuttall** [comment]
Well, this PR replaces an English page with a Chinese page, so that's no good. We don't have any meaningful way of displaying pages in other languages, and until we decide to do the whole thing, we can't really accept individual pages.

**Comment by JamesH65** [comment]
@xgqfrms As per the comments above, we currently do not have a foreign language section for documentation, so I'm afraid this PR is being rejected. However, thank you for your efforts.

**Pull request closed without merging**
