### PR TITLE
Update updating.md

### PR DESCRIPTION
**Pull request by eitanchud**
Added additional third-party solution that supports OTA updates for Raspbian out-of-the-box.

### CODE REVIEW

**Comment by lurch** [comment]
Does https://github.com/raspberrypi/documentation/issues/1439#issuecomment-601694131 also apply here @JamesH65 ?  :shrug:

**Comment by JamesH65** [comment]
Hmm, quite possibly, didn;t know about that section.

**Comment by eitanchud** [comment]
Would be nice if you decide regarding the third party providers topic and apply the decision on all the sections across the documentation. Also if you could share the final decision would be very interesting :)

**Comment by JamesH65** [comment]
Indeed, I will ask the powers above what our current policy is.

**Comment by JamesH65** [comment]
OK, had spoken to the bosses, and we are going to remove third party recommendations/instructions from the site, except in rare cases where that would be detrimental or we have agreements in place.

**Pull request closed without merging**
