### PR TITLE
Fix what exactly should be done to force wpa-supplicant  take config changes into account

### PR DESCRIPTION
**Pull request by mvasin**
According to manual https://w1.fi/cgit/hostap/plain/wpa_supplicant/README : "Changes to configuration file can be reloaded be sending SIGHUP signal to wpa_supplicant ('killall -HUP wpa_supplicant'). Similarly, reloading can be triggered with 'wpa_cli reconfigure' command."

### CODE REVIEW

**Comment by JamesH65** [comment]
This appears to be technically valid. Tried it on a recent Raspbian install and it did appear to do what it says.

**Comment by mvasin** [comment]
We are working with `wpa_supplicant` here, and I suggested the way to take config changes into account recommended in the `wpa_supplicant` documentation. This passage "If it does not, restart..." is there because maybe current approach doesn't work as good. At least I had no troubles with `sudo wpa_cli reconfigure`.

**Comment by JamesH65** [comment]
Thanks, this has been passed on for checking and inclusion.

**Comment by LornaLynch** [comment]
Merged: thanks.

**Pull request merged**
