### PR TITLE
Update building.md

### PR DESCRIPTION
**Pull request by igormartsekha**
Wrong mount names

### CODE REVIEW

**Comment by XECDesign** [comment]
The original numbers are fine. It looks like you're using a noobs card, in which case those numbers aren't guaranteed either.

**Comment by JamesH65** [comment]
@XECDesign NOOBS not my area, any thoughts?

**Comment by XECDesign** [comment]
The instructions assume a normal image and already point out noobs partitions will need to be adjusted, right? Still, 6 and 7 are not guaranteed to always be right, varying with the number of operating systems installed.

**Comment by lurch** [comment]
I wonder if changing "adjusting the partition numbers for NOOBS cards" to "adjusting the partition numbers for NOOBS cards (as necessary)" might clear this up? :man_shrugging:

**Pull request merged**
