### PR TITLE
Update headless.adoc

### PR DESCRIPTION
**Pull request by sa0mad**
Added description about HDMI hotplug as needed for smooth reboot without HDMI screen connected to RPi 4.

### CODE REVIEW

**Comment by aallan** [comment]
There's something off with your markup, it doesn't render correctly? 

Screenshot 2023-07-29 at 16 20 18

**Comment by andrum993** [comment]
The Pi 4 does **not** need this setting changed in order to boot with no screen attached. The description of this configuration setting is also wrong - it tells the firmware-based  graphics stack to always enable HDMI output, even if there is no monitor detected.

The Pi 4 also does not enable composite video output automatically if there is no screen detected on the HDMI ports - unlike Pi 0-3 the Pi 4 requires an additional setting in config.txt to enable composite video, since it requires some very specific clock timings that result in reduced system performance.

**Comment by aallan** [comment]
@jehlers42 Can you take a look at this, check for veracity and fix up ready to merge. Thanks!

**Comment by jehlers42** [comment]
This appears to be a less-than-preferable way to go about forcing boot without a monitor.

Decided to add info to this article still, but in a different manner. 
https://github.com/raspberrypi/documentation/pull/3102

**Pull request closed without merging**
