### PR TITLE
Removed mechanical drawings for keyboard and mouse

### PR DESCRIPTION
**Pull request by aallan**
This PR can be merged after @mudge adds redirects from raspberrypi.org/documentation/keyboard_mouse/* to the new locations on datasheets.raspberrypi.org.

### CODE REVIEW

**Comment by lurch** [comment]
The keyboard layout images haven't been moved to datasheets.raspberrypi.org - is that deliberate?

**Comment by aallan** [comment]
> The keyboard layout images haven't been moved to datasheets.raspberrypi.org - is that deliberate?

In the middle of things. Will copy them today probably. Just having a deliberate think about how I want things to work. Small steps.

**Comment by aallan** [comment]
@lurch Any idea why there is a merge conflict on this PR by the way? I'm not sure I understand.

**Comment by lurch** [comment]
GitHub is getting confused because this commit is in `master` https://github.com/raspberrypi/documentation/commit/3c9dad7045b2758392b1b7de9f8333abb570ca99 but that change isn't in this PR - hence the conflict.

**Comment by aallan** [comment]
> GitHub is getting confused because this commit is in `master` [3c9dad7](https://github.com/raspberrypi/documentation/commit/3c9dad7045b2758392b1b7de9f8333abb570ca99) but that change isn't in this PR - hence the conflict.

You know you'd think that it could figure out that if we're deleting the file it doesn't matter if the file is slightly changed on master, we're still deleting it. Not a conflict Git, not a conflict.

**Comment by lurch** [comment]
OTOH, it does ensure that any potentially-important changes on `master` don't get overlooked/ignored by the person deleting the file :shrug:

**Comment by aallan** [comment]
> OTOH, it does ensure that any potentially-important changes on master don't get overlooked/ignored by the person deleting the file 🤷

I suppose so, but I'm going to be grumpy about it anyway.

**Comment by lurch** [comment]
I've rebased it for you, problem solved :wink:

**Comment by aallan** [comment]
> I've rebased it for you, problem solved 😉

Thanks! 😆

**Comment by aallan** [comment]
@mudge Whenever those redirects in place, I can merge this one.

**Comment by mudge** [comment]
Redirects are now in place and I've purged the Cloudflare cache so the following URLs should all now return permanent redirects to their new location on https://datasheets.raspberrypi.org:

* https://www.raspberrypi.org/documentation/hardware/keyboard_mouse/mechanical/rpi_MECH_keyboard_DE_layout.png
* https://www.raspberrypi.org/documentation/hardware/keyboard_mouse/mechanical/rpi_MECH_keyboard_DK_layout.png
* https://www.raspberrypi.org/documentation/hardware/keyboard_mouse/mechanical/rpi_MECH_keyboard_ES_layout.png
* https://www.raspberrypi.org/documentation/hardware/keyboard_mouse/mechanical/rpi_MECH_keyboard_FR_layout.png
* https://www.raspberrypi.org/documentation/hardware/keyboard_mouse/mechanical/rpi_MECH_keyboard_IT_layout.png
* https://www.raspberrypi.org/documentation/hardware/keyboard_mouse/mechanical/rpi_MECH_keyboard_NO_layout.png
* https://www.raspberrypi.org/documentation/hardware/keyboard_mouse/mechanical/rpi_MECH_keyboard_PT_layout.png
* https://www.raspberrypi.org/documentation/hardware/keyboard_mouse/mechanical/rpi_MECH_keyboard_SE_layout.png
* https://www.raspberrypi.org/documentation/hardware/keyboard_mouse/mechanical/rpi_MECH_keyboard_UK_layout.png
* https://www.raspberrypi.org/documentation/hardware/keyboard_mouse/mechanical/rpi_MECH_keyboard_US_layout.png
* https://www.raspberrypi.org/documentation/hardware/keyboard_mouse/mechanical/rpi_MECH_keyboard_mouse.pdf

**Comment by lurch** [comment]
@aallan Do we at least want a link from `hardware/README.md` to these new datasheets.raspberrypi.org files? Or are those links going to be added to https://www.raspberrypi.org/products/raspberry-pi-keyboard-and-hub/ ? Oh... I see they already have - bonus!

**Comment by aallan** [comment]
> @aallan Do we at least want a link from hardware/README.md to these new datasheets.raspberrypi.org files? Or are those links going to be added to https://www.raspberrypi.org/products/raspberry-pi-keyboard-and-hub/ ? Oh... I see they already have - bonus!

So the only place these need to be linked from is the Product Page. This doesn't look like documentation.

**Comment by aallan** [comment]
Thanks @mudge. Many (many!) more to go, but a good solid start.

**Pull request merged**
