### PR TITLE
CMIO second camera clarifications

### PR DESCRIPTION
**Pull request by torkeldanielsson**
I made some clarifications on how to setup and connect the second
camera. I also added a note about a reported issue with GPIO pin 2 and
3.

### CODE REVIEW

**Comment by XECDesign** [comment]
The dt-blob.bin linked in the quickstart section is already the dualcam version, so there is no need to modify anything. So there is no need to "Also follow the instructions under 'How to attach two cameras' below for info on how to set pin configurations for the second camera."

**Comment by XECDesign** [comment]
Do you think the "to change pin configuration for GPIO pins 0-3 so they can be used with the camera" is necessary? It's a little misleading, because it does more than that. I'll merge it if you think it's clearer than the way it is now, but I worry that it might be a little confusing since it's not 100% accurate.

**Comment by torkeldanielsson** [comment]
Nah, maybe that's not the most important addition ever written... But the note at the end would have saved me some time googling and forum-reading when I was banging my head against the wall wondering why the second camera wouldn't work. Until that's fixed my recommendation would be to merge this change.

Here's the forum post with background:
https://www.raspberrypi.org/forums/viewtopic.php?f=98&t=89876

**Comment by XECDesign** [comment]
Alright, remove "to change pin configuration for GPIO pins 0-3 so they can be used with the camera.", squash into a single commit and I'll pull it in. Thank you.

**Comment by torkeldanielsson** [comment]
Squashing commits was a first for me, hope I did it without messing something up :)

**Comment by XECDesign** [comment]
Yup, looks good. Thank you.

**Pull request merged**
