### PR TITLE
Add note about changing the hostapd hw_mode

### PR DESCRIPTION
**Pull request by lurch**
If I left `channel` set to `7` when changing the `hw_mode` to `a`, hostapd wouldn't start and reported an error about an invalid channel selection. (it later worked when I changed the channel to 36)

However I dunno much about wireless networks, and even less about access points, so pinging @epoch1970 for confirmation.

### CODE REVIEW

**Comment by epoch1970** [comment]
Makes sense to me. I have no 5GHz-capable Pi, so I never came across this bump on the road.
The same note would apply to the bridged AP documentation.

**Comment by lurch** [comment]
Thanks @epoch1970 - I've just made small tweaks to both pages to make them more consistent with each other.

**Comment by JamesH65** [comment]
Is this OK to merge?

**Comment by lurch** [comment]
LGTM :wink:

**Pull request merged**
