### PR TITLE
Add heading anchor links

### PR DESCRIPTION
**Pull request by nelliemckesson**
@aallan @lurch @jackbenwillis this is the first step to add those heading links as requested in #1991 . I'm basically copying how github does it. I still need to add the styles to hide/show on hover and get the alignment right etc, and also test it a bunch, but there are a few things I need from y'all, so I wanted to get the ball rolling on that.

* @lurch : Can you add `_plugins` to the list of dirs to copy during the make process?
* @jackbenwillis Can you give me an SVG icon to use for the link image? Here's what it looks like currently (completely stolen from github):

Screen Shot 2021-08-12 at 7 36 32 PM

### CODE REVIEW

**Comment by aallan** [comment]
Converted to draft status so I don't accidentally merge before all features implemented.

**Comment by lurch** [comment]
@nelliemckesson Hmmm, did you miss my email? Any reason to not use the built-in AsciiDoctor mechanism for this? https://docs.asciidoctor.org/asciidoc/latest/sections/title-links/#anchor

If you want to test that locally, you'll need to use this patch:
```
diff --git a/scripts/create_build_adoc.py b/scripts/create_build_adoc.py
index 5aeed0c6..bb7f375a 100755
--- a/scripts/create_build_adoc.py
+++ b/scripts/create_build_adoc.py
@@ -32,6 +32,7 @@ if __name__ == "__main__":
 :includedir: {}
 :doctitle: {}
 :page-sub_title: {}
+:sectanchors:

 include::{{includedir}}/{{parentdir}}/{}[]
 """.format(output_path, src_dir, 'Raspberry Pi Documentation -
{}'.format(index_title), index_title, adoc_filename))
```

(but I believe it won't actually do anything until you add the necessary CSS, which I dunno how to do)

**Comment by jackbenwillis** [comment]
[Link icon.svg.zip](https://github.com/raspberrypi/documentation/files/6981282/Link.icon.svg.zip)
Excuse the round about way of uploading the file. Github doesnt accept .svg....

**Comment by nelliemckesson** [comment]
@lurch I did not see that email! That's handy. Went ahead and swapped it out here.

@jackbenwillis are you cool with using the built-in symbol? (Sorry for making you go to the trouble.) I can def use that link svg icon instead if you feel that's better for the brand -- always nice to manage fewer assets though. 

Here's what it looks like now:

Screen Shot 2021-08-17 at 8 46 20 PM

**Comment by aallan** [comment]
I'm going to merge this now — @jackbenwillis is on holiday for the rest of the month. We can revisit it when he gets back if he wants to switch to the custom link icon?

**Review by aallan — APPROVED** [review]
LGTM

**Pull request merged**
