### PR TITLE
rpi touch display: fix incorrect kernel module in troubleshooting page

### PR DESCRIPTION
**Pull request by andrum99**
See #1893

### CODE REVIEW

**Comment by lurch** [comment]
ping @6by9

**Comment by 6by9** [comment]
Nope.
edt-ft5x06 is for use with full KMS where the kernel will be directly polling the panel, not for when doing it via the firmware.

**Comment by andrum99** [comment]
Fixed per https://github.com/raspberrypi/documentation/issues/1893#issuecomment-831839010

**Comment by 6by9** [comment]
I don't have a touchscreen connected at present, but the supposed result from that grep being 
```
[ 5.224267] rpi-ft5406 rpi_ft5406: Probing device
[ 5.225960] input: FT5406 memory based driver as /devices/virtual/input/input3
``` 
looks incorrect too.

"FT5406 memory based" would be coming from https://github.com/raspberrypi/linux/blob/rpi-4.19.y/drivers/input/touchscreen/rpi-ft5406.c#L253
whilst raspberrypi-ts in 5.4 and 5.10 set it to "raspberrypi-ts" https://github.com/raspberrypi/linux/blob/rpi-5.4.y/drivers/input/touchscreen/raspberrypi-ts.c#L181

The "Probing device" line doesn't exist either with raspberrypi-ts (https://github.com/raspberrypi/linux/blob/rpi-4.19.y/drivers/input/touchscreen/rpi-ft5406.c#L174 for rpi-ft5406)

Sorry, but this needs to be checked against a system with a panel actually connected.

**Comment by aallan** [comment]
In light of #1911 is this PR still relevant?

**Comment by andrum99** [comment]
> In light of #1911 is this PR still relevant?

Per 6by9:

> Sorry, but this needs to be checked against a system with a panel actually connected.

Which I don't have. If this particular page is going to survive the upcoming reorg of the docs then this PR is worth keeping, otherwise feel free to close.

(If you're keeping this page, I would nominate 6by9 to investigate, since he raised the original issue - #1893 😉).

**Comment by aallan** [comment]
No one picked this up inside the 7 day closure window. So closing due to #1911.

**Pull request closed without merging**
