### PR TITLE
Revised scratch gpio doc

### PR DESCRIPTION
**Pull request by timrowledge**
Add new commands and links to frizzing diagrams for example wiring.

Let's see if this does things right...

### CODE REVIEW

**Comment by JamesH65** [comment]
@timrowledge Is this PR still valid? I'll push to copy edit if you can confirm. Thanks.

**Comment by timrowledge** [comment]
Yes; though I'm not completely convinced my GitHub setup is still correct since it just told me there is a gian pdf of a model airplane plan in there... oh, wait, there is. I'll just delete that. So at least as far I can work out it's good to go.

**Comment by JamesH65** [comment]
Thanks Tim, I'll push it forward.

**Comment by LornaLynch** [comment]
There are some errors in the picture captions here: is there any way that I can edit these directly? If not, let me know and I'll rewrite the text here so it can be updated in the diagram.

**Comment by timrowledge** [comment]
The images are mostly generated from Fritzing or Scratch, so if you can point me to the issues I'll fix them ASAP.

**Comment by LornaLynch** [comment]
@timrowledge corrected text below: there's a query about one of the resistor values. 

Otherwise, I still need to check the textual diffs. 

usage/scratch/gpio/images/gpio-demo-breadboard.png

Wiring layout for the Scratch GPIO server example, ‘gpio-demo’. Ideally, add a Camera Module too. 

usage/scratch/gpio/images/gpio-servoDemo.png

Wiring layout for the Scratch GPIO servo example, ‘gpio-servoDemo’. 

Do not take 5V from the Raspberry Pi: use a separate power source, such as a battery. A typical servo would pull far too much current from the Pi. Remember to join the ground of your battery to the ground of the Pi. 

usage/scratch/gpio/images/gpio-ultrasonic.png

Wiring layout for the Scratch GPIO servo example, ‘gpio-ultrasonicDemo’. 

SR04 uses 5V, but the Raspberry Pi wants no more than 3.3V, so we  split the ‘echo’ pin output voltage. Use a 10kΩ resistor connected to the ground pin, and a 47kΩ resistor [CHECK VALUE IS CORRECT!!] connected to the echo pin. The wire to GPIO 26 goes in the middle, and joins the two together.

**Comment by LornaLynch** [comment]
Hi again @timrowledge: do you need to give me access to your branch? I can't edit the (textual) diffs at the moment.

**Comment by AisforAstronaut** [comment]
@timrowledge Please give me and/or Lorna access to your branch for editing. Thank you!

**Comment by timrowledge** [comment]
OK, I see the typos you're pointing to. The last one- the SR04 related one, is actually correct since the way resistor values are written does indeed make 4k7Ω what we need.

As for providing access, I'll see if I can work out how... or if someone cares to just tell me the magic incantation?

**Comment by timrowledge** [comment]
Revised the images so hopefully they are complete. 

Best thing I can think of is to send you the Fritzing files so you can update them locally if needed.
[ScratchGPIO-fritzing.zip](https://github.com/raspberrypi/documentation/files/822041/ScratchGPIO-fritzing.zip)

**Comment by LornaLynch** [comment]
Hi @timrowledge, does this help with the edit permissions issue?  https://help.github.com/articles/about-branch-restrictions/

I'm just looking at the diagrams now: thanks for the clarification about the 4k7Ω thing! I wouldn't have known that.

**Comment by LornaLynch** [comment]
@timrowledge I've edited the text in the diagrams - thanks. Revised copies attached for you to include. Am I correct that one (without the LL in the filename) had no textual label? 

[Fritzing diagrams text edited.zip](https://github.com/raspberrypi/documentation/files/827283/Fritzing.diagrams.text.edited.zip)

**Comment by timrowledge** [comment]
Correct on the no label. 

The 4k7 thing is a neat trick to avoid trying to see a decimal point, failing, and making a circuit that releases the magic smoke at an inopportune time.

**Comment by timrowledge** [comment]
Lorna, so does this mean I’ve completed all the stuff I need to do? Is there any strange git-magic I’m supposed to perform or are all the bits in place now?

tim
--
tim Rowledge; tim@rowledge.org; http://www.rowledge.org/tim
New: It comes in different colors from the previous version.

**Comment by LornaLynch** [comment]
@timrowledge You need to change the existing diagrams in your timrowledge:master fork to the ones that I have edited. I think it makes sense for you to keep this in your PR, rather than me starting another one at my end and potentially creating a conflict. 

I still don't have access to your fork to edit your textual files, which I need to do before we can merge the commit. If the link above didn't help, you could try making me a collaborator on your repository: https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/ - I promise you can remove me as soon as we're finished!

**Comment by timrowledge** [comment]
At least in theory I’ve added you; no guarantees since I know slightly less about  dealing with github than the average banana knows about quantum electrodynamics (which I do actually know a bit about).

Once you’ve got the stuff we should simply remove my branch completely because it simply doesn’t have any relevance any more. There’s a tiny chance I might ask to have a small explanation of using MQTT from Scratch added sometime but since I’m not getting paid to do this stuff anymore I’m not going to overly exert myself over it.

> On 10-03-2017, at 2:14 AM, Lorna Lynch <notifications@github.com> wrote:
> 
> @timrowledge You need to change the existing diagrams in your timrowledge:master fork to the ones that I have edited. I think it makes sense for you to keep this in your PR, rather than me starting another one at my end and potentially creating a conflict.
> 
> I still don't have access to your fork to edit your textual files, which I need to do before we can merge the commit. If the link above didn't help, you could try making me a collaborator on your repository: https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/ - I promise you can remove me as soon as we're finished!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


tim
--
tim Rowledge; tim@rowledge.org; http://www.rowledge.org/tim
Useful random insult:- Calling her stupid would be an insult to stupid people.

**Comment by LornaLynch** [comment]
Looks like the permissions thing worked, @timrowledge: I'll get onto the edits now. Thanks!

**Comment by LornaLynch** [comment]
@JamesH65 I've copy edited all the diffs, and I've also edited the Fritzing diagrams (zip attached). I have a couple of queries for you.

- In hardware/computemodule/cm-emmc-flashing.md (circa line 9) - replace Windows 7 with Windows 8 or 10? 

- configuration/raspi-config.md  - (circa lines 95-100) Remove references to Rastrack as this is now out of date? 

- hardware/computemodule/cm-peri-sw-guide.md (line 59) should 'bootcode.bin is found' read 'bootcode.bin is **not** found'? 

Scratch GPIO README  - line 49 and following: does the Sensors and Motors folder need to be linked to in the first instance? 

Scratch GPIO README - lines 227-235: the spaces before and after the pipes aren't consistent. Can you check they make sense and correct as necessary? 

[Fritzing diagrams text edited.zip](https://github.com/raspberrypi/documentation/files/838899/Fritzing.diagrams.text.edited.zip)
Existing diagrams in this PR need to be replaced with the ones in the zip file.

**Comment by JamesH65** [comment]
What I don't understand is why there are changes to the CM documentation when this is about Scratch GPIO which seems unrelated. That's where the conflicts are...

**Comment by JamesH65** [comment]
OK, look like this PR has a load of files in it unrelated to the Scratch GPIO stuff. These are the ones causing the merge issues because they are old and out of date with the current database. I'm not happy merging them at this point, so will recreate a new PR with just the GPIO stuff in it. Not sure what to do with the copy editing done of these out of date files though, I suspect we might need to redo the changes on the latest database.

File being removed from the PR are -

hardware/computemodule/cm-designguide.md
hardware/computemodule/cm-emmc-flashing.md
hardware/computemodule/cm-peri-sw-guide.md
raspbian/applications/camera.md
configuration/raspi-config.md

Of these the final one seems to have a fair bit of work done on it, so I will attempt to merge that separately.

**Comment by JamesH65** [comment]
Superseded by #581

**Comment by JamesH65** [comment]
I've been cross checking the extraneous files, and it looks like, apart from a minor niggle I have fixed and merged, these are already merged to the docs. So I am going to close this issue, which is now replaced by #581

**Pull request closed without merging**
