### PR TITLE
Remove technical-faq.md

### PR DESCRIPTION
**Pull request by JamesH65**
Most content of this file was moved to the main FAQ, so it can now be removed.

### CODE REVIEW

**Comment by andrum99** [comment]
See also the long-running saga of raspberrypi.org/documentation being out of sync with this repo - see #1227.

**Comment by JamesH65** [comment]
Indeed. We now have a guy who will be taking on docs full time (I do other stuff..sometimes), so hopefully will get some movement on that. It does need a revamp.

**Comment by lurch** [comment]
https://github.com/raspberrypi/documentation/pull/1163#issuecomment-501068083 :laughing:

**Comment by andrum99** [comment]
> [#1163 (comment)](https://github.com/raspberrypi/documentation/pull/1163#issuecomment-501068083) 😆

It seems we have been here before 😮😋

**Pull request merged**
