### PR TITLE
Add RPi Zero 2 W overclocking defaults

### PR DESCRIPTION
**Pull request by MichaIng**

### CODE REVIEW

**Comment by lurch** [comment]
ping @popcornmix

**Comment by popcornmix** [comment]
I don't have a Pi02 to hand, but looking at the code, I think gpu_freq (and so isp/h264/v3d) is 300, not 400.
arm is 1000 and core is 400.

@MichaIng do you have a Pi02 board to confirm this?

**Comment by MichaIng** [comment]
Not sure whether I derived it from RPi 3 (same SoC). Will check back.

**Comment by popcornmix** [comment]
> Not sure whether I derived it from RPi 3 (same SoC)

The code uses 300 for the SOC (2836) with an exception for RPi3 to set it to 400.

So I'd like this PR corrected to 300 for isp/v3d/h264,
or additional evidence provided that Pi02 does use 400.

**Comment by MichaIng** [comment]
Verified and fixed. Looks like I derived it from RPi 3 that time.

**Review by popcornmix — APPROVED** [review]

**Pull request merged**
