### PR TITLE
Fix pose_estimation_tf.json syntax errors

### PR DESCRIPTION
**Pull request by ahatstat**
Removed an extra " and trailing , from the sample json

### CODE REVIEW

**Comment by lurch** [comment]
ping @davidplowman

**Comment by davidplowman** [comment]
Thanks for spotting this. Clearly the code (libcamera-apps/assets/pose_estimation_tf.json) is fine so not sure how that got mangled, We appreciate the fix!

**Comment by lurch** [comment]
So is this good to merge @davidplowman ?

**Comment by davidplowman** [comment]
Yes!

**Review by lurch — APPROVED** [review]

**Pull request merged**
