### PR TITLE
Add more resource info

### PR DESCRIPTION
**Pull request by weg2g**
More info for each linux filesystem

### CODE REVIEW

**Comment by XECDesign** [comment]
Why not link to the source instead (http://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html)? The Debian wiki link on there already opens up a few other resources. If it's of value, why not include all the relevant information on the page itself, without going to an external source?

This feels a bit like SEO.

**Comment by lurch** [comment]
> This feels a bit like SEO.

Yeah, especially when it says "we offer private custom tutoring classes..." at the bottom of the page :confused:

**Comment by weg2g** [comment]
I just checked Linux foundation docs and mine is more comprehensive than theirs. 

I can not include all of them as it includes long (20 pages). Also, we spent months to preparing docs, so just we like to maintain our copywright over our contents. 

Anyway, if you think it is SEO, go ahead and reject my changes. 

Also, "we offer private custom tutoring classes" is a part of web page template not SEO

**Comment by JamesH65** [comment]
As before, we are not keen on links offsite for things like this. Will discuss with comms.

**Comment by JamesH65** [comment]
Decided this is not a suitable change for our documentation, too 'commercial', and too detailed for the intended audience.

**Pull request closed without merging**
