### PR TITLE
Remove Windows 8 ARM from FAQ

### PR DESCRIPTION
**Pull request by andrum99**
Nobody is interested in this.

### CODE REVIEW

**Comment by JamesH65** [comment]
Not sure why it was included in the first place, I guess its was a FAQ some years ago! So LGTM. @lurch

**Comment by lurch** [comment]
:man_shrugging:  I don't read the RPi forums, so I have no idea which Q.s are currently F.A. :wink:

**Comment by andrum99** [comment]
Well there's certainly FA interest in this one.

**Comment by JamesH65** [comment]
Will need to be rebased onto recent merge, once done will merge this.

**Comment by andrum99** [comment]
Closing as I can't figure out an easy was to resolve the merge conflicts.

**Pull request closed without merging**
