### PR TITLE
Compute module dt-blob for cameras & display updates

### PR DESCRIPTION
**Pull request by 6by9**
Display blobs were missing any CM3 config.

Verified all 5 blobs on both CM and CM3.

Most are now simple additions to firmware/extras/dt-blob.dts, so it is obvious the bit that has been edited, particularly if the master dt-blob.dts gets updated.
Previously they seemed to be semi-random hacked together jobs.

### CODE REVIEW

**Comment by XECDesign** [comment]
Should the goo.gl link point to the file in raspberrypi repo rather than the fork?

**Comment by 6by9** [comment]
Which goo link in particular? I thought I'd updated them all as they were pointing to the adam-lee fork :-(

**Comment by 6by9** [comment]
Ah, spotted https://goo.gl/WZp8Qk as going to my repo. Will fix.

**Comment by 6by9** [comment]
Updated to move that first goo.gl link. 
Thanks for the sanity check (I thought I'd been through that several times already).

**Comment by 6by9** [comment]
@XECDesign Anything else you want changed?

**Comment by XECDesign** [comment]
Looks good to me, but merging is up to the documentation team.

**Comment by LornaLynch** [comment]
I've copy edited the changes, but I'd be happier if someone with a better understanding of the code did the merge.

**Comment by XECDesign** [comment]
I think @JamesH65 is the only one who can do that then.

**Comment by JamesH65** [comment]
I've merged, but for some reason cannot close the PR...if anyone else can please go ahead. Or do they auto close...hmm...

**Comment by bennuttall** [comment]
Merging closes a PR :)

**Comment by LornaLynch** [comment]
Thanks guys!

**Pull request merged**
