### PR TITLE
changed reccomended editor for rc.local to nano instead of vim

### PR DESCRIPTION
**Pull request by blessedbiped**
nano is generally the recommended editor in the rpi docs, just making this page match.

### CODE REVIEW

**Comment by bennuttall** [comment]
:(

**Comment by blessedbiped** [comment]
I know, sorry. I love it now, I just remember the first time I accidentally opened vim- it wasn't a pleasant experience as a new user.

**Comment by bennuttall** [comment]
I'm a Vim user, I don't get Nano. But Nano is pre-installed and Vim is not, so this PR is fine.

While Vim is difficult to use for the first time, I don't think Nano is all that much better. If you're booted to desktop you're probably better off opening Leafpad, but you can't assume that as we don't boot to desktop by default.

**Comment by bennuttall** [comment]
Note: Vi is preinstalled, but Vim is not.

Vim allows use of arrow keys in input mode, whereas Vi does not (and annoyingly enters escape characters when you try) which is a real pain, even for seasoned Vim users.

**Pull request merged**
