### PR TITLE
Correction/improvement of the bridge section

### PR DESCRIPTION
**Pull request by jpcornil-git**
PR related to https://github.com/raspberrypi/documentation/issues/1397#

### CODE REVIEW

**Comment by JamesH65** [comment]
@jpcornil-git If this PR is still relevant given today's merge of  #1333, can you redo it to match the changes please?

**Comment by JamesH65** [comment]
@epoch1970 I guess this one can be closed as well???!!

**Comment by epoch1970** [comment]
Absolutely. it is covered by #1333

**Comment by jpcornil-git** [comment]
Much better, I was also suggesting to disable networking service before
enabling networkd (should only be one managing network)

sudo systemctl disable networking.service
sudo systemctl enable systemd-networkd

Cheers
jpc

**Comment by epoch1970** [comment]
There is no _need_ to disable networking service, in order to get a working setup.
So I would leave it alone.

**Comment by JamesH65** [comment]
Thanks all!

**Comment by jpcornil-git** [comment]
I would recommend to either:
- mention that no network interfaces should be configured in
/etc/network/interfaces when systemd-networkd is used (avoid conflicting
dhcp clients, race conditions between both network mngt systems, ...), i.e.
only use /etc/dhcpcd.conf
- disable legacy networking.services (avoid issues related to mixed
configurations by construction)

Making that explicit will ring a bell to whoever has an issue after
applying something seen on internet based on legacy networking.services (or
even proactively prevent it)

Cheers,
jpc

Le ven. 24 avr. 2020 à 17:53, James Hughes <notifications@github.com> a
écrit :

**Comment by epoch1970** [comment]
I think I’ll agree to disagree.

Yes ifupdown must die.
No it is not the job of this guide to right every wrong. Its job is to work, out of the box, with the advertised Raspbian version. I think it does that.
Otherwise we’ll need a paragraph about how not to shoot yourself in the foot by making resolv.conf immutable, having ip=1.2.3.4 in cmdline.txt and all kinds of folklore.

Cheers

**Comment by jpcornil-git** [comment]
Agree about the 2nd paragraph :-)

just saying that:

sudo systemctl enable systemd-networkd

<https://github.com/raspberrypi/documentation/blob/master/configuration/wireless/access-point-bridged.md#define-the-bridge-device-ip-configuration>is
changing the box networking behavior/create a slipery slope and that:

sudo systemctl disable networking.service

<https://github.com/raspberrypi/documentation/blob/master/configuration/wireless/access-point-bridged.md#define-the-bridge-device-ip-configuration>(or
a note about possible conflicts) fixes potential related/vicious issues.

Feel free to continue to disagree as well/nothing wrong with that, I said
what I had to say/won't insist anymore :-)

Cheers,
jpc

**Comment by epoch1970** [comment]
First of all I have no authority here, your vote is a good as mine.

I could follow you on the idea that "systemd-networkd enable" are words none should ever utter :) 
Unfortunately, as Raspbian is today, it is the only reasonable option because dhcpcd does not handle bridge creation. It can be done, I have a prototype script lying somewhere in the forums, it's not perfect and anyways the destiny of dhcpcd in Raspbian is better to be discussed between its author and RPT.

So ATM the least of 2 evils (ifupdown, systemd) is to enable networkd and have it create the bridge. Personally I hope dhcpcd will live on and prevail in future Raspbian releases. I think it's very good software and a great asset to Raspbian.

**Comment by jpcornil-git** [comment]
Legacy-only networking can be used as well but a bit more tricky/scattered
to setup when a wifi ifce is involved, e.g.
https://wiki.debian.org/BridgeNetworkConnections#Bridging_with_a_wireless_NIC

Cheers
jpc

**Comment by lurch** [comment]
ping @XECDesign in case he has anything to add to the discussion here? :shrug:

**Comment by XECDesign** [comment]
Nothing useful, unfortunately. In a display of cognitive dissonance, I agree with both points of view.

Yes, you should avoid having 3 different network managers. Yes, if the user hasn't configured ifupdown it won't be used anyway. Yes, there will be people who followed random guides online from 2010 or have a cargo cult setup put together from random forum posts and there's no way this guide can undo all the damage.

I'd lean towards the notion that disabling ifupdown does no harm and is technically the right thing to do.

**Pull request closed without merging**
