### PR TITLE
Documentation: New page for cmdline.txt

### PR DESCRIPTION
**Pull request by JamesH65**
Added a new page to describe the cmdline.txt file and populated
it with as much as I know for the moment. It's not exhaustive
so will need filling out at a later date.

### CODE REVIEW

**Comment by JamesH65** [comment]
See issue #135

**Comment by LornaLynch** [comment]
Edited the text: at line 26-27, is line 27 supposed to be a sub-bullet of line 26 (splash), or a separate item?

**Comment by JamesH65** [comment]
All looks a bit weird that section. Need to get rid of thee back ticks for all the first parts of the line (leaving the examples), but the overall structure looks correct ie plymouth.ignore_serial_console` is a separate item but with no description (Still trying to find out what it does, but not worth delaying the whole page over it)

**Comment by AisforAstronaut** [comment]
Can you check that the changes to the back ticks are correct?

**Comment by JamesH65** [comment]
That looks fine.

**Comment by JamesH65** [comment]
Done.

**Pull request merged**
