### PR TITLE
Change company name to use small "r", updated link

### PR DESCRIPTION
**Pull request by Digital-Larry**
Link now points at "Getting Started for Raspberry Pi" page.

### CODE REVIEW

**Comment by JamesH65** [comment]
That link (and the original) are giving me the following message.

Your connection is not private
Attackers might be trying to steal your information from remote.it (for example, passwords, messages or credit cards). Learn more
NET::ERR_CERT_AUTHORITY_INVALID


So I'm inclined to remove the whole link until this is fixed.

**Comment by XECDesign** [comment]
Seems to work okay for me, so maybe it was just a temporary ssl issue.

**Comment by Digital-Larry** [comment]
Thanks, I believe that overnight we had a temporary server issue which was
subsequently resolved.

Gary Worsham
Director of Applications Engineering
remot3.it, Inc.

**Comment by JamesH65** [comment]
OK, working for me. Thanks.

**Pull request merged**
