### PR TITLE
Update access-point.md

### PR DESCRIPTION
**Pull request by scruss**
Document had no title due to all headings having an extra `#`

### CODE REVIEW

**Comment by JamesH65** [comment]
Well I never, not noticed that before! Thanks!

**Comment by bennuttall** [comment]
:+1:

**Comment by scruss** [comment]
Seems also to affect:

    usage/xbmc/README.md        # though this is a trivial redirect
    configuration/config-txt/conditional.md
    configuration/config-txt/camera.md
    configuration/config-txt/memory.md
    configuration/config-txt/video.md
    configuration/config-txt/overclocking.md
    configuration/config-txt/audio.md
    configuration/config-txt/codeclicence.md
    configuration/config-txt/misc.md
    configuration/config-txt/boot.md

(configuration/config-txt was all one file at one point, yes?)

found with

    find . -type f -iname '*.md' -print0 | xargs -0 grep -L '^#[^#]'

If you have document tests, that regex is going to catch all markdown files without titles.

(why yes, I *did* used to write tests for Collins dictionaries, thank you for asking … ☺)

**Comment by JamesH65** [comment]
Yup, side effect from when I split up config.txt.

On 11 December 2017 at 16:27, Stewart C. Russell <notifications@github.com>
wrote:

> Seems also to affect:
>
> usage/xbmc/README.md        # though this is a trivial redirect
> configuration/config-txt/conditional.md
> configuration/config-txt/camera.md
> configuration/config-txt/memory.md
> configuration/config-txt/video.md
> configuration/config-txt/overclocking.md
> configuration/config-txt/audio.md
> configuration/config-txt/codeclicence.md
> configuration/config-txt/misc.md
> configuration/config-txt/boot.md
>
> (configuration/config-txt was all one file at one point, yes?)
>
> found with
>
> find . -type f -iname '*.md' -print0 | xargs -0 grep -L '^#[^#]'
>
> If you have document tests, that regex is going to catch all markdown
> files without titles.
>
> (why yes, I *did* used to write tests for Collins dictionaries, thank you
> for asking … ☺)
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_raspberrypi_documentation_pull_781-23issuecomment-2D350776548&d=DwMFaQ&c=DpyQ_ftY536pf7wCBQXXU58xADDRY77THQzJu1OmzOo&r=w09_2ePv8G3zRjoV19Wm1Q6rI7CDlOns4PuRv2hHkek&m=Wk9xp9bCJ11-Lu_n9Zrb7u85DB47GQ554PsEGN6lr3E&s=6lXNXltTxeNqSmkrev7-TrD1rjT9PChfbrPIfdEAlu8&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADqrHY0OiCIm3p0tAbmcYhbyVmnU6MRZks5s-5FVfWgaJpZM4Q9btV&d=DwMFaQ&c=DpyQ_ftY536pf7wCBQXXU58xADDRY77THQzJu1OmzOo&r=w09_2ePv8G3zRjoV19Wm1Q6rI7CDlOns4PuRv2hHkek&m=Wk9xp9bCJ11-Lu_n9Zrb7u85DB47GQ554PsEGN6lr3E&s=kcEUBXufwr5JqjY0iSZQVmkuMdM-5vOVJ9cdnkj0pDE&e=>
> .
>



-- 
James Hughes
Principal Software Engineer,
Raspberry Pi (Trading) Ltd

**Comment by JamesH65** [comment]
OK, have corrected all the config.txt entries, should appear soon.

**Pull request merged**
