### PR TITLE
Part numbers for small angular motor and 3x3 LED

### PR DESCRIPTION
**Pull request by mutesplash**
I purchased it from here

https://education.lego.com/en-us/products/lego-technic-small-angular-motor/45607

verified the Type ID with BuildHAT and copied the item number from the bottom of the box.

### CODE REVIEW

**Comment by mutesplash** [comment]
3x3 was purchased and verified from here

https://education.lego.com/en-us/products/lego-technic-color-light-matrix/45608

**Comment by aallan** [comment]
ping @topshed

**Comment by topshed** [comment]
All good. Thanks

**Review by aallan — APPROVED** [review]
@topshed said "Yes!"

**Pull request merged**
