### PR TITLE
Link camera page to libcamera page

### PR DESCRIPTION
**Pull request by lurch**
I'm unsure if the wording I've used is correct or if it needs tweaking.
ping @JamesH65 and @6by9

### CODE REVIEW

**Comment by JamesH65** [comment]
Are we at a point where ware happy referring to the old camera stack as legacy ie We can now do the majority of stuff with libcamera that we can do with the original suite?

**Comment by lurch** [comment]
This issue https://github.com/raspberrypi/userland/issues/688 is what inspired me to create this PR. I was just kinda surprised that there was no link from the camera page to the libcamera page. But if libcamera isn't "fully ready" yet (I've never actually used it myself), perhaps that was deliberate? :shrug: 
Feel free to tweak the wording as you see fit.

**Comment by 6by9** [comment]
libcamera is the route that we will push for any 64 bit system, and really for any 32bit Pi2/3/4.
Pi0/1 will probably be stuck on the old stack as they don't have the processing grunt for running the control algos on the ARM.

David P has written replacement versions of raspistill and vid for libcamera, although I haven't tried them. The gap is the Python bindings, but that is being addressed.

**Comment by aallan** [comment]
I'd encourage you to wrap this PR up in the next week or so as we're in the process of transitioning the documentation from the current Markdown-based source format to Asciidoc. At some point soon — probably around the end of June, beginning of July — we will freeze the current documentation repo. After that time contributions and PRs based on the Markdown source will not be accepted, and any PRs that are still open will be closed.

See #1911 for full details.

**Pull request merged**
