### PR TITLE
Add details to access-over-internet

### PR DESCRIPTION
**Pull request by timfernando**
Added a short intro to remote access service Dataplicity to explain how it works and what it does. Removed the small link from the bottom too.

Relates to issue #414

### CODE REVIEW

**Comment by phiney0711** [comment]
Is there a valid reason to change the listed order (from top-of-page to bottom-of-page) for the remote access alternatives to port-forwarding?  (disclosure: I am a Weaved employee)

**Comment by timfernando** [comment]
It seemed sensible for it to be alphabetical below the overall heading of port-forwarding (as it was lumped under "alternatives" before). Is there a better order that you would suggest?

**Comment by pelwell** [comment]
But Dataplicity appears after port-forwarding, so it is already out of order. To avoid any suggestion of trying to give Dataplicity greater prominence over Weaved (I have no connection to either and no preference) then you could leave the order as it was. Alternatively, a declaration of your own interests might help to clear the air.

**Comment by timfernando** [comment]
@pelwell no problem, I've adjusted the order. 

Disclosure: I've written a [blog article using Dataplicity](http://medium.com/@timfernando/how-to-build-a-raspberry-pi-thermometer-you-can-access-anywhere-a-beginner-s-guide-4ad44ce9f4c9) and am connected to the team behind it, but I am not an employee.

**Comment by timfernando** [comment]
@pelwell @phiney0711 Thought and suggestion: a stub page with a list of one-liners with links to separate pages for each? Perhaps that would be reasonable for all concerned?

**Comment by bennuttall** [comment]
Port forwarding should be at the top because it's probably the first thing a user should try. Let's leave it. The other options should really be under the heading "Alternatives" or similar, with subheadings "Weaved" and "Duplicity".

I don't think there's a problem with the current presentation, but if the list of examples was longer it would make sense to cut it to a list of links to other pages for each alternative solution.

**Comment by bennuttall** [comment]
I'm going to merge and fix the headings.

**Comment by phiney0711** [comment]
looks good.  thanks!

**Pull request merged**
