### PR TITLE
Updated bootmode docs inline with Issue 501

### PR DESCRIPTION
**Pull request by leepenney**
Added a statement to exit parted and comments from @mkretzschmar about checking system time

### CODE REVIEW

**Comment by AisforAstronaut** [comment]
File checked. Changes made for clarity and style. Pushing back for technical checking.

**Comment by JamesH65** [comment]
More changes needed on this, I'll quickly do them.

**Comment by AisforAstronaut** [comment]
👍

**Comment by JamesH65** [comment]
Have made the changes..

**Comment by AisforAstronaut** [comment]
I'll take a look.

**Comment by AisforAstronaut** [comment]
Technical question: There is a option to install 'Raspbian Lite (or heavy
if you want)'. What is the correct technical term for non-Lite Raspbian?
'The full version'? Or something else?

**Comment by XECDesign** [comment]
I believe it's 'Raspbian with PIXEL', to be consistent with the downloads pages.

**Comment by AisforAstronaut** [comment]
Thank you!

**Comment by AisforAstronaut** [comment]
File checked. Changes made for clarity and style. Pushing back for technical checking.

**Comment by JamesH65** [comment]
looks good.

**Pull request merged**
