### PR TITLE
Renaming etcher to balenaEtcher

### PR DESCRIPTION
**Pull request by gmkey**
Etcher has been renamed to balenaEtcher and it's website changed to www.balena.io/etcher/

### CODE REVIEW

**Comment by bennuttall** [comment]
Are you saying this as a member of the public or are you a Balena employee?

It doesn't seem to me that they have renamed the tool "balenaEtcher" just that they sometimes refer to it with the company name first.

They still refer to "Etcher Pro" and there's a sentence that says "So we built Etcher, an SD card flasher app" and there are links to "Etcher for Windows", etc.

**Comment by JamesH65** [comment]
Also, the word Etcher is used on more than one page in our docs, so if we need to change we need to change on all pages that use it.

**Comment by gmkey** [comment]
First: I'm a member of the public. 
Second: I've installed the app on my Mac and although it can still be found as Etcher, the name presented to me is balenaEtcher. (balenaEtcher.app)

If need be, I'm more than happy to create change requests for these.

**Comment by gmkey** [comment]
https://www.balena.io/blog/resin-io-changes-name-to-balena-releases-open-source-edition/

**Comment by bennuttall** [comment]
I don't think we should change it, unless someone from Balena agrees that's correct usage. @lurch do you know of someone who would know for sure?

**Comment by gmkey** [comment]
Their statement seems pretty obvious to me. But then again, you might be better of at the source!

**Comment by gmkey** [comment]
closing this one in favour of #1085 , which contains proposals for all  documents

**Pull request closed without merging**
