### PR TITLE
camera: Rename libcamera-* to rpicam-*

### PR DESCRIPTION
**Pull request by naushir**
This change reflects the new naming from libcamera-apps to rpicam-apps. All documentation, examples, files are updated to reflect this renaming.

### CODE REVIEW

**Comment by naushir** [comment]
This is a placeholder for the big libcamera-apps rename change coming up.  We need to sync the doc update with the changes with the changes in our various libcamera repos, so I have marked it as draft for now.

**Comment by lurch** [comment]
Will the camera-apps installed on the Legacy Bullseye OS also be getting this rename from `libcamera-*` to `rpicam-*` ?

**Comment by naushir** [comment]
This change is now live, so we can merge when we are ready.

**Review by aallan — APPROVED** [review]
YOLO

**Comment by aallan** [comment]
@naushir Came up in the tutorial repo, this PR has package names changing, e.g.

Screenshot 2023-11-15 at 15 32 43

is this correct, or is it just the command line toolnames that are changing?

**Comment by naushir** [comment]
Yup, we are changing the package names as well.  I am just about to send an email to @XECDesign to build the updated packages when he gets a chance.

**Comment by naushir** [comment]
Oh no.  But that change is wrong :(  That should remain libcamera-dev.  Will post an update to fix this now...

**Pull request merged**
