### PR TITLE
Update README.md / video group

### PR DESCRIPTION
**Pull request by weberjn**
must add user to video group

### CODE REVIEW

**Comment by JamesH65** [comment]
Can you tell me the reason for this? In my tests, this change was not necessary to take stills or videos from a webcam.

**Comment by weberjn** [comment]
I got permission denied, which was gone after adding my user to the video
group.

There are lots of hits on google: raspberrypi webcam permission denied

https://raspberrypi.stackexchange.com/questions/50505/usb-webcam-cant-take-a-picture

this one explicitely states the group thing:

https://medium.com/home-wireless/headless-streaming-video-with-the-raspberry-pi-zero-w-and-raspberry-pi-camera-38bef1968e1

Am Mi., 2. Jan. 2019, 12:21 hat James Hughes <notifications@github.com>
geschrieben:

**Comment by JamesH65** [comment]
I pressume you were not logged in as the user `pi`. Looks like adding a new group does not add the new user to the video group automatically. I'll have a think as to the best way of dealing with this.

**Comment by weberjn** [comment]
Of course, I am always weberjn.
For me the simplest way is to add weberjn to video.

looks like this is the usual way on Linux:

https://www.tldp.org/HOWTO/Webcam-HOWTO/dev-intro.html
3.2

https://ubuntuforums.org/showthread.php?t=1305377

Am Mi., 2. Jan. 2019, 14:34 hat James Hughes <notifications@github.com>
geschrieben:

**Comment by weberjn** [comment]
Looks good. I do like that you added a check.

**Pull request merged**
