### PR TITLE
net_tutorial.md: small fixes

### PR DESCRIPTION
**Pull request by vazhnov**
Too much sudo;
Use 'tail -F' is more universal than 'tail -f';
Use Ctrl+Z for exit is wrong — use Ctrl+C.

### CODE REVIEW

**Comment by JamesH65** [comment]
Looks good to me, pushing to copy edit

**Comment by LornaLynch** [comment]
I can look at the copy now.

**Comment by LornaLynch** [comment]
The copy looks OK to me now. Ready for final check and merge.

**Comment by vazhnov** [comment]
Thank you!

**Pull request merged**
