### PR TITLE
Update VNC instructions to with detailed instructions for running TigerVNC on Linux

### PR DESCRIPTION
**Pull request by nathan-contino**
* closes https://github.com/raspberrypi/documentation/issues/3243

### CODE REVIEW

**Review by aallan — APPROVED** [review]

**Comment by andrum993** [comment]
It should not longer be necessary to use TigerVNC to connect to wayvnc running on Raspberry Pi OS, since wayvnc has been updated to work with the RealVNC client.

**Comment by aallan** [comment]
TigerVNC will still work though, so we may as well recommend it.

**Comment by andrum993** [comment]
> TigerVNC will still work though, so we may as well recommend it as its cross platform.

I wasn't criticising the PR, it was just a head up to mention that things have changed since the issue was raised.

I would have thought it would be better to stay with the RealVNC client since it is also cross-platform, and it seems sensible to only recommend a single VNC client rather than having to use one for X11, and one for Wayland-based desktops.

Also note that wayvnc is most likely going away soon: RealVNC have stated publicly that their VNC server on Raspberry Pi OS will get Wayland support some time in the first half of 2024, at which point I expect it will become the default VNC server on Raspberry Pi OS's Wayland desktop. We will then be back to the situation on previous releases, where RealVNC was the default VNC client and server for all configurations of Raspberry Pi OS.

**Comment by aallan** [comment]
> at which point I expect it will become the default VNC server on Raspberry Pi OS's Wayland desktop.

Why?

**Comment by andrum993** [comment]
> > at which point I expect it will become the default VNC server on Raspberry Pi OS's Wayland desktop.
> 
> Why?

Because the RealVNC server is, in some ways, a better VNC server than wayvnc, and it has been the default VNC server for many years on Raspberry Pi OS so people will have existing installations that expect to be using it. Anyway, you may want to speak to someone within Raspberry Pi who knows what their actual plans are. I've kind of drifted into "teaching your granny how to suck eggs" territory now, so I'll be quiet. Apologies.

**Pull request merged**
