### PR TITLE
Use Raspberry Pi Imager for recovery

### PR DESCRIPTION
**Pull request by timg236**
Direct people towards the Raspberry Pi Image for creating recovery sd cards. I've created an internal ticket to update the text on the downloads page accordingly.

### CODE REVIEW

**Comment by timg236** [comment]
Thanks!

**Comment by lurch** [comment]
Will the downloads page still be offering a link (even if indirect) to the recovery image, for the benefit of anyone unable to run the Raspberry Pi Imager tool?

**Comment by timg236** [comment]
Yes, that's what I asked, although eventually I think all binaries will be moved to Github as releases and raspberrypi.org will just point to that because it's impractical to try to synchronise documentation updates with software releases.

**Comment by JamesH65** [comment]
> Yes, that's what I asked, although eventually I think all binaries will be moved to Github as releases and raspberrypi.org will just point to that because it's impractical to try to synchronise documentation updates with software releases.

Really should have gone this way ages ago.

**Pull request merged**
