### PR TITLE
Add pi4 and pi400 conditional filters

### PR DESCRIPTION
**Pull request by timg236**

### CODE REVIEW

**Comment by timg236** [comment]
@JamesH65

**Review by lurch — APPROVED** [review]
LGTM

**Comment by timg236** [comment]
Please can you merge it, I don't have merge privileges :)

**Comment by lurch** [comment]
@timg236 Is there (or could there be?) a filter that matches "a BCM2711-based device", i.e. `[pi4 or pi400 or cm4]`

**Comment by timg236** [comment]
You could just change the table entry for [pi4] to read. Pi 4B, CM4, Pi 400 or the entire Raspberry Pi 4 family

**Pull request merged**
