### PR TITLE
Update building.md

### PR DESCRIPTION
**Pull request by realies**
Making the cross-compilation tools installation steps slightly more obvious.

### CODE REVIEW

**Comment by JamesH65** [comment]
Sorry about delay, busy. 

I like the idea, could you add some information on the link command you use to explain the flags? I had to look them up, so adding would be of educational benefit, at least to me!

**Comment by realies** [comment]
@JamesH65, it might make more sense to clone `https://github.com/raspberrypi/tools` to the root of the filesystem or the home folder and reflect that in $PATH instead of linking. Thoughts?

**Comment by JamesH65** [comment]
I think cloning it to root is prone to making mistakes, so not sure what the best approach is here. @pelwell Do you have any thoughts on best practice here?

**Comment by realies** [comment]
@JamesH65, why is cloning to root prone to making mistakes? The other option I suggested is to clone to `~/` and expand to an absolute path in $PATH.

**Comment by JamesH65** [comment]
I'm just a bit wary of doing anything in root since you need to be sudo to do it, and you might clone over something you didn't mean to. Probably just me being paranoid though.

**Comment by pelwell** [comment]
I am equally wary. Cross compilation increases the chances that the user won't have root/sudo access.

I would rather introduce a shell variable to store the place where the toolchain should go, then use that for the clone and in constructing the path.

**Comment by realies** [comment]
@pelwell, the guide already contains `sudo`. I would think most people would fire up a VM just for the purpose of cross-compiling making them the owner. On the other side, I appreciate that the process can be completed without root permissions.

**Comment by pelwell** [comment]
Of course - the escaping is just because of the shell evaluating the parameters of the "echo" command. Without it, the current value of `PATH` is substituted when the line is added to `.bashrc`.

It would be clearer and more effective to make the whole line an unevaluated string using single quotes (`'`). As written now, the `~` will be expanded to `/home/pi` which, although not wrong, probably isn't what you wanted.

**Comment by realies** [comment]
@pelwell, I have tested the code before committing. The cross-compilation tools are cloned to `~/` which gets expanded before being passed to `git clone`. Since the `.bashrc` file would be setting up the environment for the currently logged user, expanding should not be a problem and would keep the absolute path list of locations consistent.

**Comment by JamesH65** [comment]
Sorry about the delay. I'll push to copy edit, and if no-one comment here they don't like the change I will merge it.

**Comment by realies** [comment]
Wondering why the process of updating the documentation is happening so slow.

**Comment by pelwell** [comment]
Wondering why you think that is a good motivational strategy.

**Comment by realies** [comment]
I was unaware that motivational strategy is what is needed. For the good of education, please be better than the speed of bureaucracy. If you require extra hands, let the people know.

**Comment by JamesH65** [comment]
Once a pr is submitted, I do a technical check on it to ensure it it ok. Then it goes to our copy editors who will translate it from engineering speak to English. Then it comes back for another technical check to ensure copy editing hasn't broken it. Then it gets merged
 Every point in the chain can have delays. For example I have been on holiday, and have had higher priority work to do, so unable to look at docs for about a month. Copy editors also have other work to do. Hope that explains it. 

Things are actually a lot quicker nowadays....

**Pull request merged**
