### PR TITLE
Update USB boot mode documentation for recent Pi models

### PR DESCRIPTION
**Pull request by nathan-contino**
Noticed that this section is quite out-of-date. Updated!

### CODE REVIEW

**Comment by nathan-contino** [comment]
@pelwell emailed you about this, but I figured this PR will keep things moving and make it easier to understand my question. Please take a look if you get the chance!

**Comment by nathan-contino** [comment]
@timg236 emailed you about this, but I figured this PR will keep things moving and make it easier to understand my question. Please take a look if you get the chance!

**Comment by timg236** [comment]
Sorry. I don't know about this on pre-Pi4, but everything after that supports USB host boot

**Comment by nathan-contino** [comment]
@ghollingworth Any chance you know which models support USB host boot?

**Pull request merged**
