### PR TITLE
Update FAQ

### PR DESCRIPTION
**Pull request by kompowiec**
EDLC supercapacitors cooperating with a specialized power controller are ideally suited as an energy store for maintaining the power supply. Or use Powerbank.

I'm not sure if it makes sense to include this type of information in this guide, so I did not include it in the end.

### CODE REVIEW

**Comment by lurch** [comment]
Is this already covered by https://github.com/raspberrypi/documentation/blob/master/faqs/README.md#where-is-the-onoff-switch ?

BTW @JamesH65 / @spl237 I guess the "To switch off, if you are in the graphical environment, you can either log out from the main menu, exit to the Bash prompt, or open the terminal." sentence probably needs updating!

**Comment by JamesH65** [comment]
@lurch Have fixed the FAQ "To switch off" section to current scheme. 

As for this PR, I am unsure. It is clearly information that may be useful, but is it enough information? Seems a bit like its teases  the reader with something but never fully explains.

**Comment by kompowiec** [comment]
tbh both pages don't explain why pi there is no protection against card damage. If you think it's worth it, I can give you some solutions, but most of the pages in the documentation do not go in this direction, so I refrained from doing so.

**Comment by aallan** [comment]
In light of #1911 and the lack of progress in a long while I'm marking this PR as 7 day closure.

**Comment by aallan** [comment]
We're deleting the FAQ, see #1913, with the contents distributed throughout the documentation. So closing.

**Pull request closed without merging**
