### PR TITLE
Jamesh65 patch 1#552 SSH instructions

### PR DESCRIPTION
**Pull request by JamesH65**
This is a reformat of the SSH instructions, prompted by #552. It hopefully makes it a bit more obvious that SSH needs to be enabled.

Thoughts?

### CODE REVIEW

**Comment by JamesH65** [comment]
Looks good, thanks @AisforAstronaut

**Comment by AisforAstronaut** [comment]
My changes were only made to README.md. I've just made a load of changes to remote-access/ssh/android.md, and lost them because the branch no longer exists! I haven't made it to remote-access/ssh/ios.md, remote-access/ssh/unix.md or remote-access/ssh/windows.md yet. Is there a way back to these branches?

**Comment by JamesH65** [comment]
That's odd. Thought it was ready for merging. I have pressed the restore brnach button - has it reappeared?

**Comment by AisforAstronaut** [comment]
I'll take a look...

**Comment by AisforAstronaut** [comment]
It is back, but I don't have edit access!

**Comment by JamesH65** [comment]
Hmm, trying to figure this out - there doesn't appear to be a revert button...odd because there was on the other one. Note sure what the difference is.

Only thing that comes to mind is since you have acccess to you changes, create another PR with them in. 

But I'll keep looking.

**Comment by JamesH65** [comment]
And as soon as I comment I find the revert button...

"Add more commits by pushing to the revert-555-JamesH65-patch-1#552 branch on raspberrypi/documentation."

**Comment by AisforAstronaut** [comment]
Still no edit access!

**Comment by JamesH65** [comment]
Can you edit the files in the revert-555-JamesH65-patch-1#552 branch?

(Go to the code tab, then select that branch in the branch dropdown under the code tab)

**Pull request merged**
