### PR TITLE
NOOBS: Partition name must be in all caps

### PR DESCRIPTION
**Pull request by mgaffney**
Document the need for the partition name to be in all caps when creating
the install SD card for NOOBS installation.

### CODE REVIEW

**Comment by XECDesign** [comment]
Why would this be needed?

**Comment by mgaffney** [comment]
Installation failed until I renamed the partition using all caps. Unfortunately, I don't have the error message(s) in front of me but they did mention the case of the partition name.

**Comment by XECDesign** [comment]
I'll double check whether the presence and case of the label makes any difference when using something other than Disk Utility. This feel like a bit of a cargo cult fix.

**Comment by XECDesign** [comment]
Just checked and it seems like NOOBS itself is fine with lowercase FAT32 labels. Don't have a Mac handy to check what's actually going on.

**Comment by lurch** [comment]
@XECDesign Sounds like this is just another occurrence of https://github.com/raspberrypi/noobs/issues/174#issuecomment-51334441 which (despite lots of effort) I never got to the bottom of, and was never able to reproduce :-(

I suggest the issue here gets closed.

**Comment by JamesH65** [comment]
Any consensus yet? Out of my knowledge arena!

**Comment by XECDesign** [comment]
Simon has just formatted two cards with upper and lower case labels and they both work fine. I'd close this one, @JamesH65.

**Comment by JamesH65** [comment]
@mgaffney It would be interesting to know what circumstances caused this to fail, and the errors messages, but they seem to not be available, so closing for the moment. If you feel there is still an issue please reopen.

**Pull request closed without merging**
