### PR TITLE
Update mac.md

### PR DESCRIPTION
**Pull request by csofranz**
Corrected instructions to use VNC with OSX version 10.8 and above

### CODE REVIEW

**Comment by JamesH65** [comment]
I believe this is the correct technical solution, for forwarding to copy edit.

**Comment by LornaLynch** [comment]
I need to make some edits to this, but I don't have access to the branch. @csofranz Is this something you need to enable for me? 

There's also a conflict which needs to be resolved using the command line. I may need to call on someone else to do this.

**Comment by AisforAstronaut** [comment]
@csofranz Please give me and/or Lorna access to your branch for editing. Thank you!

**Comment by csofranz** [comment]
Apologies for the delay - not a git pro; how do I give you the relevant access rights?

**Comment by LornaLynch** [comment]
Does [this](https://help.github.com/articles/about-branch-restrictions/) help? I'm guessing you have protected the branch, perhaps?

**Comment by csofranz** [comment]
Added Lorna and aisforastronaut as collaborators

**Comment by LornaLynch** [comment]
@JamesH65 I changed the wording at line 11 a little to remove the value judgement. Can you check it still makes sense from a technical POV? 

Copy edited: ready for technical check.

**Comment by JamesH65** [comment]
Looks fine, but for some reason not letting me merge directly. Will sort that out.

**Comment by JamesH65** [comment]
OK, weird one. It appears that the entire mac page for VNC has been deleted in the past, replaced with only the instructions for realVNC. 

So I'm going to reintroduce the mac instructions in this PR and link to them from the main VNC page.

**Comment by LornaLynch** [comment]
@JamesH65 Do you mean in it was done in [this commit](https://github.com/raspberrypi/documentation/commit/36e5427c47cd20b53d54a011dfe51ee341a0a133)? It's nothing to do with me, but I'm trying to figure out how to trace changes in GitHub.

**Comment by JamesH65** [comment]
Yes. it removed all other examples stuff except realVNC.

I've spoken to people, and for Pi to Pi stuff realVNC is the way to go. But we need to add back some stuff for other OS's especially Mac, which has a VNC viewer builtin (hence this PR) so you don't need to install realVNC.  There is also some missing realVNC instruction on using it on other platforms (e.g. Windows and Linux). Not really sure how for lay it all out yet, but feel free to investigate!

**Comment by JamesH65** [comment]
It's been a year since this was last referenced, and I'm still not sure what to do about it. The vast majority of people use RealVNC I presume -we don't get many (any?) requests for help doing it other ways. 

I'm inclined to drop this PR, so will close it for the moment. If people feel that the VNC instructions do need broadening, post here and I will reopen.

**Pull request closed without merging**
