### PR TITLE
Made it safer

### PR DESCRIPTION
**Pull request by UnderFact**
I replaced the "/dev/sdd" with "/dev/cats" so that people who aren't paying attention wont break something.

### CODE REVIEW

**Comment by XECDesign** [comment]
I would suggest /dev/sdX and make sure the paragraph before it is also modified accordingly.

**Comment by UnderFact** [comment]
good point, anybody with 26 storage devices will now what their doing
anyway.

**Comment by lurch** [comment]
> anybody with 26 storage devices will now what their doing anyway.

24 ;-)
And even then, it'd still be `/dev/sdx` (all lowercase) and not `/dev/sdX`

**Comment by Frodox** [comment]
> anybody with 26 storage devices will now what their doing anyway.

24 ? On Raspberry Pi? Seriously? :D I think this man would be triply careful with partitions :)
+1 for `sdX`, because  it is **very important** to note, that `sdX`, nor `sdxN`.

**Comment by JamesH65** [comment]
@underfact Would it be possible to rebase this PR against the latest documentation, taking in to account the suggestions above, then I can push to copy edit and get it merged.

**Comment by JamesH65** [comment]
Actually, I'm going to fix this up myself, and will close this PR when have done so. see #536

**Pull request closed without merging**
