### PR TITLE
Update Weaved section of "Access over Internet" to match latest deb

### PR DESCRIPTION
**Pull request by phiney0711**
Remote Access -> Access Over Internet -> Alternatives to Port Fwding -> Weaved section  Updated instructions to match new deb hosted Oct 11, 2016 with support for remot3.it

### CODE REVIEW

**Comment by LornaLynch** [comment]
When this is merged, could someone let me or @lauraclay know? We will have to copy edit the changed text.

**Comment by phiney0711** [comment]
@LornaLynch @lauraclay are there any edits you'd like me to make before merge?

**Comment by bennuttall** [comment]
@LornaLynch you can edit this branch. Click the "files changed" tab and you can see the "edit" button by each file.

**Comment by bennuttall** [comment]
@phiney0711 is this ready to be merged? Do the instructions work as provided now? (do they old ones no longer work?)

Can you confirm the package is still called `weavedconnectd` and the command is still `weavedinstaller`?

**Comment by phiney0711** [comment]
@bennuttall yes ready to merge.  The new deb (still called weavedconnectd) is already live in the Pi repo.  The package name (weavedconnectd) and command (weavedinstaller) remain unchanged.  Thanks!

**Comment by LornaLynch** [comment]
Thanks @phiney0711 and @bennuttall: I'll copy edit the branch and merge it as soon as I can.

**Pull request merged**
