### PR TITLE
Deviceplane

### PR DESCRIPTION
**Pull request by joshwget**
Adds Deviceplane as a vendor for "Access your Raspberry Pi over the internet". We're OSS, but we also have a hosted version so I didn't add the `(OSS)` suffix.

Similar to #1133

### CODE REVIEW

**Comment by lurch** [comment]
Please move your entry to the end of the list :slightly_smiling_face:

**Comment by lurch** [comment]
Also similar to #1344 :wink:

**Comment by joshwget** [comment]
Updated! Didn't see the earlier PR with the request to move to the end.

**Comment by lurch** [comment]
Closing - see https://github.com/raspberrypi/documentation/issues/1439#issuecomment-601694131 because of why.

**Pull request closed without merging**
