### PR TITLE
upgrading faq

### PR DESCRIPTION
**Pull request by asfahrefajd**

### CODE REVIEW

**Comment by JamesH65** [comment]
Although the change is fine, I'm not sure we use the technical-faq any more - will need to check.

**Comment by lurch** [comment]
> I'm not sure we use the technical-faq any more

See https://github.com/raspberrypi/documentation/pull/1163#issuecomment-501068083
:wink:

**Comment by lurch** [comment]
@asfahrefajd Maybe you want to re-target your change against https://github.com/raspberrypi/documentation/blob/master/faqs/README.md ?

**Comment by JamesH65** [comment]
Manually copied to the main FAQ. 

Thanks for the PR.

**Pull request closed without merging**
