### PR TITLE
configuration/UART.md - minor simplifications

### PR DESCRIPTION
**Pull request by andrum99**

### CODE REVIEW

**Comment by andrum99** [comment]
I've also added a quick mention of what is required on the various models of compute module, which fixes #1754.

**Comment by aallan** [comment]
How does this relate to #1849?

**Comment by andrum99** [comment]
> How does this relate to #1849?

It's a reaction to #1849, which purports to solve #1754 but doesn't. This one does. #1849 also adds lots of extra verbage, and if it were up to me that would not get integrated.

I will leave this PR open should you decide it is worth integrating: it contains minor additions to add information which some forum users have requested, and minor corrections, and I believe it is ready to integrate as is.

**Comment by aallan** [comment]
So for clarity, you're arguing this PR should be merged instead of #1849? So it's an either or? Thanks, that clarifies the situation!

**Comment by andrum99** [comment]
> So for clarity, you're arguing this PR should be merged instead of #1849?

That is indeed my position.

**Comment by aallan** [comment]
> That is indeed my position.

Gotcha.

**Pull request merged**
