### PR TITLE
Add link to GPIO usage page for newer models

### PR DESCRIPTION
**Pull request by Granjow**

### CODE REVIEW

**Comment by bennuttall** [comment]
Thanks. I don't know why these are still separate pages. I must remember to merge/update/improve those pages soon.

**Comment by Granjow** [comment]
Thanks for merging :)

**Comment by lurch** [comment]
> I don't know why these are still separate pages.

```
$ diff -r usage/gpio/ usage/gpio-plus-and-raspi2/
Only in usage/gpio/images: a-and-b-gpio-numbers.png
Only in usage/gpio/images: a-and-b-physical-pin-numbers.png
Only in usage/gpio-plus-and-raspi2/images: gpio-led-pi2.png
Only in usage/gpio-plus-and-raspi2/images: gpio-numbers-pi2.png
Only in usage/gpio/images: gpio-pins.jpg
Only in usage/gpio-plus-and-raspi2/images: gpio-pins-pi2.jpg
Only in usage/gpio-plus-and-raspi2/images: physical-pin-numbers.png
diff -r usage/gpio/LICENCE.md usage/gpio-plus-and-raspi2/LICENCE.md
9c9
< Based on a work at https://github.com/raspberrypi/documentation/tree/master/usage/gpio
---
> Based on a work at https://github.com/raspberrypi/documentation/tree/master/usage/gpio-plus-and-raspi2
11a12,13
> 
> GPIO pins photo based on [Raspberry Pi 2 Model B v1.1 top new (bg cut out)](https://commons.wikimedia.org/wiki/File:Raspberry_Pi_2_Model_B_v1.1_top_new_%28bg_cut_out%29.jpg) by Multicherry. Licensed under CC BY-SA 4.0 via Wikimedia Commons
diff -r usage/gpio/README.md usage/gpio-plus-and-raspi2/README.md
1c1
< # GPIO: Raspberry Pi Models A and B
---
> # GPIO: Models A+, B+, Raspberry Pi 2 B and Raspberry Pi 3 B
5c5
< One powerful feature of the Raspberry Pi is the row of GPIO (general purpose input/output) pins along the edge of the board, next to the yellow video out socket.
---
> One powerful feature of the Raspberry Pi is the row of GPIO (general purpose input/output) pins along the top edge of the board.
7c7
< ![GPIO pins](images/gpio-pins.jpg)
---
> ![GPIO pins](images/gpio-pins-pi2.jpg)
9c9
< These pins are a physical interface between the Pi and the outside world. At the simplest level, you can think of them as switches that you can turn on or off (input) or that the Pi can turn on or off (output). Seventeen of the 26 pins are GPIO pins; the others are power or ground pins.
---
> These pins are a physical interface between the Pi and the outside world. At the simplest level, you can think of them as switches that you can turn on or off (input) or that the Pi can turn on or off (output). Of the 40 pins, 26 are GPIO pins and the others are power or ground pins (plus two ID EEPROM pins which you should not play with unless you know your stuff!)
11c11,13
< ![GPIO layout](images/a-and-b-gpio-numbers.png)
---
> ![GPIO layout](images/gpio-numbers-pi2.png)
> 
> Note that the numbering of the GPIO pins is rather weird. *Appendix 1: A note on pin numbering*  below explains why.
33c35
< ![GPIO wth LED](images/gpio-led.png)
---
> ![GPIO wth LED](images/gpio-led-pi2.png)
43c45
< If you'd like to have a go at using the GPIO as an input then have a look at our [burping jelly baby](https://www.raspberrypi.org/learning/burping-jelly-baby/) and [quick reaction game](http://www.raspberrypi.org/learning/quick-reaction-game/) tutorials for Python, or a [reaction game](http://www.raspberrypi.org/learning/reaction-game/) for Scratch.
---
> If you'd like to have a go at using the GPIO as an input then have a look at our [burping jelly baby](http://www.raspberrypi.org/learning/burping-jelly-baby/) and [quick reaction game](http://www.raspberrypi.org/learning/quick-reaction-game/) tutorials for Python, or a [reaction game](http://www.raspberrypi.org/learning/reaction-game/) for Scratch.
79c81
< ![GPIO layout](images/a-and-b-physical-pin-numbers.png)
---
> ![GPIO layout](images/physical-pin-numbers.png)
```

Yeah, looks like it shouldn't be too hard to merge them together.

**Comment by Granjow** [comment]
That would be pretty! Are you already going to do it? Otherwise I might have time tomorrow.

**Comment by lurch** [comment]
I'm too busy myself, feel free...

**Pull request merged**
