### PR TITLE
Update config-txt.md

### PR DESCRIPTION
**Pull request by fredericofs**
Added overscan scale and cec name settings info

### CODE REVIEW

**Comment by bennuttall** [comment]
@XECDesign is this correct?

**Comment by lurch** [comment]
AFAICT there are lots of additional `config.txt` settings that get added (dunno if they ever get removed too?) with various different [firmware](https://github.com/raspberrypi/firmware) releases of `start.elf`, and unfortunately the `configuration/config-txt.md` documentation rarely gets updated to match.
I believe some of the extra settings are 'debug' stuff that doesn't need documenting (e.g. some of the stuff @popcornmix does for fixes with video playback), but there are probably other options that should be documented (with the `ignore_lcd` from https://www.raspberrypi.org/documentation/hardware/display/README.md being just one example picked at random).

And on a side-note I guess the "OVERCLOCKING OPTIONS" in the `config.txt` documentation need updating to cover the different default frequencies used on the Pi2 and PiZero?

**Comment by XECDesign** [comment]
The information seems accurate, but the formatting it's quite right.The first option should probably be a level down. I am also not sure if it's so important that it should be so close to the top of the page.

**Comment by Ruffio** [comment]
@lurch @XECDesign what does it take for this PR to be merged?

**Comment by JamesH65** [comment]
Technically happy for this to be merged, will forward to comms for copy editing/format fixing.

**Pull request merged**
