### PR TITLE
Update users.md

### PR DESCRIPTION
**Pull request by Milliways2**
Simplify adding a user to sudoers

### CODE REVIEW

**Comment by JamesH65** [comment]
@spl237 @XECDesign I'm not an expert here, any comments?

**Comment by XECDesign** [comment]
Makes sense, but it would be slightly different behaviour.

The proposed way would ask the user to enter their password. No strong opinions on whether that's preferred or not.

**Comment by bennuttall** [comment]
Been thinking about this. I think the purpose of this bit is to give another user the same rights we give the pi user by default, i.e. passwordless sudo. This gives them sudo, but not passwordless.

I would suggest adding this version, as it's simpler, rather than replacing what we have, and just add a note to say this would not make it passwordless.

**Comment by Milliways2** [comment]
I note the comments about passwordless, but on Buster the contents are:-

```
root	ALL=(ALL:ALL) ALL
# Allow members of group sudo to execute any command
%sudo	ALL=(ALL:ALL) ALL

```

There is no mention of NOPASSWD for user pi

**Comment by JamesH65** [comment]
@bennuttall Thoughts?

**Comment by bennuttall** [comment]
Oh that must just be the way I do it myself on Ubuntu. @XECDesign how is the pi user made passwordless in Raspbian?

**Comment by XECDesign** [comment]
sys-mods puts this in `/etc/sudoers.d/010_pi-nopasswd`:

```
pi ALL=(ALL) NOPASSWD: ALL
```

**Comment by MichaIng** [comment]
Jep, I suggest as preferred way as well to create a separate config file and not touch `/etc/sudoers` at all:
```
echo 'bob ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/010_bob-nopasswd
```
This has several advantages, easy reverting and reviewing of custom additions, no risk to accidentally break basic sudo permissions, allow APT to silently update `/etc/sudoers`, if defaults change, and it is consistent with what sys-mods does.

The current state of the PR uses `adduser`, which is okay but it is quite a high level tool, which might not always be available (compared to `useradd` and `echo`). At least this should generally kept in mind for docs, to not have users reporting "command not found". `echo` is core and shell internal, thus safe to be available and as above provides as well a one-liner solution.
_____________
I would also keep it simple and only cover the above to give the new user same permissions as default `pi` has, like @bennuttall suggested. IMO it should be not scope here to go into sudo/sudoers details with and without password. And as the one-liner above is as simple as `adduser`, it can be a replacement then, to keep the same result as before this PR and being simple to cover the intention of this PR.

**Comment by lurch** [comment]
Replying specifically to:

> which is okay but it is quite a high level tool, which might not always be available (compared to useradd and echo)

The documentation in this repo only supports (the latest version of) Raspbian, not every possible Linux distro, so as long as the commands are available in Raspbian Buster Lite it doesn't matter.

**Comment by MichaIng** [comment]
@lurch 
Okay make sense indeed. No argument then, but still not bad to keep/have docs as compatible as possible, using low level tools/methods, where possible.

**Comment by andrum99** [comment]
adduser is the preferred tool on Debian, which is the recommended OS on the Raspberry Pi. It is also easier to use than useradd. I think the idea of a separate file for a single sudoers user is a good idea, especially as it replicates how the folks at Pi Towers have done it for the pi user.

**Comment by MichaIng** [comment]
> adduser is the preferred tool on Debian

It is more an end user oriented tool, that includes some steps that one might expect when creating a user, such as home dir is automatically created and some other things. However if you know what you are doing, `useradd` can do exactly the same. And one that writes a doc, should know how to use it correctly and give the right command :wink:. Actually I like that it does not do so much things automatically. E.g. some program run user, usually does not require any home dir or login shell, mail and such things.

**Comment by andrum99** [comment]
The Debian man page for useradd directs users to use adduser instead. I think it is bery much preferable to direct noobs to the platform's recommended tool, rather than one's preferred utility.

**Comment by MichaIng** [comment]
> preferable to direct noobs to the platform's recommended tool

That is an argument indeed, so inexperienced users get known with the easier/end user oriented tool.

**Comment by JamesH65** [comment]
With regard to documentation we should always err on the side of inexperienced users.

**Comment by JamesH65** [comment]
So, is this the correct change to make here? I'll merge straight away if so (no need to copy edit).

**Comment by andrum99** [comment]
> So, is this the correct change to make here? I'll merge straight away if so (no need to copy edit).

No idea. I didn't even know adduser could do that. Every day's a school day.

**Comment by MichaIng** [comment]
@JamesH65 
Ah, I lost track, it is still about adding a user to sudoers list, and not about creating new users. In this case I still vote for:
```
echo 'bob ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/010_bob-nopasswd
```
It is the cleanest and most compatible method. We have no control which file is changed by adduser in this case and I strongly vote for adding it via additional file (as also pi-gen does it with the "pi" user). adduser AFAIK adds it to /etc/sudoers directly, which I would always leave untouched for above mentioned reasons.

**Comment by andrum99** [comment]
If adduser is doing it then it will be safe. This is actually safer than using a shell one-liner, since the user could completely mess things up if they mistyped that.

**Comment by MichaIng** [comment]
@andrum99 
Copy & paste... And since things are written to a new file, nothing can be really messed up without being easily revertable. However I see the arguments but made my point. Now its up to you guys and choose which wights more. Finally both works well, so either way is okay.

**Comment by andrum99** [comment]
> since things are written to a new file, nothing can be really messed up without being easily revertable

Not if the user ends up messing up the new file in such a way that nobody can sudo. The fact that it is in a separate file is largely irrelevant in that case.

**Comment by andrum99** [comment]
I've tried this on my Pi 4 with a new test user, and what adduser does when called like this:

> sudo adduser newusername sudo

is to add 'newusername' to the group sudo. It does not go anywhere near the file etc/sudoers, nor does it dump anything in /etc/sudoers.d. What it does do is add the new user to the additional secondary group 'sudo', by adding it onto the end of the existing entry for the 'sudo' group within the file '/etc/group'. As stated above, the new user will be prompted for their password when they try to sudo. This differs from the behaviour of the 'pi' user, since that user will not be prompted for their password.

The file /etc/sudoers.d/010_pi-nopasswd exists to set up the 'pi' user so that they will not be prompted for their password when they run sudo. This is an additional grant beyond what the 'pi' user already has as a member of the 'sudo' group.

This page of the documentation also does not mention the need to add any new user to the various additional groups in order for various things to work correctly on the Pi.

**Comment by Milliways2** [comment]
This thread seems to have developed a life of its own!

I originally proposed that, rather than suggesting a potentially dangerous edit to sudoers, users should be encouraged to add **group sudo**. This is what I do on my Linux systems.

Subsequent discussion was about passwordless sudo. While I am unconvinced that this is necessary, the method should suggest  adding a etc/sudoers.d/010_XXX-nopasswd file (with the comment that this is only needed for **passwordless sudo**).

**Comment by MichaIng** [comment]
> Subsequent discussion was about passwordless sudo.

The initial docs were about passwordless sudo. Reason is that it is about replacing "pi" with a custom user. And "pi" has passwordless sudo as well, so especially inexperienced users will expect the new user to behave the same.

> Incidentally, rather than suggesting cryptic echo commands just list the file contents. I always use the (simpler) `sudoedit /etc/sudoers.d/010_bob-nopasswd`

What is the difference between copying an echo with "cryptic" content and running your command + copying cryptic content into the open file? It is just more effort for end users (two copy/pasts + save + quit) and fails the initial intention of this PR.

**Comment by Milliways2** [comment]
> > Subsequent discussion was about passwordless sudo.
> 
> The initial docs were about passwordless sudo. Reason is that it is about replacing "pi" with a custom user. And "pi" has passwordless sudo as well, so especially inexperienced users will expect the new user to behave the same.

My original suggestion (almost 2 months ago) was simply to add the following as a simpler (and safer) option!
```
To add a new user to sudoers add the user to group sudo
`sudo adduser bob sudo`

```

**Comment by andrum99** [comment]
I think @Milliways2's original suggestion is the way to go, but the PR should be amended to add a note that the newly added user will be prompted for their password when they sudo, and mention this is to improve security.

**Comment by MichaIng** [comment]
Reasonable alternative. However since the "pi" user comes without sudo password, it is a bid inconsistent to evaluate security vs comfort different for a new user? Note that the password that one needs to enter is the one from the originating user, not from the root user (if even existent). So if an attacker already has access to the originating user, he most likely has this password anyway, thus security benefit is marginal, only present if someone manages to hijack an open session.

However finally all this can be easily found out by asking any search machine and every suggestion made here is better, safer and easier to apply then the method that is currently provided by the docs.
@JamesH65 as you can see, there is no "correct change to make", but it's a question about your priorities between security, consistency, comfort, simple/understandable command usage etc. You know how it is done for the "pi" user, and pros/cons for alternatives are discussed here (probably too much 😉), so one with merge permissions finally has to decide.

**Comment by lurch** [comment]
IMVHO (for what it's worth) I think we should go with the original suggestion in this PR, and as @andrum99 mentioned "add a note that the newly added user will be prompted for their password when they sudo", but I also agree with @MichaIng that we should _also_ provide instructions for e.g. `echo 'bob ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/010_bob-nopasswd` if users _additionally_ want to retain the passwordless-sudo behaviour that the `pi` user has. As long as that's not too many different options to confuse newbie users :confused:

**Comment by XECDesign** [comment]
I was previously on the "leave it as it is, since it preserves the existing behaviour of the pi user" camp, but given that these instructions are to improve security, I'm with @lurch on this one. The PR improves security and makes the instructions simpler. Just adding a note on how to get the old behaviour back would make it even better.

**Comment by andrum99** [comment]
The correct incantation for @MichaIng's command, assuming the user is not root, is:

`echo 'bob ALL=(ALL) NO PASSWD: ALL' | sudo tee -a /etc/sudoers.d/010_bob-nopasswd`

**Comment by andrum99** [comment]
Since I don't have write permissions to either repo here, I've created a PR myself on my own repo with what I believe is the consensus approach - see #1269.

**Comment by JamesH65** [comment]
Superceded by #1269

**Pull request closed without merging**
