### PR TITLE
Add Pi Zero to specs page

### PR DESCRIPTION
**Pull request by JamesNewton**

### CODE REVIEW

**Comment by lurch** [comment]
AFAIK there aren't actually any links to the specs page that you've edited?
See https://github.com/raspberrypi/documentation/issues/182#issuecomment-83872783 for background info.

**Comment by JamesNewton** [comment]
Goggle found it. And it's the best comparison table I've seen after about 10 min of searching except for lacking the Zero and pi2 . Sorry to see it go unused.... where else can you find guidance on which to buy / use?

**Comment by lurch** [comment]
I guess 2a46bba69e3e0171f32906867a5566eff742ad91 means that this PR will need to be closed?

**Comment by JamesH65** [comment]
Sorry to leave a comment on a closed page, but this has just come up on the forum - the products page only has current models, there is no information on older models that people may come across. Since these may come up for sale at various points, people may wish to know what they have got. This is where a table might be useful, as it could flag whether it's a current model or not, as well as giving a quick comparison between models.

**Comment by JamesNewton** [comment]
Honestly, this also bugs me... As JamesH65 notes (good name) there is no other place that lists all the models side by side. I would really suggest retaining this information somewhere.

**Pull request closed without merging**
