### PR TITLE
Delete the FAQ

### PR DESCRIPTION
**Pull request by aallan**
We'll salvage some of the content from the FAQ for use elsewhere, but the FAQ is going away post-#1911.

### CODE REVIEW

**Comment by JamesH65** [comment]
Why is the FAQ going away? Always seemed to have useful information in it.

**Comment by aallan** [comment]
> Why is the FAQ going away? Always seemed to have useful information in it.

Some of the information in it will get reused elsewhere in the documentation.

**Comment by lurch** [comment]
Will the FAQ link in the website-footer still redirect to somewhere appropriate?

**Comment by aallan** [comment]
I might leave an abbreviated FAQ in place for that. Or just get a ticket to get the link removed.

**Comment by aallan** [comment]
Superceeded by internal tooling.

**Comment by JamesH65** [comment]
One section that will definitely need to be moved somewhere new is the power consumption stuff - I don't think that is anywhere else in the docs, and it's a very common question.

**Comment by aallan** [comment]
> One section that will definitely need to be moved somewhere new is the power consumption stuff - I don't think that is anywhere else in the docs, and it's a very common question.

Thanks! I'd spotted that one too. I've got a post-it note of sections I'm going to snag stuck to my monitor. If you think of any others that aren't duplicated elsewhere let me know.

**Comment by lurch** [comment]
image

**Pull request closed without merging**
