### PR TITLE
Resources for Linux Kernel

### PR DESCRIPTION
**Pull request by weg2g**
Adding more resource for Linux Kernel

### CODE REVIEW

**Comment by JamesH65** [comment]
As with comment on you rother PR, on the whole we don't like links offsite for things like this. I'll discuss with the comms team.

**Comment by lurch** [comment]
I guess there's also the level-of-detail to consider - IMHO stuff about "Bottom Half Handling Data Structures" certainly seems _well_ beyond the scope of the beginner-oriented nature of the Raspberry Pi Documentation? :man_shrugging:

**Comment by JamesH65** [comment]
I hadn't looked at the content, but that is a fair point.

**Comment by JamesH65** [comment]
Not happy with simply adding links to random outside sites over which we have zero control, so rejecting this PR.

**Pull request closed without merging**
