### PR TITLE
Update Mac image installation instructions

### PR DESCRIPTION
**Pull request by bshaw**
- Provides additional commands required when using the command line and provides some output examples.
- Cleanup some markdown syntax

### CODE REVIEW

**Comment by helenlynn** [comment]
@JamesH65 the table in lines 15-37 appears to me to be misaligned, unless the current alignment holds some meaning with which I am not familiar. Has it? If not, I will line up columns under headings.

**Comment by JamesH65** [comment]
I think the format has gone a bit haywire. Not familiar with Mac's, but I thin lining up is probably the way to go.

**Comment by helenlynn** [comment]
Now aligned and ready for tech check etc.

**Comment by JamesH65** [comment]
rebased and merged.

**Pull request merged**
