### PR TITLE
Added link for 2837 

### PR DESCRIPTION
**Pull request by infoseek1**
Thanks @lurch  for catching the error.

### CODE REVIEW

**Comment by Ruffio** [comment]
@LornaLynch can this be merged? It just adds updated info about Pi3

**Comment by LornaLynch** [comment]
@Ruffio I'm afraid I can't merge this as there's a conflict. I can duplicate the required text manually and close the PR if that is OK?

**Comment by Ruffio** [comment]
@infoseek1 what do you say? will you fix this PR (and get credit when it is merged) or should @LornaLynch do it?

**Comment by LornaLynch** [comment]
Sorry, I may have jumped in there. I've created the requisite documents/made the edits and referenced this PR. Sorry if I stepped on your toes, @infoseek1

**Comment by lurch** [comment]
@LornaLynch You need to rename [bcm2387](https://github.com/raspberrypi/documentation/tree/master/hardware/raspberrypi/bcm2387) to `bcm2837`. The link in [README.md](https://github.com/raspberrypi/documentation/blob/master/hardware/raspberrypi/README.md) is correct, it's just the directory that's been mis-named.

**Comment by LornaLynch** [comment]
Thanks @lurch, will do.

**Pull request closed without merging**
