### PR TITLE
Update access-point.md

### PR DESCRIPTION
**Pull request by moonlitknight**
Add warning that brctl addif command will temporarily disable the eth0 interface.

### CODE REVIEW

**Comment by JamesH65** [comment]
Whilst probably a good idea, I don't like the phrasing. Rejig the USB keyboard part and I'll take another look.

**Comment by JamesH65** [comment]
@epoch1970 Sorry to keep pinging you on these! I'm having a clear out and there was a backlog of access point PR's! Is this needed now?

**Comment by epoch1970** [comment]
Pings are a good sign :)
Poor brctl is gone, gone, gone by now.
You can close that one too.

**Comment by JamesH65** [comment]
No longer requried.

**Pull request closed without merging**
