### PR TITLE
raspbian/applications/vcgencmd.md: various minor fixups

### PR DESCRIPTION
**Pull request by andrum99**

### CODE REVIEW

**Comment by aallan** [comment]
I'd encourage you to wrap this PR up in the next week or so as we're in the process of transitioning the documentation from the current Markdown-based source format to Asciidoc. At some point soon — probably around the end of June, beginning of July — we will freeze the current documentation repo. After that time contributions and PRs based on the Markdown source will not be accepted, and any PRs that are still open will be closed.

See #1911 for full details.

**Comment by andrum99** [comment]
This one is awaiting review from someone at Pi Towers.

**Comment by aallan** [comment]
@JamesH65 @lurch Any idea who should look at this?

**Comment by aallan** [comment]
Marked for 7 day close due to merge conflicts, these need to be resolved before its ready to merge.

**Comment by andrum99** [comment]
> Marked for 7 day close due to merge conflicts, these need to be resolved before its ready to merge.

Conflicts resolved 👍

**Comment by aallan** [comment]
> Conflicts resolved 👍

Excellent! :) 

Waiting for internal comment on the content only then. Otherwise ready to merge.

**Pull request merged**
