### PR TITLE
Add missing step to edit /etc/default/hostapd to access-point-routed.md

### LINKED ISSUE #1646: Wireless Access Point creation document is missing the DAEMON_CONF edit step
https://www.raspberrypi.org/documentation/configuration/wireless/access-point-routed.md

The official link to generate Acess Point on RPI is missing the step where the configuration file of HOSTAPD needs to be modified

Path to File: /etc/default/hostapd
Edit Required: 
Change #DAEMON_CONF= to DAEMON_CONF="/etc/hostapd/hostapd.conf"

Rpi will fail to generate a network, In case of RPI zero, any access to board over Wi-Fi will be lost in case this step is not performed.

### PR DESCRIPTION
**Pull request by ajf58**
Fixes #1646.

### CODE REVIEW

**Comment by JamesH65** [comment]
I have no idea what this does, but it looks sane to me. @lurch @andrum99 @XECDesign Any ideas?

**Comment by XECDesign** [comment]
From the  systemd service file (`/lib/systemd/system/hostapd.service`):
```
[Unit]
Description=Advanced IEEE 802.11 AP and IEEE 802.1X/WPA/WPA2/EAP Authenticator
After=network.target

[Service]
Type=forking
PIDFile=/run/hostapd.pid
Restart=on-failure
RestartSec=2
Environment=DAEMON_CONF=/etc/hostapd/hostapd.conf
EnvironmentFile=-/etc/default/hostapd
ExecStart=/usr/sbin/hostapd -B -P /run/hostapd.pid -B $DAEMON_OPTS ${DAEMON_CONF}

[Install]
WantedBy=multi-user.target
```
That already sets `DAEMON_CONF=/etc/hostapd/hostapd.conf` before `/etc/default/hostapd` is parsed.

**Comment by andrum99** [comment]
> From the systemd service file (`/lib/systemd/system/hostapd.service`):
> 
> snip
>
> That already sets `DAEMON_CONF=/etc/hostapd/hostapd.conf` before `/etc/default/hostapd` is parsed.

While I've never used `hostapd`, I can confirm that this is the case. This PR is therefore not required.

**Comment by ajf58** [comment]
You're right, @andrum99, this isn't required with the current version of Raspberry Pi OS. I was certain this was required previously, and my experience matched others. Perhaps the `systemd` service unit that is installed with the package has been updated since I looked at this last(?), but my knowledge of how packages are built is limited.

Anyway, thanks for spotting my mistake. I'll close this PR, and #1646 can be closed as well.

**Pull request closed without merging**
