### PR TITLE
Update frequency-management.adoc

### PR DESCRIPTION
**Pull request by andrum99**
Grammar fixups

### CODE REVIEW

**Comment by lurch** [comment]
I'm not sure if the de-hyphenation is appropriate here? :shrug:

**Comment by andrum99** [comment]
> I'm not sure if the de-hyphenation is appropriate here? 🤷

Hyphens are only meant to be used where:

- the words being hyphenated form a compound adjective, which is not the case here
- the words being hyphenated would otherwise be confused with another word which has a different meaning, e.g. co-op versus coop

There are some exceptions, but those don't apply in this case.  See https://blog.oup.com/2018/08/linguistics-where-to-put-hyphens/

**Comment by aallan** [comment]
undervoltage should be all one word, rather than a compound.

**Comment by andrum99** [comment]
> undervoltage should be all one word, rather than a compound.

I use OUP's free online service lexico.com to check spelling, and it doesn't have undervoltage as a word, although it does have overvoltage. This implies `under voltage` is correct in this case, where it is used as a compound noun.

**Comment by aallan** [comment]
> I use OUP's free online service lexico.com to check spelling, and it doesn't have undervoltage as a word, although it does have overvoltage. This implies `under voltage` is correct in this case, where it is used as a compound noun.

It's in Merriam Webster as a word? https://www.merriam-webster.com/dictionary/undervoltage

**Comment by andrum99** [comment]
> > I use OUP's free online service lexico.com to check spelling, and it doesn't have undervoltage as a word, although it does have overvoltage. This implies `under voltage` is correct in this case, where it is used as a compound noun.
> 
> It's in Merriam Webster as a word? https://www.merriam-webster.com/dictionary/undervoltage

Merriam Webster is an American dictionary.

**Review by aallan — APPROVED** [review]
LGTM

**Pull request merged**
