### PR TITLE
Update revision-codes.adoc for Pi5

### PR DESCRIPTION
**Pull request by JamesH65**

### CODE REVIEW

**Comment by lurch** [comment]
Hmm, both entries are listed as 8GB? Was one of them supposed to be 4GB?

**Comment by JamesH65** [comment]
Doh, C&P error. First one is 4GB.

**Comment by aallan** [comment]
I'll just go in and edit it on branch @JamesH65 no need to do another PR.

**Comment by aallan** [comment]
Fixed in d9c0470

**Pull request merged**
