### PR TITLE
Update bcm2711_bootloader_config.md

### PR DESCRIPTION
**Pull request by timg236**
Updated the rpi-update branch instructions. 
The firmware updates are now in the mainline firmware branch and will available via the rpi-update master branch

@popcornmix

### CODE REVIEW

**Comment by JamesH65** [comment]
LGTM, I presume this can be merged straight away?

**Comment by popcornmix** [comment]
Looks fine. Only valid after next rpi-update push (later today).

**Comment by timg236** [comment]
Let's leave it until the binaries are available and I'll add a line to give the hash/version number.

**Comment by lurch** [comment]
Might be worth linking this to James' new rpi-update page, so people are aware of the rpi-update caveats?
https://github.com/raspberrypi/documentation/blob/master/raspbian/applications/rpi-update.md

**Comment by lurch** [comment]
"it might scare people away :)" - probably better to err on the side of caution, than to risk people getting angry with RPi when they lose all their data because they didn't make a backup first :wink:

**Comment by timg236** [comment]
Please can someone merge this now?

**Pull request merged**
