### PR TITLE
Adding copy-to-clipboard functionality

### PR DESCRIPTION
**Pull request by nelliemckesson**
Here's some initial code to add the copy-to-clipboard functionality. I'm inserting the copy buttons as part of the jekyll build process, to reduce the JS load a little bit. @lurch can you add `_plugins` to the dirs that get copied to the build folder (for reals this time)?

@aallan @jackbenwillis take a look -- could use some design guidance... Also if you want to provide a nicer clipboard svg icon, that would be cool!

Screen Shot 2021-08-26 at 8 56 15 PM

### CODE REVIEW

**Comment by lurch** [comment]
> @lurch can you add _plugins to the dirs that get copied to the build folder (for reals this time)?

Done :+1: 

This looks nice and seems to work okay in the limited bit of testing I've just done, but do we want a "Copy to clipboard" hover-text / tooltip-text on the clipboard icon?

**Comment by aallan** [comment]
> … do we want a "Copy to clipboard" hover-text / tooltip-text on the clipboard icon?

I think we might want that?

**Comment by nelliemckesson** [comment]
@lurch yeah, I rebased onto develop and things got weird :/ Not totally sure what went wrong or how to fix. Might just close this one and start a new branch...

**Comment by nelliemckesson** [comment]
See #2145 for mergeable code

**Review by gk351 — COMMENTED** [review]
> - [ ] **~~````
_**

**_
````~~**

**Review by gk351 — COMMENTED** [review]
@phsilva

**Review by gk351 — COMMENTED** [review]
堅持

**Pull request closed without merging**
