### PR TITLE
configuration/config-txt/video.md: clarify hdmi_blanking option

### PR DESCRIPTION
**Pull request by andrum99**
The wording was not ideal. I would propose running this through copy edit to apply more polish.

Also, is there anything specific to the Pi 4 that we need to mention here?

### CODE REVIEW

**Comment by generaleramon** [comment]
If i understand correctly the `hdmi_blanking` option is not working as it should on the Pi 4
https://github.com/raspberrypi/linux/issues/3050
https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=244796#p1504694

**Comment by andrum99** [comment]
> If i understand correctly the `hdmi_blanking` option is not working as it should on the Pi 4
> [raspberrypi/linux#3050](https://github.com/raspberrypi/linux/issues/3050)
> https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=244796#p1504694

That bug has someone saying hdmi_blanking is not yet implemented on Pi 4. Is this true, and if so, is that something we should mention in the docs?

**Comment by mehrvarz** [comment]
> That bug has someone saying hdmi_blanking is not yet implemented on Pi 4. Is this true, and if so, is that something we should mention in the docs?

This not a PI4 specific bug. It's also not really a hdmi issues, as I point out here: https://github.com/raspberrypi/linux/issues/3050#issuecomment-514609300

**Comment by andrum99** [comment]
> > That bug has someone saying hdmi_blanking is not yet implemented on Pi 4. Is this true, and if so, is that something we should mention in the docs?
> 
> This not a PI4 specific bug. It's also not really a hdmi issues, as I point out here: [raspberrypi/linux#3050 (comment)](https://github.com/raspberrypi/linux/issues/3050#issuecomment-514609300)

I was not referring to the bug, but to one of the comments in it - @timg stated that hdmi_blanking is not yet implemented on Pi 4.

**Comment by andrum99** [comment]
@JamesH65 Can you possibly confirm with timg (who I cannot contact via github) if hdmi_blanking is implemented yet on the Pi 4, and also comment on whether I should mention that in this page of the docs?

**Comment by JamesH65** [comment]
AFAIK, it is NOT yet implemented. Probably should be mentioned.

**Comment by andrum99** [comment]
Just had a user on the forums wondering why hdmi_blanking=1 wasn't working on their Pi 4, so have added mention that this is not implemented yet.

**Comment by JamesH65** [comment]
thanks.

**Pull request merged**
