### PR TITLE
Clarify J2 for CM4 vs J4 for CM1/CM3

### PR DESCRIPTION
**Pull request by gojimmypi**

### CODE REVIEW

**Comment by lurch** [comment]
ping @dp111

**Comment by dp111** [comment]
I think this pull request ( #2181) tidies up the issue and makes things a little more logical ?

**Comment by JeffersonKidd** [comment]
You guys have got to take me off this list.  I don't know how many more ways to unsubscribe.

________________________________

**Comment by lurch** [comment]
@JeffersonKidd That's something you need to do yourself, see https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/managing-subscriptions-for-activity-on-github/managing-your-subscriptions

**Comment by aallan** [comment]
@gojimmypi Does #2181 solve your issue?

**Comment by aallan** [comment]
Closing due to lack of response.

**Pull request closed without merging**
