### PR TITLE
Clarify country code in WiFi doc

### PR DESCRIPTION
**Pull request by bman46**

### CODE REVIEW

**Comment by lurch** [comment]
Not sure if this is necessary, as it already says `See [Wikipedia](https://en.wikipedia.org/wiki/ISO_3166-1) for a list of country codes.` just underneath?

**Comment by bman46** [comment]
I found it kind of confusing on which one to use (alpha 2, alpha 3, or numeric). Plus, it will help out with the people who just want to copy and paste and not read anything.

**Comment by JamesH65** [comment]
I think this would be OK, if the link below also stated the ISO number. The text used to match in both places, it should continue to match, so if one changes the other does.

**Comment by bman46** [comment]
> I think this would be OK, if the link below also stated the ISO number. The text used to match in both places, it should continue to match, so if one changes the other does.

Good point, added that in.

**Comment by JamesH65** [comment]
Thanks

**Comment by bman46** [comment]
No problem.

**Pull request merged**
