### PR TITLE
Add oflag=sync to the dd command line

### PR DESCRIPTION
**Pull request by fwyzard**
Using only `status=progress conv=fsync` will result in a seemingly very fast copy, much faster than the write speed of the SD card, followed by a long delay as the data is actually written to the SD card.  
Using `status=progress conv=fsync oflag=sync` will show a slower progress, roughly matching the write speed of the SD card, but once it is done the command will complete immediately.  

I think the second approach is more intuitive and less likely to cause users to think the copy is hung.

### CODE REVIEW

**Comment by JamesH65** [comment]
Hmm, nice idea. Once I've confirmed it's all OK will merge.

**Comment by fwyzard** [comment]
In fact, I suspect `conv=fsync` can be dropped altogether if using `oflag=sync`,

And by the way, `dd(1)` suggests also `oflag=direct`, but I haven't tried it.

**Comment by lurch** [comment]
@fwyzard As you've noted, this is (apparently) only an issue when using the `status=progress` option in newer versions of `dd`. So perhaps this `oflag=sync` should only be used with the last `dd` command, and not with all three `dd` commands as this PR is currently doing?

(from what you're describing, it sounds like the `conv=fsync` does one big file-sync at the end, but the `oflag=sync` does lots of smaller file-syncs as the file is being written? Note that I've not tested any of these options myself)

**Comment by fwyzard** [comment]
OK.

Though it may be harder to explain why one uses different flags when showing the progress.

**Comment by aallan** [comment]
In light of #1911 and the lack of progress in a long while I'm marking this PR as 7 day closure.

**Comment by aallan** [comment]
No one picked this up inside the 7 day closure window. So closing due to #1911.

**Pull request closed without merging**
