### PR TITLE
Mac VNC client needs exact port

### PR DESCRIPTION
**Pull request by antoinesd**
Add another problem resolution by using effective vnc port for Mac OS built-in vnc client (solved non working connexion for me)

### CODE REVIEW

**Comment by lurch** [comment]
Duplicate of #317 / #318 ?

**Comment by antoinesd** [comment]
yes duplicate of #317 / #318. What's the problem with their merging @lurch?

**Comment by lurch** [comment]
I can't merge myself, as I don't have a Mac for testing. But I've obviously no idea why other people haven't merged it (I'm only a keen volunteer, not an RPF employee).

**Comment by antoinesd** [comment]
Thanks lurch. I close my PR since #318 propose the same in a more complete way ;)

**Pull request closed without merging**
