### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by teschlg**
Some fixes for the latest version

### CODE REVIEW

**Comment by XECDesign** [comment]
Why do you need to touch the lightdm service for this?

**Comment by teschlg** [comment]
If lightdm is running on :0 you can't start vnc on :0! Of course you could have lightdm on :0 and vnc on :1 but given the limited resources of the pi that does not seem a good idea?

**Comment by XECDesign** [comment]
Ah yes, makes sense. I think I would prefer to run vnc on :1 anyway and mention that lightdm can be disabled to save resources. However, this is definitely an improvement on the instructions so looks good to me as is.

Minor typo: "Since a desktop **ist** typically..."

**Comment by teschlg** [comment]
OK, I changed this to :1. See if you like it.

**Comment by XECDesign** [comment]
Looks good, thank you.

**Comment by bennuttall** [comment]
I'm not fussed about squashing commits but I'd prefer better commit messages than `Update README.md` :)

**Comment by XECDesign** [comment]
Heh yeah, good point. Noted.

**Pull request merged**
