### PR TITLE
James h65 patch 2 wireless access point instructions

### PR DESCRIPTION
**Pull request by JamesH65**
This is a new page under the wireless section for setting up access points. I've tested as it stands, could probably do with someone else doing it on a fresh install to make sure it all works.

### CODE REVIEW

**Comment by XECDesign** [comment]
Nit-picky comment that can be ignored: if we are shipping, using and supporting dhcpcd in the default install, it would make sense to use dhcpcd where possible, rather than discarding it and using the old system.

**Comment by JamesH65** [comment]
Can dhcpcd act as a server as well as a client then?

On 17 March 2017 at 18:33, XECDesign <notifications@github.com> wrote:

> Nit-picky comment that can be ignored: if we are shipping, using and
> supporting dhcpcd in the default install, it would make sense to use dhcpcd
> where possible, rather than discarding it and using the old system.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_raspberrypi_documentation_pull_587-23issuecomment-2D287436607&d=DwMFaQ&c=DpyQ_ftY536pf7wCBQXXU58xADDRY77THQzJu1OmzOo&r=w09_2ePv8G3zRjoV19Wm1Q6rI7CDlOns4PuRv2hHkek&m=PKhtsTMFNPEF4piYI03vXI5rwOcRl42HuDF4t8m6TL0&s=DCjsSNUxirRpqj8DFZenl5fv3Pzf5tAXYM3OK6nO4LU&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADqrHQcdv7fJi4OjhohGN2ioZdl5EZgbks5rmtHkgaJpZM4Mgb4v&d=DwMFaQ&c=DpyQ_ftY536pf7wCBQXXU58xADDRY77THQzJu1OmzOo&r=w09_2ePv8G3zRjoV19Wm1Q6rI7CDlOns4PuRv2hHkek&m=PKhtsTMFNPEF4piYI03vXI5rwOcRl42HuDF4t8m6TL0&s=Au0Fs1vz9vv6WPthGlNIKUgJyjJtvxUuChYhughCbN4&e=>
> .
>



-- 
James Hughes
Principal Software Engineer,
Raspberry Pi (Trading) Ltd

**Comment by XECDesign** [comment]
No, but it can be used to set up a static IP, which seems to be one of the steps.

**Comment by LornaLynch** [comment]
Copy edit done. There are a couple of changes in my latest commit which I *think* are fine, but which need a technical check. Pushing back to you @JamesH65.

**Comment by JamesH65** [comment]
Following @XECDesign comment above, I tried to use dchpcd to set a static IP address and was not able to get it to work. I don't have time to check why so I'm inclined to publish this current documentation and reply of updates later if required. Third party testing has shown the process does work as described, so its better than not having the docs in there at all. Pushing to Copy edit for one last pass, then will merge it.

**Comment by JamesH65** [comment]
@LornaLynch @AisforAstronaut This needs one last copy edit going over- I know its been done once but I have added a few lines. Should be a quick job.

**Comment by AisforAstronaut** [comment]
I'll take a look!

**Comment by AisforAstronaut** [comment]
@JamesH65 File checked. Minor changes. Pushed back for technical checking.

**Pull request merged**
