### PR TITLE
Update users.md

### PR DESCRIPTION
**Pull request by steveb1475**
adduser doesn't prompt for password, nor does it create home directory.

### CODE REVIEW

**Comment by steveb1475** [comment]
Sorry if this is incorrect, but the instructions state that you should be prompted for a password for the new user.  This doesn't happen unless you use useradd.

**Comment by waveform80** [comment]
Erm - `adduser` seems to prompt for me:

```console
pi@raspberrypi ~ $ sudo adduser foo
Adding user `foo' ...
Adding new group `foo' (1001) ...
Adding new user `foo' (1001) with group `foo' ...
Creating home directory `/home/foo' ...
Copying files from `/etc/skel' ...
Enter new UNIX password: 
Retype new UNIX password: 
passwd: password updated successfully
Changing the user information for foo
Enter the new value, or press ENTER for the default
        Full Name []: foo
        Room Number []: 
        Work Phone []: 
        Home Phone []: 
        Other []: 
Is the information correct? [Y/n] 
```

On the contrary, `useradd` (which is the lower level tool that `adduser` is built upon) is the one that doesn't prompt for a password (it creates users with blank password fields which leaves them disabled(ish)).

**Comment by steveb1475** [comment]
Check it again, sorry, typo my first post.

existing documentation:
`Enter `sudo useradd bob` and you'll be prompted for a password for the new user `bob`. Leave this blank if you don't want a password.`

My suggestion was to change it to:
`Enter `sudo adduser bob` and you'll be prompted for a password for the new user `bob`. Leave this blank if you don't want a password.`

useradd doesn't prompt for password or create home directory.

**Comment by steveb1475** [comment]
sorry, dyslexic moment I guess.

**Pull request closed without merging**
