### PR TITLE
Simplify instructions for VNC on Mac

### PR DESCRIPTION
**Pull request by teschlg**
Simpler instructions for VNC on Mac

### CODE REVIEW

**Comment by bennuttall** [comment]
@lauraclay can you please check this and merge? Thanks

**Comment by lurch** [comment]
@bennuttall Did you want to edit the name of this PR first? ;-)

**Comment by bennuttall** [comment]
Is that possible? :P

**Comment by lurch** [comment]
Yup, the "Edit" button up near the top-right of the page :)

**Comment by bennuttall** [comment]
So you can...

**Comment by bennuttall** [comment]
Thanks!

**Pull request merged**
