### PR TITLE
fix typos in GPS tags

### PR DESCRIPTION
**Pull request by electronicsguy**

### CODE REVIEW

**Comment by XECDesign** [comment]
@JamesH65 Is that right?

**Comment by lurch** [comment]
I have no idea if this is correct or not, but there's a bit more detail in #211

**Comment by JamesH65** [comment]
It looks OK to me. Straining my memory about the /100 but nothing popping out...

**Comment by XECDesign** [comment]
Thank you

**Comment by electronicsguy** [comment]
:+1:

**Pull request merged**
