### PR TITLE
Add hdmi_blanking config option

### PR DESCRIPTION
**Pull request by t3chguy**
ref: https://github.com/raspberrypi/linux/issues/487#issuecomment-132638826

### CODE REVIEW

**Comment by popcornmix** [comment]
Might be worth mentioning this can cause problems with apps that don't use framebuffer like omxplayer.

**Comment by Ruffio** [comment]
@t3chguy Will you change this PR according to @popcornmix 's comment and rebase?

**Comment by t3chguy** [comment]
Thanks @Ruffio I must've missed @popcornmix's comment, all done now;

**Comment by AisforAstronaut** [comment]
This has been corrected in a copy: #532

**Comment by JamesH65** [comment]
Closing as has been fixed in another PR.

**Pull request closed without merging**
