### PR TITLE
User security

### PR DESCRIPTION
**Pull request by thecolorjay**
Disabling the `pi` user and disabling autologin of the `pi` user.

### CODE REVIEW

**Comment by JamesH65** [comment]
@XECDesign Does this look sane to you?

**Comment by XECDesign** [comment]
Seems coherent, yes. I'd recommend using raspi-config instead since that will also handle console autologin. Otherwise this needs an extra step added to adjust the getty override as well.

**Comment by JamesH65** [comment]
@thecolorjay As @XECDesign has suggested, raspi-config is a better option for turning off auto login, so the instructions should be amended to use that instead. Otherwise, all good.

**Comment by thecolorjay** [comment]
> @thecolorjay As @XECDesign has suggested, raspi-config is a better option for turning off auto login, so the instructions should be amended to use that instead. Otherwise, all good.

That's actually not installed by default, they'd have to install it first. But, I'll point that out.

**Comment by XECDesign** [comment]
Where is `raspi-config` not installed by default?

**Comment by thecolorjay** [comment]
> Where is `raspi-config` not installed by default?

On Raspbian, it's not preinstalled.

**Comment by JamesH65** [comment]
> > Where is `raspi-config` not installed by default?
> 
> On Raspbian, it's not preinstalled.

Yes it is, and has been almost since the very first Pi.

**Comment by thecolorjay** [comment]
> > > Where is `raspi-config` not installed by default?
> > 
> > 
> > On Raspbian, it's not preinstalled.
> 
> Yes it is, and has been almost since the very first Pi.

Well I had to install it because it didn't exist, and I'm using the latest version of Raspbian. Try it yourself.

**Comment by XECDesign** [comment]
The core issue here is that the instructions are incomplete. Following them will disable lightdm autologin, but will do nothing about console autologin. Whereas using raspi-config instead will do both.

**Comment by XECDesign** [comment]
No need to try it ourselves, it's one of the first things people run and if it wasn't there, we'd be the first to notice.

**Comment by thecolorjay** [comment]
> The core issue here is that the instructions are incomplete. Following them will disable lightdm autologin, but will do nothing about console autologin. Whereas using raspi-config instead will do both.

Okay I'll just get rid of that all together

**Comment by thecolorjay** [comment]
> The core issue here is that the instructions are incomplete. Following them will disable lightdm autologin, but will do nothing about console autologin. Whereas using raspi-config instead will do both.

Okay, it's done. That good?

**Comment by thecolorjay** [comment]
I didn't mean to close the pull request, that was a mistake.

**Comment by thecolorjay** [comment]
> No need to try it ourselves, it's one of the first things people run and if it wasn't there, we'd be the first to notice.

That may be, but I'm also a user of Raspbian and it's not there for me. As I pointed out, I had to install it. Weird, but that's true.

**Comment by thecolorjay** [comment]
You know, this is a fucking waste of my time. Fuck your upper management!

**Comment by JamesH65** [comment]
I'll pass on your message. Just a FYI though, I spend a lot of time working on this documentation. It's not a waste of time.

**Comment by JamesH65** [comment]
Despite over the top comments from OP, this is worth keeping. But I don't seem to be able to reopen it. Will just copy over when I get the chance.

**Comment by thecolorjay** [comment]
> Despite over the top comments from OP, this is worth keeping. But I don't seem to be able to reopen it. Will just copy over when I get the chance.

I've already deleted the pull request, I don't see the point in trying to contribute anything when the smallest change is rejected.

**Comment by XECDesign** [comment]
It wasn't rejected.

**Comment by JamesH65** [comment]
This is documentation that is read by millions of people. It has a process to go through before it goes live - its checked for technical accuracy, checked for completeness, checked its useful enough to go in, then it's checked by copy editors to ensure its grammatically correct and adheres to our publishing standards. Then it is technically checked again to make sure copy editors haven't broken anything. Then its merged. We were still going through that process, at no point was it rejected.

**Pull request closed without merging**
