### PR TITLE
Update camera.md

### PR DESCRIPTION
**Pull request by JamesH65**
Added what we know about the colour temperature ranges  for various AWB modes.

### CODE REVIEW

**Comment by JamesH65** [comment]
Issue #358

**Comment by AisforAstronaut** [comment]
I've tweaked your corrections here, but I have also spotted that there are whole lists of settings formatted:

- off Turn off white balance calculation
- auto Automatic mode (default)
- sun Sunny mode (between 5000K and 6500K)
- cloud Cloudy mode (between 6500K and 12000K)
- shade Shade mode 

This looks like a mistake to me. Can I either remove the first word:

- Turn off white balance calculation
- Automatic mode (default)
- Sunny mode (between 5000K and 6500K)
- Cloudy mode (between 6500K and 12000K)
- Shade mode 

or add some formatting to make it clearer?

- off: Turn off white balance calculation
- auto: Automatic mode (default)
- sun: Sunny mode (between 5000K and 6500K)
- cloud: Cloudy mode (between 6500K and 12000K)
- shade: Shade mode 

Some guidance would be useful! Thank you!

**Comment by JamesH65** [comment]
You definitely need the first word, so delineating it from the rest of the sentence is the best option. I thought it used to use a tab/ruler style approach so we had the first word then a gap to vertically aligned description (ie all the description in the list lined up), not sure how to do that in markdown though. Must be a way @bennuttall may be able to help.

**Comment by AisforAstronaut** [comment]
Awesome. I'll see what I can do.

Thank you!

**Comment by AisforAstronaut** [comment]
How would you feel about putting these in a table? I have a cheat sheet for a table!

**Comment by JamesH65** [comment]
I cannot find any other way of formatting this except by using a table, which is annoying...! If anything comes to mind will let you know.

**Comment by AisforAstronaut** [comment]
@JamesH65 Shall I put the table in for now?

**Comment by JamesH65** [comment]
Yes, cannot think of an alternative.

On 6 March 2017 at 12:31, R M Churcher <notifications@github.com> wrote:

> @JamesH65
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_JamesH65&d=DwMCaQ&c=DpyQ_ftY536pf7wCBQXXU58xADDRY77THQzJu1OmzOo&r=w09_2ePv8G3zRjoV19Wm1Q6rI7CDlOns4PuRv2hHkek&m=sjnWq_C2oyFU3fCFVqrpWsZ0tjjLrCgQg9wT4U7QrzU&s=mRbyuOEtTVqkRzodF7li2RkzwQ9HZ5nFCYtL9J9kdEk&e=>
> Shall I put the table in for now?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_raspberrypi_documentation_pull_530-23issuecomment-2D284383677&d=DwMCaQ&c=DpyQ_ftY536pf7wCBQXXU58xADDRY77THQzJu1OmzOo&r=w09_2ePv8G3zRjoV19Wm1Q6rI7CDlOns4PuRv2hHkek&m=sjnWq_C2oyFU3fCFVqrpWsZ0tjjLrCgQg9wT4U7QrzU&s=f-iu99B9B7eUpal1Cp5JdlbhA3fh7UCqK74yiMk-UZ8&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADqrHTAP-5FPMugcX9g8wwR3YUhw2wCW35ks5ri-5FyTgaJpZM4MRFPA&d=DwMCaQ&c=DpyQ_ftY536pf7wCBQXXU58xADDRY77THQzJu1OmzOo&r=w09_2ePv8G3zRjoV19Wm1Q6rI7CDlOns4PuRv2hHkek&m=sjnWq_C2oyFU3fCFVqrpWsZ0tjjLrCgQg9wT4U7QrzU&s=o4bD-5-2Kn8vrgdgWXNseQv9oPSiDW0JFUDzQMXQZmQ&e=>
> .
>



-- 
James Hughes
Principal Software Engineer,
Raspberry Pi (Trading) Ltd

**Comment by AisforAstronaut** [comment]
@JamesH65 
I've tried putting a table in, but I could not get it to work. I've used colons instead, and adjusted the capitalization. Pushing back for technical checking.

**Comment by JamesH65** [comment]
The captialisation is a problem - the code doesn't do a case insensitive comparison, so capitalising the command will cause them to fail. Sorry, need to be lower case....

**Comment by AisforAstronaut** [comment]
No problem - I'll fix that.

**Comment by AisforAstronaut** [comment]
@JamesH65 Should be fixed and ready to merge. Double check that I have changed all the affected words!

**Comment by JamesH65** [comment]
Look good! Merged

**Pull request merged**
