### PR TITLE
Changed 'dist-upgrade' to 'upgrade' in two spots

### PR DESCRIPTION
**Pull request by exaudio**
There were two spots where 'dist-upgrade' was specified when the correct command was 'upgrade'.

### CODE REVIEW

**Comment by bennuttall** [comment]
This undoes an intention change by @XECDesign in e12279fce4f282cf1e17138a28c7ce831faeeb5a. Serge, can you explain your reasoning?

**Comment by XECDesign** [comment]
Sure. Dist-upgrade does what upgrade does, but also picks up dependency changes. It's all in the man page. Sometimes we make changes to dependencies, so dist-upgrade should be used.

**Comment by lurch** [comment]
This is _almost_ a "documentation repo FAQ" :wink: 
https://github.com/raspberrypi/documentation/search?q=dist-upgrade&type=Issues

**Comment by XECDesign** [comment]
Maybe `sudo apt full-ugprade` would clear up some confusion, but I'm not 100% sure it's the same as `sudo apt-get dist-upgrade`. The description in the documentation is a little different and possibly incomplete. After a few minutes of googling, I couldn't find any definitive answer whether they're equivalent commands. I think it would require a bit of testing.

**Pull request closed without merging**
