### PR TITLE
bootloader: Remove redudant date information

### PR DESCRIPTION
**Pull request by timg236**
Drop explicit references to pre-2021 bootloader releases because
there's been two default releases since then. The older releases
aren't supported because they won't work on all Pi variants.

### CODE REVIEW

**Comment by timg236** [comment]
@peterharperuk @lurch

**Comment by peterharperuk** [comment]
I approve :)

**Review by aallan — APPROVED** [review]

**Comment by aallan** [comment]
@timg236 I rebased the PR from `master` to `develop` as the default branch for the repo is now `develop`. Commits to `master` auto-build and deploy the actual documentation site. For future PRs can you make sure you're against the `develop` branch? Thanks!

**Comment by timg236** [comment]
> @timg236 I rebased the PR from `master` to `develop` as the default branch for the repo is now `develop`. Commits to `master` auto-build and deploy the actual documentation site. For future PRs can you make sure you're against the `develop` branch? Thanks!

Will do. Sorry, wasn't aware of the branch structure, I did get a bit confused by the bot error !

**Comment by aallan** [comment]
> Will do. Sorry, wasn't aware of the branch structure, I did get a bit confused by the bot error !

No worries! Something we added when we moved from Markdown to Asciidoc. 

The default branch of the repo is `develop` and we all work there. PRs to `develop` need an approval from someone (I actually can't remember the whole list of folks) to commit it on to the branch. 

You can only commit from `develop` to `master` and not some other random branch, commits to `master` can only be done by me or another repo admin, but will trigger and auto-deploy of the site.

That means any PR has to be reviewed, and should spend some time on `develop` on people's local machines before going to the production site, and there's now two steps between a PR getting committed and it breaking the site somehow. 

Arguably we should have had a `production` branch, which was the branch that auto-deploys rather than using `master`, as it's a little bit non-standard, but seems to be working pretty well.

**Pull request merged**
