### PR TITLE
Add [cm3] model filter

### PR DESCRIPTION
**Pull request by lurch**
Based on https://github.com/raspberrypi/documentation/pull/2258#issuecomment-955797301
ping @pelwell

### CODE REVIEW

**Comment by pelwell** [comment]
I misremembered - there is no `[cm3]` either, not even a `[cm]` - only `[cm4]`.

**Comment by aallan** [comment]
So the Compute Module 3+ should be under [pi3], but there is no [cm3] category?

**Comment by lurch** [comment]
PR updated.

**Review by aallan — COMMENTED** [review]
YOLO

**Review by aallan — APPROVED** [review]

**Comment by pelwell** [comment]
LGTM.

**Pull request merged**
