### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by eitanchud**
Added UpSwift.io as free remote shell access over the internet solution for RaspberryPi boards.

### CODE REVIEW

**Comment by JamesH65** [comment]
Looks like a pay for service to me (for over three devices), couldn't even get pricing without signing up, so I don't think  we will merge this.

**Comment by JamesH65** [comment]
Actually, given the other options are also pay under certain circumstances, if you can make you price list more obvious this could probably go through - because I needed to register before seeing pricing, it make it less clear to our users which to chose.

**Comment by JamesH65** [comment]
Also, please put your link at the end of the list rather than the beginning. No need to 'jump the queue', those others were here first.

**Comment by eitanchud** [comment]
Hi James, as you mentioned, the pricing isn't relevant for that case, because we provide our platform completely free and full-featured for Makers and for Prototyping. 

Regarding the link - You are completely right, I will move it to the end of the list, there was no intention to 'jump the queue'.

**Comment by JamesH65** [comment]
Merged from #1345

**Pull request closed without merging**
