### PR TITLE
chore: Included githubactions in the dependabot config

### PR DESCRIPTION
**Pull request by naveensrinivasan**
This should help with keeping the GitHub actions updated on new releases. This will also help with keeping it secure.

Dependabot helps in keeping the supply chain secure https://docs.github.com/en/code-security/dependabot

GitHub actions up to date https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by aallan** [comment]
Ping @mudge

**Review by mudge — APPROVED** [review]

**Comment by aallan** [comment]
So if @mudge says yes, this is a thing we will now do. 😄

**Comment by mudge** [comment]
@lurch I'd skim the changelogs for all major version changes (assuming that represents a breaking change as per [semantic versioning](https://semver.org)) to see if any behaviour or configuration options have changed. We can also check the build output for any warnings or errors, e.g. https://github.com/raspberrypi/documentation/runs/6270167845?check_suite_focus=true

**Comment by lurch** [comment]
Okay, so I guess it's a case of merge each PR one at a time (after carefully perusing the changelog), and carefully checking the build-logs after each, before moving on to the next one? Feels like a later-in-the-week job :wink: 
(I might write some scripts to help with downloading and comparing build-log output from before and after each merge)

**Comment by lurch** [comment]
Oooh, I just happened to stumble upon https://github.com/nektos/act which looks like it _might_ be useful for testing PRs that update the GitHub actions themselves :heart:

**Pull request merged**
