### PR TITLE
Fix page titles - again again!

### LINKED ISSUE #1977: Fix top-level index page title
Need to fix the top-level index page so the title is "Raspberry Pi Documentation" and not "Raspberry Pi Documentation - Index". See discussion in #1971. 

Screenshot 2021-08-09 at 13 08 51

### PR DESCRIPTION
**Pull request by lurch**
Third time lucky? Fixes #1977 (hopefully! :crossed_fingers: )

### CODE REVIEW

**Review by aallan — APPROVED** [review]
LGTM! Fixed! /cc @mudge @nelliemckesson

**Review by duynguyen0209 — COMMENTED** [review]
Tiot

**Comment by duynguyen0209** [comment]
Tôtts

**Comment by Mandog1120** [comment]
3ff23e9af786772fc20d75ce33d23cf8b8ad892f

**Pull request merged**
