### PR TITLE
Add CM4 revision code bits

### PR DESCRIPTION
**Pull request by MichaIng**
This is just an assumption that/question if I derived this correctly. CM4 code has been added in various places, so I guess it will be released next.

If this is wrong, would be great to know which value it will have instead, for our own model detection scripts and also `raspi-config`, I guess.

### CODE REVIEW

**Comment by JamesH65** [comment]
Sorry, won't be merging this - we don't 'preempt' documentation, and I have no idea whether the number is correct anyway. Or when CM is being released.

**Comment by MichaIng** [comment]
All fine, especially when nothing is known about this yet, but
> we don't 'preempt' documentation

Re-consider this as a general rule. It is nice to allow 3rd party software providers assure compatibility BEFORE the board is released. Even `raspi-config` will likely stay without CM4 support / wrong detection otherwise: https://github.com/RPi-Distro/raspi-config/blob/5a7f883d76627fd5b77eb82fad5655843bd9c6a8/raspi-config#L48-L51
Probably you have some internal communication channels to push a release quickly but there are many other widely used tools that regularly stay there with lowered trousers 😄.

I just remember how we needed quite a while to implement all the required changes for RPi4 surprise, not only us but regular RPi tools as well, so the first order users were having an incomplete experience the first days/weeks that could have been avoided by providing some information for developers earlier :wink:.

Just as an input about general community communication, otherwise I'm pretty sure you have good reason to handle it the way you do 👍.

**Comment by lurch** [comment]
Ummm, `raspi-config` is also maintained by Raspberry Pi engineers... :wink:

**Comment by MichaIng** [comment]
Hence:
> Probably you have some internal communication channels to push a raspi-config release quickly

But I also remember some RPi4 related changes/fixes in raspi-config being done after the release, and required documentation changes were done with much more delay, months after RPi4 release in some cases. It can be wanted to hide info about new releases as long as possible, but I wanted to throw in the negative side of this, even when its only about RPi-controlled software and docs, but especially when its about external open source developers.

**Comment by R4C3R** [comment]
According to a message from Eben Upton on May 28th, the CM4 will be released definately this year. From that moment on (may 28th), we have halted our CM3 developements and wait patiently for the CM4 to arrive.

**Comment by JamesH65** [comment]
As I am sure you are aware, we never announce products (or release dates for those things that are obviously goign to be launched at some point, such as the CM4) in advance. Any documentation change that hints at a new product, or what a possibly known about new product will do (e.g. CM4),  are therefor only released on the day of release of the product. 

Changes to documentation and code always happens after release -  there are bound to be issues found that need changes, irrespective of whether there was pre-release of information. Note that we do have alpha and beta testing where product is sent out to third parties for testing and for those third parties to get their own product working. These testers do get access to the engineering team for questions so don't need public documentation. On the whole, testers are invite only.

**Comment by JamesH65** [comment]
> According to a message from Eben Upton on May 28th, the CM4 will be released definitely this year. From that moment on (may 28th), we have halted our CM3 developements and wait patiently for the CM4 to arrive.
> 
> source:
> https://www.raspberrypi.org/blog/8gb-raspberry-pi-4-on-sale-now-at-75/
> 
> search for "coming."

AFAIK, its is still due for release sometime this year. However, CV-19 has made this year rather unusual, so there is no solid guarantee.

**Comment by MichaIng** [comment]
@JamesH65 
Request to reopen this PR 😉.

**Comment by JamesH65** [comment]
I've updated the page directly.

**Comment by MichaIng** [comment]
Oh, the CM4 ID is `14`, what happened to 12 and 13? 😄

**Comment by JamesH65** [comment]
I wondered how long it would take....look forward to the speculation on the forums!

**Pull request closed without merging**
