### PR TITLE
Add note about using 64GB SD cards with NOOBS

### PR DESCRIPTION
**Pull request by lurch**
To try and prevent users getting caught out by the SDXC / exFAT "problem".

### CODE REVIEW

**Comment by lurch** [comment]
(see also https://github.com/raspberrypilearning/software-guide/issues/13 )

**Comment by JamesH65** [comment]
Made a change to the default size of Rasbpian as well. It now requires 8GB. Read OK?

**Comment by lurch** [comment]
I wonder if "installation of NOOBS and the full version of Raspbian" should be reworded as "installation of NOOBS or the image installation of Raspbian" ?
Otherwise it might sound like it's only the _combination_ of NOOBS and Raspbian that needs 8GB ;)

And on the subject of NOOBS and SD-card sizes: there's some other page(s) which talks about the pre-installed version of NOOBS on an 8GB card - seems like most (all?) vendors are now supplying pre-installed NOOBS on 16GB cards?

**Comment by JamesH65** [comment]
No idea about NOBS, never use it. But rewording of paragraph sounds fine. Do you want to do it? I'll push to copy edit as and when.

**Comment by lurch** [comment]
Done.

**Pull request merged**
