### PR TITLE
James h65 patch 1#warning icons

### PR DESCRIPTION
**Pull request by JamesH65**
Add a new configuration page to describe the latest warning icons.

I'm not convinced this is the correct location for this, but cannot think of anywhere better.

### CODE REVIEW

**Comment by JamesH65** [comment]
@AisforAstronaut Would you mind giving this a once over, I'd like it merged soon so I can reference it from another PR.

**Comment by AisforAstronaut** [comment]
Documents checked. 

No changes to README.

Minor changes to warning-icons.md. Pushing back for technical check. Please note that I am not certain what was meant by (+=5%). I have changed it to (+/-5%): please double check.

**Comment by AisforAstronaut** [comment]
Checked! Minor changes.

**Comment by JamesH65** [comment]
+/- is what was meant - thanks! Will merge in  a mo...

**Pull request merged**
