### PR TITLE
Added information about using touchscreen with multiple monitors

### PR DESCRIPTION
**Pull request by corndog2000**
Added information about using touchscreens with multiple monitors. How to map the touchscreen to the LCD screen.

### CODE REVIEW

**Comment by corndog2000** [comment]
Actually I'm having issues after reboot. Hold off on this commit until I have added fixes.

**Comment by lurch** [comment]
Possibly related to https://github.com/raspberrypi/Raspberry-Pi-OS-64bit/issues/8 ?

**Comment by aallan** [comment]
I'd encourage you to wrap this PR up in the next week or so as we're in the process of transitioning the documentation from the current Markdown-based source format to Asciidoc. At some point soon — probably around the end of June, beginning of July — we will freeze the current documentation repo. After that time contributions and PRs based on the Markdown source will not be accepted, and any PRs that are still open will be closed.

See #1911 for full details.

**Comment by corndog2000** [comment]
I am having trouble getting the required xinput command to run on Raspberry Pi OS startup.

This command fixes the issues I talk about in my PR for future reference.

`xinput --map-to-output 'raspberrypi-ts' DSI-1`

**Pull request closed without merging**
