### PR TITLE
Update apache.md

### PR DESCRIPTION
**Pull request by tomcb1**
Updated the image of the apeche2 default page to the current updated one

### CODE REVIEW

**Comment by XECDesign** [comment]
Thanks. Instead of embedding from an external site, could you replace the image itself?

**Comment by tomcb1** [comment]
Done and done! Have not used git in quite some time so it took some research on how to replace a file.

**Comment by XECDesign** [comment]
Much appreciated

Could you also please squish the commits? `git rebase -i HEAD~3`
Then you can mark the last two commits with 'f' to squash them into your first one.

When you push back to github, you will need to use the `-f` flag.

**Comment by tomcb1** [comment]
Ok. I think thats done now. How would I mark the commits?

**Comment by XECDesign** [comment]
when you run the rebase command, it should open a text editor. The instructions are written as comments in there.

**Comment by tomcb1** [comment]
Done.

**Comment by XECDesign** [comment]
Looks good, thanks.

**Pull request merged**
