### PR TITLE
add the html rake task to help deploy this documentation on personal …

### PR DESCRIPTION
**Pull request by wangzhizhou**
…website

### CODE REVIEW

**Comment by JamesH65** [comment]
@bennuttall Ben, I have no idea what this is about - have you any thoughts?

**Comment by bennuttall** [comment]
Ah, well on the server we use a little PHP app to translate requests into content, grabbing the appropriate md file and rendering into the template. This doesn't include the template so it's not as useful to us (it would be nice if we could output html rather than rely on a PHP app, but it's not caused us any problems in the 3 years it's been running).

It might be useful to (a small subset of) contributors to be able to fire up an HTML (template-less) version, if they have the right tooling to do so. I don't see any harm in this but it's not something we really want to support. Let me have a chat with the web team and see what they think.

@wangzhizhou any thoughts to add? (thanks for the effort btw)

**Comment by waveform80** [comment]
I did build a little Python script that did this (generated an offline copy of the docs) way back when (several years ago). I might still have it somewhere if it's wanted?

**Comment by bennuttall** [comment]
Merged! Thanks

**Pull request merged**
