### PR TITLE
Update led_blink_warnings.adoc

### PR DESCRIPTION
**Pull request by JamesH65**
These errors are also applicable to the Pi 5

### CODE REVIEW

**Comment by JamesH65** [comment]
@timg236 Is this now correct for the Pi 5?

**Comment by lurch** [comment]
Presumably the "RP1 not found" is also specific to just the Pi 5?

**Comment by timg236** [comment]
> Presumably the "RP1 not found" is also specific to just the Pi 5?

RP1 is Pi5 family only

**Comment by timg236** [comment]
Changes look good though

**Review by nathan-contino — APPROVED** [review]
LGTM!

**Pull request merged**
