### PR TITLE
Update raspi-config.md

### PR DESCRIPTION
**Pull request by YOUN3SS**
The menu has changed
Sub-menus to be done

### CODE REVIEW

**Comment by lurch** [comment]
Will you be adding further commits to this PR? :)

**Comment by YOUN3SS** [comment]
Yes, as soon as I have some time I'll complete the documentation with the new details for each menu.
I'm GH new user so If I'm doing it wrong please let me know :)

**Comment by lurch** [comment]
Well, the normal practice is to make all the edits on your fork, and then only submit a Pull Request when it's ready to be merged. But as you've already made the PR, then any further edits you make in your `patch-1` branch will automatically show up here :)

**Comment by JamesH65** [comment]
This PR has been superceded by another PR and can be closed.

**Pull request closed without merging**
