### PR TITLE
Fix titles redux

### PR DESCRIPTION
**Pull request by lurch**

### CODE REVIEW

**Comment by aallan** [comment]
@lurch Is this fixable?

Screenshot 2021-08-09 at 12 14 39

The title of the `documentation/` is "Raspberry Pi Documentation - index" any way to make that "Raspberry Pi Documentation" without breaking the rest of the titles.

**Comment by lurch** [comment]
Not easily... :confused:

**Comment by lurch** [comment]
Alternatively we could make it say "Raspberry Pi Documentation - Computers" since the "index page" **is** a copy of the "computers category page"? :shrug:

**Comment by aallan** [comment]
> Alternatively we could make it say "Raspberry Pi Documentation - Computers" since the "index page" **is** a copy of the "computers category page"? 🤷

That's bad for SEO. 😢 

Any way to just hardwire it?

**Comment by lurch** [comment]
Okay, let me try a different tactic...

**Comment by lurch** [comment]
...hmmm, nope my alternative tactic:
```patch
diff --git a/jekyll-assets/_layouts/docs.html b/jekyll-assets/_layouts/docs.html
index 0e187ffb..346978c8 100644
--- a/jekyll-assets/_layouts/docs.html
+++ b/jekyll-assets/_layouts/docs.html
@@ -14,7 +14,7 @@
       {% include nav.html %}
 
       <section id="content">
-        <h1>{{ page.title }}</h1>
+        <h1>{{ page.sub_title }}</h1>
         {{ content }}
       </section>
     </div>
diff --git a/scripts/create_build_adoc.py b/scripts/create_build_adoc.py
index c6796ab7..c2577e7b 100755
--- a/scripts/create_build_adoc.py
+++ b/scripts/create_build_adoc.py
@@ -30,7 +30,8 @@ if __name__ == "__main__":
         out_fh.write(""":parentdir: {}
 :page-layout: docs
 :includedir: {}
-:doctitle: Raspberry Pi Documentation - {}
+:doctitle: {}
+:sub_title: {}
 
 include::{{includedir}}/{{parentdir}}/{}[]
-""".format(output_path, src_dir, index_title, adoc_filename))
+""".format(output_path, src_dir, 'Raspberry Pi Documentation - {}'.format(index_title), index_title, adoc_filename))
```
didn't work as it ends up with the `<h1>` tags in the generated docs pages (e.g. `documentation/computers/linux_kernel.html`) being empty :slightly_frowning_face:  (Looks like the Jekyll template can't "see" the `sub_title` variable? :shrug: )
I think this might be one for @nelliemckesson as it goes beyond my basic Jekyll knowledge!

**Comment by aallan** [comment]
> https://twitter.com/Gadgetoid/status/1424701341520310274

Okay. I'm going to merge your intial fix then (aka this PR) that fixes everything except the top level index header. 

Thanks!

**Review by aallan — APPROVED** [review]
Need to fix the top level title so it's "Raspberry Pi Documentation" rather than "Raspberry Pi Documentation - Index" but other than that, LGTM.

**Comment by lurch** [comment]
> (Looks like the Jekyll template can't "see" the sub_title variable? :shrug: )

I took a lucky guess at the fix and it worked :tada:  #1980

**Comment by duynguyen0209** [comment]
Vge

**Pull request merged**
