### PR TITLE
Original boot cmdline doesn't work anymore. Fixed the docs.

### PR DESCRIPTION
**Pull request by dagelf**
It worked as soon as I removed init=

### CODE REVIEW

**Comment by JamesH65** [comment]
Bit confused, I cannot find an `init=` in the docs or in the cmdline.txt of a standard Pi. Where is the original cmdline you are talking about?

**Comment by XECDesign** [comment]
It's in cmdline.txt before first boot. If it prevents netbooting, it should be fixed within the script.

**Comment by XECDesign** [comment]
Yes, that would be me.

**Comment by JamesH65** [comment]
@XECDesign  Thoughts?

**Comment by XECDesign** [comment]
No objections. It will be a while before we release a new image, and it doesn't make sense to waste peoples' time with undocumented bugs.

**Pull request merged**
