### PR TITLE
removed umask=000 because it fails with `Unrecognized mount option "u…

### PR DESCRIPTION
**Pull request by brunoamaral**
…mask=000" or missing value`

Using Raspbian 9 (stretch)

### CODE REVIEW

**Comment by JamesH65** [comment]
I've just tried this action on a recent (4.19) kernel, and I do not get the error message you describe, even with umask=000 in the fstab entry, the device mounts correctly. Is there anything different with your setup?

**Comment by brunoamaral** [comment]
Could be the kernel version I am using. This is the output of uname: `Linux johnnyfive 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux`

I can try to upgrade and test again at home.

**Comment by JamesH65** [comment]
Hmm, I tested on 4.19.0, I'll need to find a lower version to check with as well.

**Comment by lurch** [comment]
http://downloads.raspberrypi.org/raspbian/release_notes.txt
http://downloads.raspberrypi.org/raspbian/images/

:wink:

**Comment by brunoamaral** [comment]
Not sure if it's relevant, but it's a Rpi 2. And running a remote upgrade of the kernel didn't get it up to 4.19: `Linux johnnyfive 4.14.90-v7+ #1183 SMP Fri Dec 21 14:03:50 GMT 2018 armv7l GNU/Linux`

**Comment by JamesH65** [comment]
4.19 is only availabled via rpi-update - its currently being tested to get it ready for full release which is why I am using it. Unless you are happy with bleeding edge kernels, I'd suggest sticking with what you have. I'll try and find some time to check this on a lower version kernel.

**Comment by andrum99** [comment]
Perhaps it would be worth mentioning the security implications of umask=000, should it be retained on this page of the docs.

**Comment by JamesH65** [comment]
What are the security implications? I have no idea what it does!!

**Comment by andrum99** [comment]
Umask used as a mount option to a FAT or NTFS filesystem will make all
files fully accessible to all users on the Pi. My question was whether it
was worth mentioning this.

**Comment by andrum99** [comment]
I think a better fix for this issue would be to state that umask=000 should only be user for FAT and NTFS filesystems (and possibly Mac HFS as well). Also mention the security implications of this setting.

**Comment by JamesH65** [comment]
Happy to have any changes to this PR to match comments above. @brunoamaral

**Comment by brunoamaral** [comment]
@JamesH65 I read the comments by @andrum99 and I agree that this is more of a matter of communicating the caveats and implications rather than fixing anything in code. Both of you have a better perspective on this issue, so let me know if you want me to close this PR or amend it in any way.

**Comment by andrum99** [comment]
I believe what James is suggesting is that he would be happy to have this PR amended per my last comment - i.e. only suggest umask=000 for certain non-Linux-native filesystems, and mention that it makes all files on the drive fully accessible to all users on that Pi. Umask=000 is useful for those particular filesystems.

I've just realised github is saying this file has conflicts - this is due to another PR (from me) integrating while this one was cooking. That PR was in April 2019. It is therefore probably easier if I just raise a new PR referencing this one. Once I have done that, you or James can close this PR.

**Comment by andrum99** [comment]
See #1271 for PR that includes all above changes. This PR can be closed now.

**Pull request closed without merging**
