### PR TITLE
Update nginx.md

### PR DESCRIPTION
**Pull request by fmirko**
On my raspberry pi, I need to restart the nginx  http server before to be able to see index.php

### CODE REVIEW

**Comment by XECDesign** [comment]
1) Do you need to restart, or does a reload work?
2) You shouldn't need to do this after adding the index file, only after editing the config file.

Would it not be better to move this to the Enable PHP in NGINX section and change restart to reload? Or can you confirm that you actually need to restart after renaming the file?

**Comment by fmirko** [comment]
Le 28/03/2015 15:35, XECDesign a écrit :
>
> 1) Do you need to restart, or does a reload work?
>
I will check again, but reloading/refreshing the page didn't work.
I did : /etc/init.d/nginx restart, but didn't try the /etc/init.d/nginx 
reload.

I let you when I redo the test.

**Comment by ethanyoung** [comment]
I had a similar problem. A reload was needed after I edited PHP config file. I mentioned this in #130 .

**Comment by bennuttall** [comment]
Fixed in #236

**Pull request closed without merging**
