### PR TITLE
wireless-cli: place update_config=1 on new line

### PR DESCRIPTION
**Pull request by labtoast**
Current pi image has error in wpa_supplicant.conf because GROUP="netdev update_config=1". The instructions are modified with the config file fix and a command to view wpa_supplicant output in case of other errors.

### CODE REVIEW

**Comment by XECDesign** [comment]
I don't see that in the current image at all. The wpa_supplicant.conf file seems correct as is:
```
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
```
Are you sure the line endings in your editor are correct?

**Comment by labtoast** [comment]
You are right, sorry about that. The issue is not in the image.

I've characterized the problem further. When connecting to the raspberry pi over the serial interface (TERM=vt102) nano will delete the newline (ascii 0x0a) upon *opening* the file. Nano will delete any number of spaces (ascii 0x20) leading up to the newline as well. Vi and Emacs do not have this issue over the same interface.

Examples:
```
[... 'd', 'e', 'v', 0x0a, 'u', 'p'...]                         => [... 'd', 'e', 'v', 0x02, 'u', 'p'...]
[... 'd', 'e', 'v', 0x20, 0x0a, 'u', 'p'...]                   => [... 'd', 'e', 'v', 0x02, 'u', 'p'...] 
[... 'd', 'e', 'v', 0x20, 0x20, 0x20, 0x20, 0x0a, 'u', 'p'...] => [... 'd', 'e', 'v', 0x02, 'u', 'p'...] 
```

My steps to reproduce:
1) connect serial cable[1] to computer[2]
2) open terminal session `screen /dev/cu.usbserial 115200`
3) login to raspberry pi[3]
4) open config file `sudo nano /etc/wpa_supplicant/wpa_supplicant.conf`
5) observe lack of newline
6) add newline after `GROUP=netdev`
7) reopen config file `sudo nano /etc/wpa_supplicant/wpa_supplicant.conf`
8) observe lack of newline

[1] http://www.amazon.com/gp/product/B00DJUHGHI?psc=1&redirect=true&ref_=oh_aui_detailpage_o00_s01
[2] OSX 10.11
[3] Model A+

**Comment by XECDesign** [comment]
Not having much luck reproducing the issue on Mint.

**Comment by lurch** [comment]
Sounds like it's probably a terminal-emulator settings problem? I suspect the newline **is** still there, it's just not being displayed correctly.
(Not having a Mac though, I've got no suggestions on how to fix it)

**Comment by labtoast** [comment]
I suspect a terminal setting issue as well.

I've tried to reproduce the issue with the following configurations:
```
OSX 10.11, Terminal, Screen 4.00.03, PL2303 cable, nano           issue
OSX 10.11, Terminal, Screen 4.00.03, PL2303 cable, emacs          no issue
OSX 10.11, Terminal, Screen 4.00.03, PL2303 cable, vi             no issue
Ubuntu 14.04(VM), Terminal, Screen 4.01.00, PL2303 cable, nano    no issue
Win 10, Putty, PL2303 cable, nano                                 no issue
```

**Comment by labtoast** [comment]
@lurch I have verified using a hex editor that the newline gets deleted. This is what causes wpa_supplicant to fail when launching.

**Comment by lurch** [comment]
@labtoast Yeah, I guess if the terminal-settings are wrong, such that newlines in files don't get displayed correctly on your Mac, then it makes sense that newlines sent from the Mac to the Pi also don't get translated properly?
Have you tried using different terminal emulator programs on your Mac (I'm sure there must be lots), to see if there are any that work better? Alternatively I guess you could try scouring into the `screen` [manual](https://www.gnu.org/software/screen/manual/screen.html) .

**Comment by labtoast** [comment]
A few more data points. I updated screen to 4.03 (no change) and tried minicom which did not have an issue.

```
OSX 10.11, Terminal, Screen 4.03.01, PL2303 cable, nano           issue
OSX 10.11, Terminal, Minicom 2.7, PL2303 cable, nano              no issue
OSX 10.11, iTerm2.1.1, Screen 4.03.01, PL2303 cable, nano         issue
```

I don't need to resolve this at this point. Just hoping this info might save someone else some time.

**Pull request closed without merging**
