### PR TITLE
Fix instructions for Linux installs: remove truncate bit, add expand filesystem notes

### PR DESCRIPTION
**Pull request by azizLIGHT**
Remove old instructions, and mention the ability to expand the filesystem

### CODE REVIEW

**Comment by waveform80** [comment]
Looks good to me; the existing truncate instructions are incorrect and `raspi-config` is by far the most "user friendly" way of expanding the FS up to the size of the chosen SD card.

**Comment by XECDesign** [comment]
The bit about truncating the image is about verifying that what was written was correct. If you remove that, then the previous paragraph is useless.

**Comment by waveform80** [comment]
Ah, missed that the former paragraph was about copying back - thought this was to with file-system expansion (serves me right for skimming stuff late at night). Is verification worth having in the instructions? I note there's nothing similar in the Mac/Win sections.

For that matter, would it be worth having `raspi-config` mentioned at the end (or a link to the [raspi-config](https://www.raspberrypi.org/documentation/configuration/raspi-config.md) page?)

**Comment by JamesH65** [comment]
Unless I hear otherwise, I'll close this in a week, I don't think it's relevant. If there is an issue with the current truncate instructions (should they even be there?) I'd suggest raising an issue.

**Comment by JamesH65** [comment]
No responses so closing.

**Pull request closed without merging**
