### PR TITLE
Replace Simple Jekyll Search with Algolia DocSearch

### PR DESCRIPTION
**Pull request by mudge**
In order to provide a better search experience and address some of the usability issues raised in https://github.com/raspberrypi/documentation/issues/1987, replace our Simple Jekyll Search-powered search box with one provided by [Algolia DocSearch][0].

We use the default, [out of the box theme provided by DocSearch v3][1] as customising it will involve rewriting/overriding the CSS provided directly by Algolia or overriding the default options in JS to render our own markup. As it is, my hope is that it provides a better user experience than the current search box.

  [0]: https://docsearch.algolia.com
  [1]: https://docsearch.algolia.com/docs/styling

Screenshot 2022-01-04 at 16 18 30

### CODE REVIEW

**Comment by aallan** [comment]
Alternative to #2315.

**Comment by lurch** [comment]
I'll leave any functionality and Look'n'Feel comments to @aallan and @jackbenwillis (other than to say that this obviously gives **much** better search results than our previous header-only-search did), but from a technical PoV the code-changes here (including removal of the old static search) look fine :+1:  Well done @mudge with the Python and Ninjabuild hacking.

The only slight drawback (which I guess is unavoidable with _any_ cloud-based search system) is that when I'm viewing http://127.0.0.1:4000/documentation/ for local testing, the search results take me directly to a page on https://www.raspberrypi.com/documentation/ (so we'll just have to remember to double-check which version we're looking at when doing local testing).

**Comment by mudge** [comment]
Is there any value in getting this deployed without building out our own custom look and feel (which is [not fully documented by Algolia](https://docsearch.algolia.com/docs/styling))? The Crawler has been running daily with success and it might be that the improved search is worth the non-Raspberry Pi branded UI?

If we were to try to customise the appearance, I'd recommend we stick to customising only the [official variables exposed by DocSearch](https://github.com/algolia/docsearch/blob/next/packages/docsearch-css/src/_variables.css) which is mostly colours and sizing rather than anything more significant like disabling the modal altogether, etc.

**Comment by aallan** [comment]
> Is there any value in getting this deployed without building out our own custom look and feel (which is not fully documented by Algolia)? The Crawler has been running daily with success and it might be that the improved search is worth the non-Raspberry Pi branded UI?

That sounds like a @jackbenwillis + me decision rather than just a me decision. I'll bring it up in the Comms standup this morning. 

> If we were to try to customise the appearance, I'd recommend we stick to customising only the official variables exposed by DocSearch which is mostly colours and sizing rather than anything more significant like disabling the modal altogether, etc.

I'd be happy to deploy it immediately so long as we get the colours sorted out so it looks brand-ish, and I guess we have to try and make it uses Roboto font (if that's possible, if it doesn't already).

**Comment by mudge** [comment]
@aallan @jackbenwillis here's a version with the DocSearch primary colour set to Raspberry Red (#cd2355) and the Algolia logo set to our red tint (#d75a64).

https://user-images.githubusercontent.com/287/151948525-eed1ba4e-6c7c-49fb-8df8-b2ab8200d177.mov

**Review by aallan — APPROVED** [review]
I think that's deployable now, and we can talk about doing further customisation later if needed.

**Pull request merged**
