### PR TITLE
Update VNC docs

### PR DESCRIPTION
**Pull request by lurch**
It's actually `sudo apt-get install package` you use to upgrade already-installed packages (confusing, I know), rather than `sudo apt-get upgrade package`. The latter upgrades *all* packages on the system, not just the ones specified on the command line.

### CODE REVIEW

**Comment by minkustree** [comment]
Excellent point.

Can we also add a 
```
sudo apt-get update
```
line just before sudo apt-get install, to ensure package lists are up to date!

Apologies for not spotting this earlier.

**Comment by lurch** [comment]
Instructions **update**d ;-)

**Comment by minkustree** [comment]
Awesome, thanks!

**Comment by LornaLynch** [comment]
All merged: thank you.

**Pull request merged**
