### PR TITLE
computers/raspberry-pi : correct spelling on raspberry

### PR DESCRIPTION
**Pull request by RuffaloLavoisier**

### CODE REVIEW

**Comment by JamesH65** [comment]
LGTM

**Review by JamesH65 — APPROVED** [review]

**Comment by RuffaloLavoisier** [comment]
@JamesH65 
Thanks, TGIF !

**Comment by lurch** [comment]
LOL, it's amazing the number of different ways that a single word can be mis-spelt!

**Comment by aallan** [comment]
I'm fairly sure not being able to spell Raspberry is a prerequisite for working here. 🤷‍♂️

**Pull request merged**
