### PR TITLE
Update screen blanking

### PR DESCRIPTION
**Pull request by jehlers42**
re: issue #2959 

Removed instructions on adjusting the blank interval via the config file. Internal discussion led to encouraging changes solely through raspi-config or the config GUI.

### CODE REVIEW

**Review by aallan — APPROVED** [review]

**Comment by aallan** [comment]
Closes #2959

**Comment by aallan** [comment]
It's not Monday, but it feels like it sometimes… 🙄 

Screenshot 2023-08-22 at 15 30 18

**Comment by lurch** [comment]
I just noticed that the text just beyond the change in this PR also talks about "sudo apt install xscreensaver" - we probably don't want that, as Bookworm / Wayland comes with a screensaver built in by default? (It displays a rotating-cube of the desktop)
(and I'd guess that a program named `xscreensaver` _might_ not work on Wayland?)

ping @spl237 for thoughts / comments

**Comment by jehlers42** [comment]
Since that section mentions finding the xscreensaver app in Preferences, will the new built-in screensaver have a similar location for options relating to it or should I just remove the entire screensaver bit.

**Comment by aallan** [comment]
I'd lean towards just removing it.

**Pull request merged**
