### PR TITLE
Update linux.md - lsblk -p

### PR DESCRIPTION
**Pull request by littlebaka**
Added full path option

### CODE REVIEW

**Comment by lurch** [comment]
On Ubuntu 14.04 `lsblk -p` says `lsblk: invalid option -- 'p'`
:-/

**Comment by JamesH65** [comment]
How backwards in time do we want to remain compatible with things like Ubuntu? 14.04 is pretty old now, 16.10 seems to support it, and the Pi itself works with -p. 

The -p option does match up better with the docs.

**Comment by lurch** [comment]
> How backwards in time do we want to remain compatible with things like Ubuntu?

\*shrug\* That's entirely up to you.

Brief aside: the laptop I bought a few years ago came with Ubuntu 14.04 pre-installed (it was the LTS release at the time), I've never bothered to upgrade it to a newer distro, and https://wiki.ubuntu.com/Releases says it's supported until April 2019.

**Comment by JamesH65** [comment]
Not sure what to do with this one.  It does make the process a little clearer, but clearly not available if you go back a few years. Hmmm.

@LizUpton Liz, any thoughts on what we should do here?

**Comment by JamesH65** [comment]
Since 14.04 is now out of LTS, I think this can be merged.

**Pull request merged**
