### PR TITLE
Push to production

### PR DESCRIPTION
**Pull request by aallan**

### CODE REVIEW

**Comment by lurch** [comment]
Now that this has been pushed live, it looks like the text for the "NOTE" might be a different colour than the text for the links? Or perhaps I'm getting old and my eyes are just playing tricks on me? :man_shrugging: 
Screenshot from 2021-12-16 13-28-15

ping @mudge

**Comment by mudge** [comment]
@lurch if you inspect that element (a `<div>` with class `title`), you'll see it has a `color` of `var(--red)` (which is set to `#cd2355`) which is the same as the `color` for `<a>` tags.

**Comment by aallan** [comment]
Could be the [NOTE] being in bold just makes it look more red?

**Comment by lurch** [comment]
Yeah, probably just the font anti-aliasing that's confusing my eyes :eyes:

**Pull request merged**
