### PR TITLE
Adding .NET support

### PR DESCRIPTION
**Pull request by aallan**
Rough initial rework of #2364, for discussion. Mostly stylistic issues, and removing references to Windows.

Ping @Ellerbach and @topshed.

### CODE REVIEW

**Comment by topshed** [comment]
We do have official photos from LEGO of the Spike components that we could use - they are more consistent with each other than the ones in this PR I think. We also use them on the Build HAT Python librarty readthedocs pages.

Other than that, looks good.

**Comment by aallan** [comment]
> We do have official photos from LEGO of the Spike components that we could use - they are more consistent with each other than the ones in this PR I think. We also use them on the Build HAT Python librarty readthedocs pages.

Do you want to checkout the `dotnet-for-lego` branch and commit them on branch? Alternatively you could email them to me if you like? Thanks!

**Comment by aallan** [comment]
Probably merge to `develop` mid-afternoon today if there aren't any substantive objections.

**Comment by aallan** [comment]
Pushed live in #2408

**Comment by Ellerbach** [comment]
> Pushed live in #2408

Great! Happy I'll help .NET developers! Interested in Sense HAT as well?

**Comment by aallan** [comment]
> > Pushed live in #2408
> 
> Great! Happy I'll help .NET developers! Interested in Sense HAT as well?

Looking at the current Sense HAT documentation it's from the "pre-me-doing-documentation" times, so if you look at https://www.raspberrypi.com/documentation/accessories/sense-hat.html#sense-hat-software you can see that what we have is a paragraph (or so) and pointers to external documentation for the Python and RTIMULib libraries.

At some point we need to fix that and document the Sense HAT properly, but that time is not today.

For now, I'd be happy to get a PR that would fit into that scheme. So a section to drop into the "Sense HAT Software" section pointing to the .NET library documentation that is hosted elsewhere (the library's own Github page?).

**Pull request merged**
