### PR TITLE
Push to production

### PR DESCRIPTION
**Pull request by aallan**

### CODE REVIEW

**Comment by aallan** [comment]
Big bunch of things getting pushed here. I've run the `develop` HEAD locally a bunch, but would appreciate someone else taking a look before I push. @lurch can you have a quite look?

**Comment by RuffaloLavoisier** [comment]
`DPI*.png` in `documentation/asciidoc/computers/raspberry-pi/images`

If we no longer need the existing image when the new version is reflected, it would be okay to remove it.

**Comment by aallan** [comment]
> `dpi*.png` in `documentation/asciidoc/computers/raspberry-pi/images`
> 
> If we no longer need the existing image when the new version is reflected, it would be okay to remove it.

Thanks, good catch. Can you throw a quick PR on `develop` to get rid of them?

**Comment by RuffaloLavoisier** [comment]
1 minute..

**Comment by RuffaloLavoisier** [comment]
Done https://github.com/raspberrypi/documentation/pull/2472

**Comment by lurch** [comment]
> @lurch can you have a quite look?

Done :wink: #2476

**Pull request merged**
