### PR TITLE
Split table into two for Pi4B and non Pi4B , simplify table as well

### PR DESCRIPTION
**Pull request by dp111**

### CODE REVIEW

**Review by aallan — APPROVED** [review]

**Comment by seamusdemora** [comment]
Just out of curiosity, what's the approximate timeline before these changes show up on the website?

**Comment by RuffaloLavoisier** [comment]
@seamusdemora 
ping @aallan 
Document manager.

**Comment by aallan** [comment]
> Just out of curiosity, what's the approximate timeline before these changes show up on the website?

Next time I push batched changes through to production. There isn't any larger work underway right now, so it'll probably be Monday next week.

**Comment by seamusdemora** [comment]
@aallan : OK - I'll be watching for it - thanks. 

A related question: Do you encourage pull requests for the documentation repo, or are changes all handled "in-house"?

**Comment by lurch** [comment]
> Do you encourage pull requests for the documentation repo

Yes! https://github.com/raspberrypi/documentation/blob/develop/CONTRIBUTING.md

**Comment by aallan** [comment]
…and the changes got pushed live on Monday.

**Comment by seamusdemora** [comment]
@lurch : Thanks for confirmation. I'd volunteered to do that here, but no one accepted... I thought that might have something to do with the recent transition to asccidoc, etc.

**Comment by seamusdemora** [comment]
The changes look good - thank you all.

**Pull request merged**
