### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by iugamarian**
Link to other optional setup scripts.

### CODE REVIEW

**Comment by iugamarian** [comment]
Thank you.

**Comment by lurch** [comment]
Um, what? You should provide more instructions - your README just says "Setup scripts to personalize Raspbian for my needs" which makes me suspect this PR should be closed as invalid.

**Comment by iugamarian** [comment]
I have written some instructions in README.

I hope this is usefull to the comunity.

If not, my bad.

Thank you.

2015-03-05 0:59 GMT+02:00 Andrew Scheller <notifications@github.com>:

**Comment by iugamarian** [comment]
I have a link: https://github.com/iugamarian/raspberrypisetup

Good bye.

**Comment by lurch** [comment]
IMHO your scripts are far too specific to be included in the [official documentation](http://www.raspberrypi.org/documentation/).
But there's no reason you can't add your links somewhere on the community wiki over at http://elinux.org/RPi_Hub

**Comment by iugamarian** [comment]
In fact that's what I tried to find out - where to tell the community - I worked weeks on them :) .

Thank you for telling me and I will not disturb here any more. Going to http://elinux.org .

**Pull request closed without merging**
