### PR TITLE
Update users.md

### PR DESCRIPTION
**Pull request by ElectricRCAircraftGuy**
added "Useful examples and references" to bottom of documentation

### CODE REVIEW

**Comment by JamesH65** [comment]
Change works OK and is useful, but I am not sure of RPF policy on links offsite like those, so passing up to copy edit for clarification.

**Comment by LizUpton** [comment]
We try not to use offsite links where possible; we can't control what's there, and can't be guaranteed to notice if anything changes.

**Comment by JamesH65** [comment]
OK, happy for me to close this PR due to offsite links?

**Comment by ghollingworth** [comment]
Yes, close

> --
--
Director of Software Engineering, Raspberry Pi (Trading) Limited
t:  +44 (0) 1223 322633
m: +44 (0) 7450 946289
e: gordon@raspberrypi.org
w: www.raspberrypi.org

**Pull request closed without merging**
