### PR TITLE
Correct spelling of VideoCore

### PR DESCRIPTION
**Pull request by andrum99**
See #1532

### CODE REVIEW

**Comment by andrum99** [comment]
technical_faq.md also needs some fixup for Pi 4B, but that's a bigger change unrelated to this spelling issue. I propose to leave that to a future PR, separate from this one.

**Comment by andrum99** [comment]
I've searched for 'videocore', 'video' and 'core' using Github's built-in search, so it should have picked up all occurrences 😁 Unless there's some that are completely misspelled, that should be it done.

I've also changed a couple of instances of Videocore 4 to VideoCore IV.

**Comment by lurch** [comment]
> using Github's built-in search

For this sort of thing, the GitHub search is woefully inadequate and you really need to be using a local checkout of the repo. Here are some places you missed :wink: 

* https://github.com/raspberrypi/documentation/blob/master/configuration/config-txt/boot.md#start_file-fixup_file
* https://github.com/raspberrypi/documentation/blob/master/raspbian/applications/vcgencmd.md#codec_enabled-type

> I've also changed a couple of instances of Videocore 4 to VideoCore IV.

I'm not sure how important that is, I'll leave those sorts of decisions up to James.

**Comment by andrum99** [comment]
> For this sort of thing, the GitHub search is woefully inadequate and you really need to be using a local checkout of the repo.

Thanks - will do. I've added WIP to the title of this PR to indicate this is one actually is not ready yet.

**Comment by andrum99** [comment]
> 
> > I've also changed a couple of instances of Videocore 4 to VideoCore IV.
> 
> I'm not sure how important that is, I'll leave those sorts of decisions up to James.

I've come across more instances of the use of numbers instead of roman numerals in the docs, so I've backed out those two changes, so basically Videocore 4 becomes VideoCore 4. If roman numerals are required that can be a separate PR.

**Comment by andrum99** [comment]
I've manually reverted changes to technical-faq.md so it doesn't conflict with its removal.

**Comment by andrum99** [comment]
That should be it complete now this time.

**Pull request merged**
