### PR TITLE
Add v1.2 of the Raspberry Pi Camera Algorithm and Tuning Guide

### PR DESCRIPTION
**Pull request by naushir**
Update the libcamera documentation to point to the new v1.2 file.

### CODE REVIEW

**Comment by naushir** [comment]
@JamesH65 and @davidplowman

**Comment by naushir** [comment]
Please hold off on this for a bit, I might want to make a tweak or two.

**Comment by naushir** [comment]
Ok, good to merge if everybody is happy.

**Comment by davidplowman** [comment]
Yes, I'm happy. Can we update the link on the README.md there to point to the new one as well?

**Pull request merged**
