### PR TITLE
Simplify hardware docs, update for Pi 400, CM4, grammar & style fixups

### PR DESCRIPTION
**Pull request by andrum99**

### CODE REVIEW

**Comment by JamesH65** [comment]
That does look better! Give me shout when the editing is complete.

**Comment by andrum99** [comment]
Ready to roll @JamesH65.

**Comment by JamesH65** [comment]
What was the theory behind removing the technical specs from the processor pages?

This is such a large change that it will need to go to our copy editors. Probably should have been submitted as a number of smaller PR's for ease of checking, but no worries.

@lurch Any comments?

**Comment by JamesH65** [comment]
I've asked for a quick CE on this.

**Comment by aallan** [comment]
I'd encourage you to wrap this PR up in the next week or so as we're in the process of transitioning the documentation from the current Markdown-based source format to Asciidoc. At some point soon — probably around the end of June, beginning of July — we will freeze the current documentation repo. After that time contributions and PRs based on the Markdown source will not be accepted, and any PRs that are still open will be closed.

See #1911 for full details.

**Comment by andrum99** [comment]
> I'd encourage you to wrap this PR up in the next week or so as we're in the process of transitioning the documentation from the current Markdown-based source format to Asciidoc. At some point soon — probably around the end of June, beginning of July — we will freeze the current documentation repo. After that time contributions and PRs based on the Markdown source will not be accepted, and any PRs that are still open will be closed.
> 
> See #1911 for full details.

I'm going to close this, since the pages it tackles are good candidates for some more serious consolidation once the docs move to the new toolchain so there's probably not much point spending time trying to polish the pages in their current form. Feel free to reopen if you think there's anything here worth saving.

**Pull request closed without merging**
