### PR TITLE
renamed Etcher to balenaEtcher and etcher.io to www.balena.com/etcher/

### PR DESCRIPTION
**Pull request by gmkey**
made the modifications for all affected pages rather than one. closed #1084, which - in the event you approve the change - contained only one affected page

### CODE REVIEW

**Comment by JamesH65** [comment]
There appear to be a number of whitespace related changes unrelated tothe balena change. I'd prefer, if possible, that they supplied as a separate PR, since that makes it easier to detemine relevent changes. Still waiting for confirmation from Balena themselves on the correct naming scheme.

**Comment by gmkey** [comment]
Oh dear, that seems to be the setting on my text editor (Atom). Not sure how to revert these? (not that github prolific for that matter. Please advise

**Comment by JamesH65** [comment]
Hmm, not sure of your procedure, but I'd revert the whitespace changes, then use git commit --amend to update the PR. Or, make another PR that just has the whitespace changes in, send that in, then rebase this PR with that one. Or something.

**Comment by lurch** [comment]
Ping @thundron and @zvin (and see also #1084, where this was also discussed)

**Comment by JamesH65** [comment]
Part of the problem is that balenaEtcher is such an awkward (and terrible) name. Everyone is still just going to call it Etcher (a great name) whatever its actual name is, and changing the docs might make it more confusing rather than less.

**Comment by bennuttall** [comment]
FWIW etcher.io was a better URL too

**Comment by lurch** [comment]
@JamesH65 See also "GNU/Linux" and "Microsoft Windows" :wink:   (which everyone calls just Linux and Windows)

**Comment by gmkey** [comment]
I agree with most your comments and I do feel that some marketing intern at etcher has probably forgot to read branding 101. 
At the same time most of the target Community are inexperienced, the name could set them of on the wrong foot. 
IMHO waiting for a statement from etcher / baloney (err balena ;-) is the sensible thing to do.

**Comment by gmkey** [comment]
PS “GNU/Linux” is actually a name given to the Linux project by the FSF. AFAIK the Linux Project at kernel.org talk only about Linux.

**Comment by lurch** [comment]
Ping also @jviotti and @alexandrosm

**Comment by JamesH65** [comment]
Going to merge this with the whitespace changes as well - bit confusing, but they need to be done anyway.

**Pull request merged**
