### PR TITLE
Revert "Jamesh65 patch 1#552 SSH instructions"

### PR DESCRIPTION
**Pull request by JamesH65**
Reverts raspberrypi/documentation#555

### CODE REVIEW

**Comment by AisforAstronaut** [comment]
Edit permissions restored. Thank you!

**Comment by AisforAstronaut** [comment]
All files checked. Changes made. Pushing back for technical checking.

**Comment by JamesH65** [comment]
This appears to have lost the changes I made, no idea why, the shenanigans of yesterday I suspect.  Only the first file was changed, so I will do the change again, and resubmit for copy edit.

**Comment by JamesH65** [comment]
OK, have made the changes, only to README.md, so only that needs checking.

**Comment by AisforAstronaut** [comment]
I've edited myself! One change to the second sentence. Everything else is fine.

**Pull request merged**
