### PR TITLE
WIP: Move FAQs into docs

### PR DESCRIPTION
**Pull request by bennuttall**
WIP - just imported HTML, need to convert to markdown and make sure it's presented ok.

### CODE REVIEW

**Comment by JamesH65** [comment]
Looks pretty good already! Import has done a decent job of lists and indentation.

**Comment by JamesH65** [comment]
Just merged my HTML->MD changes. Going to get this copy edited now I think, ready for linking to main website.

**Comment by JaninaPi** [comment]
I've CE'd, meaning made the headings not all in capitals, and fixed a couple of things that jumped out at me. Some of the sections needs updating — the PoE, "When's the next model", and netbooting/PXE questions are the ones I noticed.

**Comment by JamesH65** [comment]
@LizUpton Liz, you may well want to have a look at this prior to publishing it to remove older fluff. Moving it to github makes it a lot easier to edit so should be easier to keep up to date.

**Comment by JamesH65** [comment]
@LizUpton Ping.

**Comment by JamesH65** [comment]
@LizUpton If you don't have time to check out this and #864, I'm happy with them so they could just be merged - they have already been CE'd.

@bennuttall You happy to update the relevant Wordpress pages to point to these ones?

**Comment by LizUpton** [comment]
Thanks James - and sorry; I moved this onto my ToDo list, but it's...monstrously full at the minute. Very happy for you to just merge and close.

**Comment by LizUpton** [comment]
Sorry - accidentally closed!

**Comment by bsimmo** [comment]
Could you check all the links index links, two I've tried on GitHub page did not jump to the correct title (didn't go to any title).

**Comment by JamesH65** [comment]
I think this one still needs a CE as well. Its is actually a straight copy of the current FAQ, so there must be mistakes in that too!

**Comment by JamesH65** [comment]
OK, have fixed the links and am going to merge as is. If there are any remaining issues we can sort them out once all plumbed in. It does need a going over anyway, so in effect all that happening is its moving from WP to github.

**Comment by bennuttall** [comment]
Now live here: https://www.raspberrypi.org/documentation/faqs/ - James do you want to check the presentation over? I can see a few issues with headers/indentation I'll fix now

I will get the web team to add a redirect when we're ready to go.

**Comment by JamesH65** [comment]
Hmm. None of the links work, I think because the auto move from github to the docs capitalises all the headings which in turn breaks all the links which are in lower case. I could go though and capitalise everthing....but what is the reason fro the auto capitlisation? Look a bit aggressive.

**Comment by bennuttall** [comment]
Oh the anchor links? GitHub itself makes these automatically, but that's extraneous to standard markdown parsing. We have to add anchor links manually (in HTML). Hang on while I push some changes and I'll show you.

**Comment by bennuttall** [comment]
I've pushed the header changes and an example anchor link. Annoyingly the fixed nav bar makes anchors offset anyway so they're not entirely useful. What do you think?

**Comment by JamesH65** [comment]
I'm inclined to remove the entire index section. You have to scroll through it anyway to read all the titles, you may as well just scroll through the FAQ itself.

**Comment by bennuttall** [comment]
Good idea!

**Comment by JamesH65** [comment]
OK, I'll anchor the section headings only then.

**Comment by bennuttall** [comment]
I'm half way through it!

**Comment by JamesH65** [comment]
Or you can do it.....!

**Comment by bennuttall** [comment]
Added links, not removed unused ones yet...

**Pull request merged**
