### PR TITLE
FTP set-up tutorial for Rpi

### PR DESCRIPTION
**Pull request by malsony**
Hi, I guess there might be users who would like to set up an FTP server even though sftp-server allow secured SFTP, because the Rpi owners sometimes do not want to bother. So I wrote this, any ideas?

### CODE REVIEW

**Comment by XECDesign** [comment]
Thanks, looks good. Although vsftpd would've been better, this is better than nothing. Could you please squash the commits?

**Comment by malsony** [comment]
Thanks for your time reading it (found some typing mistakes after pulling)! :P To be frank, I am new to GitHub and was trying to learn how to use it... I even wanted to translate the documentation into Chinese...

**Comment by XECDesign** [comment]
Are you using the 'git' command or are you only using the features given by the github website? If it's the former, this link should help http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html . If it's the latter, I don't think you can do it that way.

**Comment by lauraclay** [comment]
We have a guide to using Github here:

https://www.raspberrypi.org/github/

Generally, try to make one pull request, rather than several updates to a page. And yes, unfortunately there are a few grammatical mistakes in your request.

**Comment by hazand** [comment]
unnamed

**Comment by malsony** [comment]
So I just close this request and request again after changes?

**Comment by XECDesign** [comment]
Nope, you can keep making changes on your fork and the pull request will be updated as you go. If you would like, I can just take your changes and squash them myself.

**Comment by malsony** [comment]
Thanks, you gave a tutorial and I would like to try it myself first.

**Comment by lauraclay** [comment]
If trying yourself results in having to proofread seven files instead of two, it would be preferable to follow the tutorial.

**Comment by XECDesign** [comment]
If malsony was successful, there would've been a single commit and a single file changed.

**Comment by pelwell** [comment]
Yes, I think there has been a misunderstanding.

**Comment by malsony** [comment]
Hi I tried squash all those entries of ftp.md with Git GUI, but I could not find a way deleting the mistaken entries of README.md? I read the website XECDesign provided above and browsed a book, but could not find a clue, or did I misunderstand? Thanks!

**Comment by XECDesign** [comment]
Git was designed to be driven from the terminal. I'm sure there are lots of different GUI frontends for it, but it seems like they get in the way more than they help. I really can't help here.

**Comment by malsony** [comment]
Hi, thanks for the tips, I can follow the Terminal guide, but maybe my concept of "delete" is wrong.

**Comment by hazand** [comment]
Thanks for your help.

**Comment by XECDesign** [comment]
So how do you want to proceed, malsony?

**Comment by malsony** [comment]
I have come to "git checkout" and "git reset", but my guide told me not to push at my decision, for it might be causing problems... I have to say that I have to give it up this time, but can I try another time? Sorry for the messed-up...

**Comment by XECDesign** [comment]
I've squashed and pushed the changes made here (your name show up in the commit history). I suspect the problem you saw was git complaining about rewriting the remote commit history. In the future, you can use the `-f` or `--force` option to push anyway.

**Comment by malsony** [comment]
My guide says "push -f" might be dangerous when working in a team, so my hands were tied....

**Comment by XECDesign** [comment]
It's perfectly fine to use in situations like this. The warning is there 
if you run it by accident without understanding that it will 
inconvenience people who have checked out your fork.

**Pull request closed without merging**
