### PR TITLE
Update access-point.md

### PR DESCRIPTION
**Pull request by tazz4843**
Edited line 143 to clarify the space between 'hostapd' and 'bridge-utils'

### CODE REVIEW

**Comment by XECDesign** [comment]
Out of curiosity, in what cases would it be reasonable to assume the space is optional? It seems to me like the documentation would have thousands of commands with spaces and none of them would be optional, as far as I know. Since adding this warning to each one is not reasonable, what makes this a special case?

**Comment by JamesH65** [comment]
I had the same question. There is clearly a space in the command as
written, so what particular reason do you have for emphasising this?

On 24 July 2017 at 13:17, XECDesign <notifications@github.com> wrote:

> Out of curiosity, in what cases would it be reasonable to assume the space
> is optional? It seems to me like the documentation would have thousands of
> commands with spaces and none of them would be optional, as far as I know.
> Since adding this warning to each one is not reasonable, what makes this a
> special case?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_raspberrypi_documentation_pull_698-23issuecomment-2D317404158&d=DwMFaQ&c=DpyQ_ftY536pf7wCBQXXU58xADDRY77THQzJu1OmzOo&r=w09_2ePv8G3zRjoV19Wm1Q6rI7CDlOns4PuRv2hHkek&m=Jkc3BdFQjuTVzPKYZ6ZHbB03fje5ygoXXYzmWLnV4NM&s=alWFyu74swv_E8DSEV5gHyBAi_QMZdgrA7PYBlU1HS0&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADqrHdzFj-5F46sTfiG-5Ftwmf34yKWaV55Mks5sRItzgaJpZM4OgTJ3&d=DwMFaQ&c=DpyQ_ftY536pf7wCBQXXU58xADDRY77THQzJu1OmzOo&r=w09_2ePv8G3zRjoV19Wm1Q6rI7CDlOns4PuRv2hHkek&m=Jkc3BdFQjuTVzPKYZ6ZHbB03fje5ygoXXYzmWLnV4NM&s=qmfF3edyRBrXebbCN73_DpQGLKSgBVpPBCXdYp8kAbQ&e=>
> .
>



-- 
James Hughes
Principal Software Engineer,
Raspberry Pi (Trading) Ltd

**Comment by bennuttall** [comment]
:-1: we can't add in ad-hoc notes like this without adding them everywhere!

**Comment by JamesH65** [comment]
I'm going to close this, I don't think that its an appropriate change, sorry.

**Pull request closed without merging**
