### PR TITLE
Fix path for rpcbind defaults and fix rpcbind option

### PR DESCRIPTION
**Pull request by ricardobranco777**
Fix path for rpcbind defaults and fix rpcbind option.

### CODE REVIEW

**Comment by lurch** [comment]
It looks like this file now says:
```
# /etc/init.d/rpcbind

OPTIONS=""

# Cause rpcbind to do a "warm start" utilizing a state file (default)
OPTIONS="-w"

# Uncomment the following line to restrict rpcbind to localhost only for UDP requests
# OPTIONS="${OPTIONS} -h 127.0.0.1 -h ::1"

# Uncomment the following line to enable libwrap TCP-Wrapper connection logging
# OPTIONS="${OPTIONS} -l "
```
so the bits talking about "to get rid of either `-l` or `-h 127.0.0.1`" don't seem correct?

Ping @pelwell in case he has any NFS-knowledge (or knows who does?)

**Comment by pelwell** [comment]
@popcornmix is the main NFS user here.

**Comment by pelwell** [comment]
At first glance that whole line now appears to be redundant.

**Comment by popcornmix** [comment]
I only run nfs shares on a trusted network so I haven't looked at securing ports with rpcbind.

Typically I just install nfs-kernel-server /  nfs-common, and edit /etc/exports / /etc/fstab and things work for me.
This seems far more complicated (presumably for security reasons).

**Comment by aallan** [comment]
@jehlers42 Can you look at this one, and get it ready to merge, or close as appropriate.

**Comment by aallan** [comment]
Actually @nathan-contino this might be one for you!

**Comment by nathan-contino** [comment]
@aallan removed this line as per discussion with @popcornmix. Ready to merge when you are.

**Review by aallan — APPROVED** [review]

**Comment by aallan** [comment]
Merged!

**Pull request merged**
