### PR TITLE
Setup: remove content, point to getting started guide instead

### PR DESCRIPTION
**Pull request by andrum99**

### CODE REVIEW

**Comment by andrum99** [comment]
Changed my mind - I've gone for the nuclear option of just deleting the page content and pointing to the much more up-to-date getting started guide instead.

**Comment by lurch** [comment]
I guess this is up to @aallan given that he's said he already has plans to overhaul/refresh the documentation :slightly_smiling_face:  #1810

**Comment by andrum99** [comment]
> I guess this is up to @aallan given that he's said he already has plans to overhaul/refresh the documentation 🙂 #1810

Indeed. I think when I saw the reference to NOOBS on this page I thought it was worth just pointing to the much better 'getting started guide' rather than trying to edit the page, given the getting started guide is far better. An alternative would simply be to remove reference to NOOBS from this page.

**Comment by JamesH65** [comment]
Going to be a while before @aallan is going to have time to look at this I suspect, so in the meantime we should just carry on as before. 

WRT this change, its true the Getting Started guide is much better, and duplicating stuff seems pointless, so I guess this is OK.

**Comment by aallan** [comment]
> Going to be a while before @aallan is going to have time to look at this I suspect, so in the meantime we should just carry on as before.

Agreed. I don't see the overhaul project starting in earnest for another mont or so at the earliest.

**Comment by lurch** [comment]
I just had a look and https://projects.raspberrypi.org/en/projects/raspberry-pi-setting-up/1 doesn't mention the composite video output available on the AV connector, but perhaps that's too much of a niche case to be worth documenting? :man_shrugging:

**Comment by andrum99** [comment]
> I just had a look and https://projects.raspberrypi.org/en/projects/raspberry-pi-setting-up/1 doesn't mention the composite video output available on the AV connector, but perhaps that's too much of a niche case to be worth documenting? 🤷‍♂️

You would need to ask whoever wrote that page. I suspect the answer is as you suspect - hardly anyone uses composite. Also, Pi Zero and 400 don't do composite. (Although Zero has an unpopulated header for it).

I'm in two minds about mentioning composite - given there's no yellow (or black) composite port on the almost all Pis, unless you happen to read the spec you're not going to know it's there. On the other hand, it's something the vast majority of users would never use anyway.

**Comment by aallan** [comment]
If it's currently undocumented, it's probably a sufficiently niche case that we shouldn't spend time documenting it at this point.

**Comment by lurch** [comment]
The only reason I brought this up was because https://www.raspberrypi.org/documentation/setup/monitor-connection.md (which this PR removes) currently says:
"Others models (Raspberry Pi B+ and later) combine the audio out and composite out on to the same 3.5mm jackplug. This requires a particular type of lead, with audio left on the tip, audio right on ring 1, ground on ring 2, and video on the sleeve. This is the same as leads used on the Zune, and on Apple devices."

But with how ubiquitous HDMI displays are now, I'm happy to accept that this probably isn't worth documenting.

**Comment by andrum99** [comment]
> The only reason I brought this up was because https://www.raspberrypi.org/documentation/setup/monitor-connection.md (which this PR removes) currently says:
> "Others models (Raspberry Pi B+ and later) combine the audio out and composite out on to the same 3.5mm jackplug. This requires a particular type of lead, with audio left on the tip, audio right on ring 1, ground on ring 2, and video on the sleeve. This is the same as leads used on the Zune, and on Apple devices."
> 
> But with how ubiquitous HDMI displays are now, I'm happy to accept that this probably isn't worth documenting.
> 
> (EDIT: see also https://github.com/raspberrypi/documentation/blob/master/configuration/config-txt/video.md and https://github.com/raspberrypi/documentation/blob/master/faqs/README.md#pi-video-displays )

I'm not sure if the fact that https://www.raspberrypi.org/documentation/setup/monitor-connection.md mentions composite makes any real difference - most people don't read the documentation pages. To me, if you're going to mention composite it should be on the relevant product pages, with perhaps a passing reference in the getting started guide.

I'm happy to close this PR and instead file a PR to just remove reference to NOOBS from this particular page if folk think that's a better solution.

**Comment by JamesH65** [comment]
Anecdotally, I think we still have a surprising number of users especially third world, that complain like mad if composite threatens to leave. Also the Retro gaming community do like their composite displays.

**Comment by andrum99** [comment]
> Anecdotally, I think we still have a surprising number of users especially third world, that complain like mad if composite threatens to leave. Also the Retro gaming community do like their composite displays.

It sounds like I should shelve this PR and instead submit one that just removes reference to NOOBS from this page. I will now do that.

If it is decided that this PR is the best approach, then it can of course be resurrected.

**Comment by andrum99** [comment]
See #1819

**Pull request closed without merging**
