### PR TITLE
Update conditional.md

### PR DESCRIPTION
**Pull request by JamesH65**
Added new models, and section on GPIO filtering

### CODE REVIEW

**Comment by JamesH65** [comment]
@6by9 @pelwell Does this seem correct to you guys? If so I will merge it.

**Comment by 6by9** [comment]
Let me check. As noted in the forum thread I reverse engineered the gpio syntax from the code but haven't tried it.

**Comment by pelwell** [comment]
The gpio section looks correct from reading the code, but I've not tried it myself.

It's worth mentioning that a Zero W will see the contents of `[pi0w]` _and_ `[pi0]`. Likewise, a 3B+ sees `[pi3+]` _and_ `[pi3]`. If you want a setting to apply only to Pi Zero or Pi 3B you need to follow it (order is important) with a setting in the `[pi0w]` or `[pi3+]` section that reverts it.

**Comment by JamesH65** [comment]
Have added @pelwell comments almost verbatim.

**Comment by 6by9** [comment]
Confirmed that gpio works as described. Looks all good to me.

**Comment by pelwell** [comment]
Agreed.

**Pull request merged**
