### PR TITLE
Update pin-configuration.md

### PR DESCRIPTION
**Pull request by JamesH65**
The sample DTS section links to a infrequently updated example, so removing the entire (now small) section seems prudent.

### CODE REVIEW

**Comment by JamesH65** [comment]
Fixes #359

**Comment by JamesH65** [comment]
Note to copy edit, the dt-blob file has been deleted for this PR, so no need to check it.

**Comment by JamesH65** [comment]
Actually, changed my mind - I've retained the section but added a link to the master source file, rather than the one in the documentation tree.

**Comment by AisforAstronaut** [comment]
Is there anything I need to check here, or is it ready to merge?

**Comment by JamesH65** [comment]
The pin-configuration.md file could probably do with a once over.

**Comment by AisforAstronaut** [comment]
I'll take a look now.

**Comment by AisforAstronaut** [comment]
This seems to have opened a new PR: #556

**Comment by JamesH65** [comment]
OK, original merge merged from your branch in to my patch branch (the PR itself), I've now merged that in to the main doc tree and deleted the PT branch.

**Pull request merged**
