### PR TITLE
Add Pi 5 model filter to config.txt documentation

### PR DESCRIPTION
**Pull request by nathan-contino**
Missed at release time.

### CODE REVIEW

**Review by aallan — APPROVED** [review]

**Comment by cmitu** [comment]
According to https://github.com/raspberrypi/firmware/issues/1839, this is not (yet) supported.

**Comment by lurch** [comment]
@cmitu That issue was last updated on November 6th.
@timg236 @pelwell Has the `pi5` conditional filter been added in the meantime?

**Comment by pelwell** [comment]
Support for the `[pi5]` filter appeared in the 6.1.58 kernel release of October 17th: https://github.com/raspberrypi/firmware/commit/fdb9eafae4b83e553593937eae8e77b0193903c3

**Comment by cmitu** [comment]
@pelwell thank you. Sorry for incorrect comment.

**Comment by pelwell** [comment]
No problem - it prompted us to update the issue.

**Pull request merged**
