### PR TITLE
Clarify "Verify Disk" desc in Graphical Interface

### PR DESCRIPTION
**Pull request by jaksah**
If using Mac OS X and the "Verify Disk" way of retrieving the BSD name it is not crystal clear that you should leave out the partition part when dd-ing. This change, I think, would clarify to exclude the s2 part of /dev/disk1s2

### CODE REVIEW

**Comment by Ruffio** [comment]
@lurch how is it going with this one? Can it be merged?

**Comment by JamesH65** [comment]
Technically happy for this to be merged, but need to be rebased against the latest documentation. Once that is done I can forward it for copy edit and merging.

**Comment by JamesH65** [comment]
@jaksah Are you able to rebase this over the latest docs?

**Comment by jaksah** [comment]
@JamesH65, done!

**Comment by JamesH65** [comment]
Thanks, have flagged for copy edit review. Can you ensure that other contributors can make changes to the PR (makes it easier for our copy editors to make slight adjustments) - I think this might actually be the github default now.

**Comment by AisforAstronaut** [comment]
I don't have edit access. @jaksah Could you invite me to edit this document? Thank you!

**Comment by jaksah** [comment]
@AisforAstronaut you are now invited

**Comment by AisforAstronaut** [comment]
Thank you!

**Comment by AisforAstronaut** [comment]
File checked. Changes made. Pushing back for technical checking.

**Pull request merged**
