### PR TITLE
clarified where the ssh options were

### PR DESCRIPTION
**Pull request by spencer1573**
i think some times its good to be more clear so that beginners don't get discouraged as easily.

### CODE REVIEW

**Comment by bennuttall** [comment]
Looks fine. I don't know why there's a conflict though...

**Comment by waveform80** [comment]
There's a conflict because a [subsequent commit on master](https://github.com/raspberrypi/documentation/commit/aaeb4074f1f9179df0da0cbe7de5570444dd7acc) hits the same line(s).

**Comment by lurch** [comment]
So I guess the conflict would be resolved if @LornaLynch makes the same "hit" -> "press" edit on this PR too?

So annoying that the GH webinterface can detect, but not display, conflicts :-/

**Comment by waveform80** [comment]
Erm - not sure. If git's merging skills are *that* good, then yes - but I've no idea if they'll handle this situation or not. It might still just be a conflict and this branch might have to be rebased onto the conflicting commit

**Comment by lurch** [comment]
@waveform80 Looks like you were right :-(

@spencer1573 the easiest option for you here is to probably close this PR, and then make the same [changes](https://github.com/raspberrypi/documentation/pull/448/files) on a fresh fork.

**Comment by bennuttall** [comment]
It's ok someone can just do it on the command line when they get chance. I just can't right now as I'm an another machine without ssh keys.

**Comment by lurch** [comment]
> I'm an another machine without ssh keys.

If only somebody could clarify for you where the SSH options are! :laughing:

**Comment by bennuttall** [comment]
Oh the irony!

**Comment by spencer1573** [comment]
thanks for the help guys.

**Comment by LornaLynch** [comment]
I merged the pull request yesterday and then made a correction to the language in line with the style guide. I'm not sure why that would have caused a problem but I can look at it in a moment.

**Comment by waveform80** [comment]
@LornaLynch ah, I'm afraid that while you did make a correction to the language, you didn't merge the PR first. I.e. your correction wound up as [a second commit](https://github.com/raspberrypi/documentation/pull/448/commits/467fee436fea7f3b07918f753f04aa800ef16322) within the PR's branch (GitHub recently added the ability for contributors to add their own commits to others' PRs). You then added [another language correction commit](https://github.com/raspberrypi/documentation/commit/aaeb4074f1f9179df0da0cbe7de5570444dd7acc) but on the master branch. Because this hit the same line as this PR, but occurred *after* this PR on the master branch, it conflicted.

If all this is hard to visualize, have a look at the [network graph](https://github.com/raspberrypi/documentation/network) for the project. You should be able to find Spencer's original commit fairly easily (look along from the spencer1573 line). Then note that your initial correction commit is after his *on the same branch*; that branch wasn't merged to master prior to that commit being made. Then have a look at the next chronological commit on master which is your second correction commit; this is the one that hits the same line as Spencer's initial PR. Because it's on the master branch *after* Spencer's commit, it's a conflict which would require Spencer to rebase his commit on master to fix (or just close this and open a new PR which starts after the conflicting commit, which is what was ultimately done).

Hope that clarifies things!

**Comment by LornaLynch** [comment]
It does, thanks: I was working with a lot of interruptions yesterday, and I suspect one happened when I was doing this.

**Pull request closed without merging**
