### PR TITLE
Update sd-cards.md

### PR DESCRIPTION
**Pull request by semicolo**

### CODE REVIEW

**Comment by JamesH65** [comment]
Good spot, thanks!

**Comment by lurch** [comment]
@JamesH65  I've been wondering for a while whether this section should be reworded, given that none of the Pis currently being sold have TP1 and TP2 test-pads?  (unfortunately I'm too busy right now to PR anything myself, but I can add an issue if you think that'd be helpful?)

**Comment by semicolo** [comment]
What about pins 2(or 4) and 6 of the header to check the voltage?

**Comment by JamesH65** [comment]
Hmm, that is a bit outdated. I'll try and find time to update it, unless someone else volunteers.

**Pull request merged**
