### PR TITLE
Convert absolute link to a relative link

### LINKED ISSUE #669: DPI mode documentation miss linked
Just informing while searching for available config.txt parameter for Raspberry Pi running Android Things to get my 3.5 tft lcd working, under "dpi_group, dpi_mode, dpi_output_format" in config.txt/video is miss linked. [this link](https://www.raspberrypi.org/hardware/raspberrypi/dpi/README.md) should be [this one](https://www.raspberrypi.org/documentation/hardware/raspberrypi/dpi/README.md). Thanks.

### PR DESCRIPTION
**Pull request by lurch**
Fixes #669

### CODE REVIEW

**Comment by JamesH65** [comment]
No need for copy edit on this one.

**Comment by bennuttall** [comment]
Good spot @lurch - one to look out for @JamesH65

**Comment by JamesH65** [comment]
Indeed! Thanks @lurch.

**Comment by lurch** [comment]
And see the issue I created: https://github.com/gjtorikian/html-proofer/issues/436

**Pull request merged**
