### PR TITLE
The wikipedia link to the ZIP64 is broken

### PR DESCRIPTION
**Pull request by SibeeshVenu**
Updated the ZIP64 Wikipedia link

### CODE REVIEW

**Comment by lurch** [comment]
Yup, #1228

**Comment by JamesH65** [comment]
So I think the ( and ) should be converted to %28 and %29 respectively? Are we sure the transfer from github to the website copes with that?

**Comment by lurch** [comment]
I've got no idea, but I guess there's only one way to find out... :confused:

**Comment by JamesH65** [comment]
Currently finding out!

**Comment by JamesH65** [comment]
And it worked. 

So no need for this PR now, but thanks to @SibeeshVenu for pointing out the problem.

**Pull request closed without merging**
