### PR TITLE
Fix missing details with VNC setup

### PR DESCRIPTION
**Pull request by rugk**
* The `/root/.vnc/config.d/vncserver-x11` did not have any `Authentication`entries in my case, so we cannot replace, but append a string
* Add a note on how to restart the vnc server (I hope I am right that I need to restart both `vncserver-virtuald.service` and `vncserver-x11-serviced.service`)
* Add a note on how to open/edit the file.
* Clarify where to find the "VNC Server dialog". 
* Even if you do not connect it to a screen, you can start (and autologin)

### CODE REVIEW

**Comment by rugk** [comment]
Note I did not include the workaround for https://github.com/raspberrypi/noobs/issues/599 in here.

**Comment by andrum99** [comment]
> * Even if you do not connect it to a screen, you can start (and autologin)

Enabling boot to desktop and autologin does **not** force display output. (You've also added this to the virtual desktop section of the VNC instructions, which are for the case where the user has the local display disabled).

**Comment by andrum99** [comment]
> > * Even if you do not connect it to a screen, you can start (and autologin)
> 
> Enabling boot to desktop and autologin does **not** force local display output, nor is it meant to. (You've also added this to the virtual desktop section of the VNC instructions, which is for the case where the user wishes to have the VNC desktop separate from any local display which may or may not be running).

Sorry, I'm talking rubbish. On Pi Zero, 1, 2 and 3 if there is no screen detected on HDMI, the display will come up on composite: on Pi 4 you get no display.

The fact quite a few folk seem to have trouble with VNC means the documentation could probably do with improving.

**Comment by andrum99** [comment]
See #1631

**Comment by rugk** [comment]
> Enabling boot to desktop and autologin does not force local display output, nor is it meant to

Really? In my case it always worked. Do you have a quote/source for this?

**Comment by JamesH65** [comment]
Has this PR been replaced by #1631? @andrum99

**Comment by andrum99** [comment]
> Has this PR been replaced by #1631? @andrum99

That was the intention originally, but I think I need to verify the proposed additions/corrections in this PR as well, since it seems the docs as currently written may not match the current situation.

**Comment by aallan** [comment]
In light of #1911 and the lack of progress in a long while I'm marking this PR as 7 day closure.

**Comment by aallan** [comment]
No one picked this up inside the 7 day closure window. So closing due to #1911.

**Pull request closed without merging**
