### PR TITLE
Update terminal

### PR DESCRIPTION
**Pull request by bennuttall**
Minor changes: updated screenshots and removed legacy references to "LXTerminal".

### CODE REVIEW

**Comment by AisforAstronaut** [comment]
This looks great, Ben. Ready to merge.

**Comment by JamesH65** [comment]
Looks good from a technical POV, merging.

**Comment by bennuttall** [comment]
Just spotted a typo "sofware". Fixing...

**Comment by bennuttall** [comment]
48da7c0af69c2c3841dd8ccc87627852ca138561

**Pull request merged**
