### PR TITLE
Update unix.md : add instruction for X11 installation on OSX.

### PR DESCRIPTION
**Pull request by louity**

### CODE REVIEW

**Comment by JamesH65** [comment]
Happy for this to go forward. Note to copy editor, might want to alter slightly to make it clear that the change is specific to the Mac.

**Comment by bennuttall** [comment]
Is it worth splitting this into two files, linux and mac rather than grouping them in unix?

**Comment by JamesH65** [comment]
I suspect it might be. OK for comms to do that?

**Comment by ghollingworth** [comment]
It's probably better for you to split it

**Comment by AisforAstronaut** [comment]
I don't have access to the branch to make edits to this change. Can you sort this, @JamesH65?

**Comment by JamesH65** [comment]
@louity Can you flag up your patch to allow other collaborators to make edits please.

**Comment by JamesH65** [comment]
Closing as superseded by #582. Done this way as no comment from OP and no ability to edit his PR.

**Pull request closed without merging**
