### PR TITLE
SDXC formatting: Mac Disk Utility no longer allows FAT32

### PR DESCRIPTION
**Pull request by parkr**
Instead, you need to use the diskutil utility:

> $ sudo diskutil eraseDisk FAT32 SDCARD MBRFormat /dev/disk2

### CODE REVIEW

**Comment by andrum99** [comment]
Not sure why the mac instructions are lumped together with Linux. It would make sense to pit mac in a separate section under its own heading

**Comment by andrum99** [comment]
After actually reading the section, it looks like it makes sense to leave Mac and Linux together in the one section.

**Comment by parkr** [comment]
@JamesH65 @andrum99 Anything else you need from me?

**Comment by JamesH65** [comment]
No, its flagged up to our copy editors, so once they have checked it over, it will be merged.

**Comment by parkr** [comment]
@helenlynn What kind of technical check are you looking for?

**Comment by JamesH65** [comment]
That's down to me. Once a CE has been done, I double check that there has been no technical inaccuracies introduced. Hardly ever happens, but just to be on the safe side.

**Pull request merged**
