### PR TITLE
Update led_blink_warnings.md

### PR DESCRIPTION
**Pull request by timg236**
Added I2C error pattern

### CODE REVIEW

**Comment by timg236** [comment]
@JamesH65

**Comment by andrum99** [comment]
Which I2C failures would result in a Pi 4 not being able to boot? Just curious. The other types of failure are fairly obvious.

**Comment by timg236** [comment]
PMIC or GPIO expander

**Comment by aallan** [comment]
I'd encourage you to wrap this PR up in the next week or so as we're in the process of transitioning the documentation from the current Markdown-based source format to Asciidoc. At some point soon — probably around the end of June, beginning of July — we will freeze the current documentation repo. After that time contributions and PRs based on the Markdown source will not be accepted, and any PRs that are still open will be closed.

See #1911 for full details.

**Comment by aallan** [comment]
Any reason **not** to merge? Anyone?

**Pull request merged**
