### PR TITLE
Update camera_auto_detect usage in the camera documentation.

### PR DESCRIPTION
**Pull request by naushir**
To manually override the automatic overlay detection, we must delete the
camera_auto_detect parameter from config.txt.

### CODE REVIEW

**Comment by lurch** [comment]
Oh, does `camera_auto_detect=0` not work as you might expect it to? Is that something that'll be getting "fixed"?

**Comment by lurch** [comment]
(This also appears in the config.txt documentation https://www.raspberrypi.com/documentation/computers/config_txt.html#camera_auto_detect )

**Comment by naushir** [comment]
> Oh, does `camera_auto_detect=0` not work as you might expect it to? Is that something that'll be getting "fixed"?

 `camera_auto_detect=0` disables the boot time detection completely. This would be used specifically for users that want boot times to be as low as possible, and want to avoid any i2c probing.

**Review by lurch — APPROVED** [review]

**Comment by naushir** [comment]
> (This also appears in the config.txt documentation https://www.raspberrypi.com/documentation/computers/config_txt.html#camera_auto_detect )

Yes, I did find that reference in my grep of the tree.  That snippet is still valid and needs no change, but do you think I should explicitly say about removing it if using a manual overlay?

**Comment by lurch** [comment]
I think it should be fine as-is - I guess anybody interested in the nitty-gritty will be reading the camera-specific pages anyway?

**Review by aallan — APPROVED** [review]
LGTM

**Comment by aallan** [comment]
I think its fine as is @naushir. If they want more detail they should go read the camera-specific section.

**Pull request merged**
