### PR TITLE
Glommed ifdown and ifup to a single line

### PR DESCRIPTION
**Pull request by jandahl**

### CODE REVIEW

**Comment by XECDesign** [comment]
What's the reasoning behind this commit? I am not sure that it improves the document.

**Comment by jandahl** [comment]
It shifts the interface down and up in one operation instead of two, saving the user a copy/paste if they’re doing that.

-- 
Jan Gronemann

On 20 Jul 2015 at 18:03:32, XECDesign (notifications@github.com) wrote:

What's the reasoning behind this commit? I am not sure that it improves the document.

**Comment by XECDesign** [comment]
I'm of the opinion that if people are copying and pasting from tutorials, they're doing it wrong. I'm leaning towards not merging this one, but will leave it for a few days if somebody else wants to.

**Comment by jandahl** [comment]
To that, it will be a subtle hint to new users that they can rack up commands like this :-)

No worries either way. 
-- 
Jan Gronemann

On 20 Jul 2015 at 18:14:53, XECDesign (notifications@github.com) wrote:

I'm of the opinion that if people are copying and pasting from tutorials, they're doing it wrong. I'm leaning towards not merging this one, but will leave it for a few days if somebody else wants to.

**Comment by XECDesign** [comment]
Sorry, I'll close this one. There's nothing wrong with it, but at the same time, I don't see it adding anything either.

**Pull request closed without merging**
