### PR TITLE
Toggling scrollbar off for Windows

### PR DESCRIPTION
**Pull request by nelliemckesson**
@lurch can you test this and let me know if it makes any difference?

### CODE REVIEW

**Review by lurch — APPROVED** [review]
LGTM - scrollbar when needed, no scrollbar when not-needed :+1: 
Screenshot from 2021-08-31 10-02-25

(tested on Google Chrome on Ubuntu Linux)

**Comment by aallan** [comment]
Ready to merge at that point @nelliemckesson ?

**Comment by aallan** [comment]
Also, does this also help with #1979?

**Comment by lurch** [comment]
Nope, I think this only addresses #1984 and doesn't touch on #1979

**Comment by nelliemckesson** [comment]
@aallan ready to merge!

**Comment by andrum99** [comment]
Confirmed working as intended on Chrome and Edge (Chrome-based) on Windows 10.

**Pull request merged**
