### PR TITLE
prefix hex number with 0x

### PR DESCRIPTION
**Pull request by dp111**

### CODE REVIEW

**Comment by aallan** [comment]
Hmm. While I agree in theory, I'm not sure we should start unless we intend go through and do this everywhere.

**Comment by dp111** [comment]
Got to start somewhere. Other hex numbers on the page are prefixed. As we
come across them they can be done.

**Comment by aallan** [comment]
> Got to start somewhere. Other hex numbers on the page are prefixed.

Fair enough.

**Comment by aallan** [comment]
@dp111 I merged this, but then noticed you'd based it against the `master` branch. So I've reverted the PR. Please rebase against `develop`. All PRs should be against the `develop` branch. A push to `master` runs the build and pushes live to production.

**Pull request merged**
