### PR TITLE
libcamera: update build instructions and documentation.

### PR DESCRIPTION
**Pull request by naushir**

### CODE REVIEW

**Comment by naushir** [comment]
@davidplowman and @JamesH65

**Comment by davidplowman** [comment]
LGTM. (Though we haven't yet put in Dave's suggestion of "ninja -C build" ahead of "sudo ninja ..." and we should probably do that too. Though I thought we were going to file that as an "Issue"...)

**Comment by davidplowman** [comment]
Actually, the big pdf duplicates that git reference on LinuxTV (section 6.4.3), so we should probably update that too. Arguably, we should perhaps remove the update/build instructions from the pdf and point it to the README.md file instead, to avoid duplication?

**Comment by naushir** [comment]
I will remove the section and point to our readme.  That way we only have one place with the instructions.

**Comment by naushir** [comment]
Done.

**Comment by davidplowman** [comment]
Hmmm, I wonder whether section 6.4.1 shouldn't go too (sorry, I was perhaps not very helpful in referring explicitly to just section 6.4.3, my apologies)....

**Comment by naushir** [comment]
Done :)

**Comment by davidplowman** [comment]
Thank you. Really really LGTM this time!

**Comment by XECDesign** [comment]
Any reason I shouldn't package it up and put it in apt? Or is it too much of a moving target right now?

**Comment by davidplowman** [comment]
Hello XECDesign.... who are you?? BTW, I think I'm more in the "too much of a moving target" camp at the moment.

**Comment by XECDesign** [comment]
Ha, the guy that does the packaging (Serge).

**Comment by davidplowman** [comment]
Ah, hello Serge! Thanks for the question - at some point (hopefully not too long) I guess we'll want to do that, and it's good that we know to give you some warning beforehand, but for now I think we wait...

**Comment by naushir** [comment]
Curious who I should ping to get this merged?

**Comment by JamesH65** [comment]
Me! And done.

**Pull request merged**
