### PR TITLE
CONTRIBUTING.md : add comma on words

### PR DESCRIPTION
**Pull request by RuffaloLavoisier**

### CODE REVIEW

**Review by lurch — APPROVED** [review]
LGTM

**Comment by RuffaloLavoisier** [comment]
@lurch @aallan 
Sorry, It's a non Pull-request question. Is there a community group that you can freely communicate with for Raspberry Pi Official group ? `ex : Discord.. anything !`

If it's a problem, I'll delete it.

**Comment by JamesH65** [comment]
The forums is the public interactive part of Pi. https://forums.raspberrypi.com/

**Comment by RuffaloLavoisier** [comment]
@JamesH65 
Ah...Thanks 😄

**Pull request merged**
