### PR TITLE
clarified the options for the ssh

### PR DESCRIPTION
**Pull request by spencer1573**
I just think its important to make things as clear as possible for the beginners because its really easy to get lost sometimes.

### CODE REVIEW

**Comment by spencer1573** [comment]
does somebody know why i'm failing the html checks?

**Comment by lurch** [comment]
Don't worry, it's nothing that you've done. It's just that HTML-Proofer on TravisCI tends to be a bit unreliable sometimes.

**Comment by spencer1573** [comment]
@lurch thanks! whos in charge of this repository?

**Comment by LornaLynch** [comment]
All done: apologies for the issue last time.

**Comment by spencer1573** [comment]
@LornaLynch I've never dealt with an issue in dev before. weird. haha

**Pull request merged**
