### PR TITLE
Typo?

### PR DESCRIPTION
**Pull request by eugf**
mon --> moy (for "month of year")

### CODE REVIEW

**Comment by JamesH65** [comment]
merged, thanks.

**Comment by bennuttall** [comment]
This is not a typo. That's pasted from crontab. It was correct before.

**Comment by JamesH65** [comment]
It doesn't matter, it's only some text to describe the order isn't it? The typo correct a fairly heinous inconsistency in the docs.

**Comment by JamesH65** [comment]
Ah, actually its the line above that is wrong, it uses "month of year" instead of just month, which is how its described in the crontab. Which is a bit bad but its probably been like that for years. Why use day of week, day of year, then not month of year. Oh well.

**Pull request merged**
