### PR TITLE
update SD card size section in FAQ

### PR DESCRIPTION
**Pull request by JamesH65**

### CODE REVIEW

**Comment by JamesH65** [comment]
Fixes https://github.com/raspberrypi/documentation/issues/1079

**Comment by robthez** [comment]
Not quite what I had in mind - more along the lines of:

"While the recommended minimum of 8GB should be enough for most people, we have tried cards up to 128GB, and most cards seem to work OK. You can also attach a USB stick or USB hard drive to provide extra storage."

Is that OK?

**Comment by JamesH65** [comment]
Updated.

Probably easier in future for you to provide a PR with the change you think is appropriate, saves a bit of back and forth.

**Comment by robthez** [comment]
Sure yeah, sorry. Anyway, great, thanks!

**Comment by JamesH65** [comment]
Think we are running behind on copy edits at the moment, since @JaninaPi moved to Foundation, not sure how long before its merged.

**Pull request merged**
