### PR TITLE
Edit the correct fstab file

### PR DESCRIPTION
**Pull request by peternewman**
Untested, but I think from reading it the current code is targeting the wrong one, or assuming it's run from the Pi that was booted via the network rather than the Pi serving the images over the network.

I may be entirely wrong @chunky but I assume this is what you intended?

### CODE REVIEW

**Comment by JamesH65** [comment]
I have no idea whether this is correct or not. Needs input from the original author.

**Comment by lurch** [comment]
ping @liamfraser

**Comment by JamesH65** [comment]
I'm assuming this is correct. If not i am sure some will will let us know.

**Comment by peternewman** [comment]
I think this also closes #1380 @JamesH65 ?

**Pull request merged**
