### PR TITLE
MP4 output example with raspivid command

### PR DESCRIPTION
**Pull request by dtbaker**
Added an example of wrapping the raw h264 raspivid output in an mp4 container so that raspivid output can be played back easily once recorded.

As per issue #345

### CODE REVIEW

**Comment by Ruffio** [comment]
Can this be merged?

**Comment by JamesH65** [comment]
Happy with the overall idea, but I'd prefer if the instructions did the mp4box command on a separate line to the capture - make it easier for beginners to understand. There's also a couple of typos that need fixing. Please update the PR, and I'll pass it on to comms for final check and merging.

**Comment by JamesH65** [comment]
Thanks! Forwarded to copy edit.

**Comment by AisforAstronaut** [comment]
@dtbaker @JamesH65 Can I have edit access to this branch, please?

**Comment by dtbaker** [comment]
@AisforAstronaut did that go through? https://github.com/dtbaker/documentation/invitations

**Comment by AisforAstronaut** [comment]
@dtbaker It did! Thank you!

**Comment by AisforAstronaut** [comment]
@JamesH65 File checked. Minor changes. Pushed back for technical checking.

**Comment by JamesH65** [comment]
Looks good, merge. Thanks everyone.

**Pull request merged**
