### PR TITLE
Update windows10.md

### PR DESCRIPTION
**Pull request by nikiljos**
About using SSH with WSL

### CODE REVIEW

**Comment by lurch** [comment]
I don't have Windows10 myself, but is this different to #1248 ?

**Comment by nikiljos** [comment]
> I don't have Windows10 myself, but is this different to #1248 ?

In #1248 it is mentioned about windows command line, But my edit can be useful to those who already use ubuntu terminal in Windows 10. They don't have to follow the whole steps.

**Comment by nikiljos** [comment]
Shall I make a commit changing it as @JamesH65 said?

**Comment by ret394** [comment]
What exactly is @JamesH65  suggestion here. Revert or append to file?

Current one is a bit better and less confusing than the file in #1248, someone new or young should look at that.

thanks.

**Comment by andrum99** [comment]
I don't think this is a good addition to the documentation. Is it not obvious that if you are running Linux on Windows using WSL, that you can use the Linux command `ssh` within WSL?

**Pull request closed without merging**
