### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by JamesH65**
Added a bit more information about the BCM2837

### CODE REVIEW

**Comment by JamesH65** [comment]
fixes #325

**Comment by lurch** [comment]
Should this page also mention that the BCM2837 is used in newer versions of the Pi2?
And only a minor tweak, but perhaps `ArmV8` should be changed to `ARMv8` ?

**Comment by JamesH65** [comment]
Hi Andrew, I think that's probably a good idea. Feel free to knock up a PR, we can run paste copy edit.

James

**Comment by lurch** [comment]
See #541

**Comment by ebenupton** [comment]
It's important to emphasise that the BCM2837-based Raspberry Pi 2 v1.2 hasn't superseded the v1.1: the two products continue to run alongside each other.

**Comment by JamesH65** [comment]
@lurch Andrew, could you update as per Eben's comment and throw us another PR please. Ta!

**Pull request merged**
