### PR TITLE
attempted fix for multi-level list bug

### LINKED ISSUE #1251: Multi-level lists in docs subtly broken on raspberrypi.org
(This is one I discovered a while ago but I'm just getting round to adding it as a separate bug).

Documentation pages which contain multi-level lists are currently subtly broken on the official Pi website (raspberrypi.org). The breakage applies only to list items where the indent level is a multiple of 3. In other words indent levels 3, 6, 9 etc are affected. For those indent levels, any list item will be rendered as if it belongs to one below the actual indent level. So level 3 list items are rendered as level 2 list items, level 6 list items as level 5 items, etc.

Compare and contrast the following pages:

https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/host.md
https://github.com/raspberrypi/documentation/blob/master/hardware/raspberrypi/bootmodes/host.md

Rendered on github, the page shows the correct layout of multi-level lists. On raspberrypi.org it is broken as described above.

Interestingly, github.com seems to know about the possible breakage: if you go into edit mode it  renders 3rd, 6th etc level list items in red - see https://github.com/raspberrypi/documentation/edit/master/hardware/raspberrypi/bootmodes/host.md

### PR DESCRIPTION
**Pull request by andrum99**
Attempt to fix #1251 by making all list indents on this page 4 spaces instead of 2.

### CODE REVIEW

**Comment by lurch** [comment]
Pushing this directly to master to see if it fixes #1251 on https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/host.md
If it doesn't fix things I'll revert it.

**Comment by andrum99** [comment]
Nope - still broken in the same way it was before. so it seems https://github.com/Python-Markdown/markdown/issues/3 is not the culprit.

**Comment by lurch** [comment]
AFAIK raspberrypi.org doesn't auto-update, but is done as a scheduled-task or something. I'll check in a few hours...

**Comment by andrum99** [comment]
I've just checked https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/host.md and it is actually now rendering correctly. I jumped the gun slightly there - sorry.

Looking again at this page, it could do with different list indicator character for each indent level - at the moment it is slightly confusing how raspberrypi.org renders it all with red hyphens - the various levels of indent would be much more obvious if each indent level used a different character, ike github.com uses.

**Comment by andrum99** [comment]
See #1254

**Pull request merged**
