### PR TITLE
Remove duplicated words

### PR DESCRIPTION
**Pull request by RuffaloLavoisier**
Is this the right way to fix it? 
# Please let me know if I can improve it more!

### CODE REVIEW

**Comment by lurch** [comment]
I think in this case the original was correct? @aallan ?

**Comment by aallan** [comment]
So"that that" is not great wording, and personally I try and avoid it in written English with judicious rewording, but it is correct.

**Comment by lurch** [comment]
Thanks again for all your other PRs though @RuffaloLavoisier :heart:

**Comment by RuffaloLavoisier** [comment]
@lurch @aallan 
Thank you for checking 😆

**Pull request closed without merging**
