### PR TITLE
Update updating.md

### PR DESCRIPTION
**Pull request by fprades**
apt command lacks clean subcommand. It's apt-get which include clean subcommand.

### CODE REVIEW

**Comment by JamesH65** [comment]
Is there a apt version of clean? That would be a better change, but if there is nothing similar, this PR looks fine.

**Comment by fprades** [comment]
I run into this problem while updating. Jessie to Stretch. At least apt 1.0.9.8.5(jessie) doesn't seem to have it.

**Comment by JamesH65** [comment]
Just tried this on a Pi4 with latest Raspbian, no errors apparent, but no idea if it actually did anything.

**Comment by fprades** [comment]
I suspect `apt clean` was added in later releases of apt. Modified the doc to use apt, or apt-get if former not available

**Comment by JamesH65** [comment]
Thanks!

**Pull request merged**
