### PR TITLE
Update rpicam_apps_packages.adoc - Refer to libcamera-dev

### PR DESCRIPTION
**Pull request by peter-vanpoucke**
Refer to libcamera-dev instead.

### CODE REVIEW

**Comment by peter-vanpoucke** [comment]
`rpicam_apps_building.adoc` does *libcamera-dev* mention in *Building `rpicam-apps` without rebuilding `libcamera`*. But

**Comment by aallan** [comment]
Ping @davidplowman

**Comment by davidplowman** [comment]
@naushir Two commits here.

The first one wants to change the `libcamera-dev` package to `rpicam-dev`. This doesn't feel right to me, it's the "dev" version of the "libcamera" package that we want. Would you agree? Is there even an `rpicam-dev` package?

The second commit wants to add some png related packages. I assume these are ok.

**Comment by naushir** [comment]
> The first one wants to change the `libcamera-dev` package to `rpicam-dev`. This doesn't feel right to me, it's the "dev" version of the "libcamera" package that we want. Would you agree? Is there even an `rpicam-dev` package?

Yes, I agree.  I think `libcamera-dev` is the right term here.

**Comment by aallan** [comment]
Okay to merge then @davidplowman @naushir ?

**Comment by davidplowman** [comment]
I think the 2nd commit with the dng change is OK, but I'm not convinced about the first.

**Comment by peter-vanpoucke** [comment]
fyi libpng is required here: <https://github.com/raspberrypi/rpicam-apps/blob/122b835fb927dffa86f0c3437042d3f0048709bc/image/meson.build#L16>

**Comment by peter-vanpoucke** [comment]
> @naushir Two commits here.
> 
> The first one wants to change the `libcamera-dev` package to `rpicam-dev`. This doesn't feel right to me, it's the "dev" version of the "libcamera" package that we want. Would you agree? Is there even an `rpicam-dev` package?
> 
> The second commit wants to add some png related packages. I assume these are ok.

hi @davidplowman. Just to be sure we're on the same page, I'm trying to change the package to `libcamera-dev`. `rpicam-dev` was originally there.

**Comment by davidplowman** [comment]
> fyi libpng seems to be required [here](https://github.com/raspberrypi/rpicam-apps/blob/122b835fb927dffa86f0c3437042d3f0048709bc/image/meson.build#L16).

Thanks for the clarification, and indeed thanks for posting the documentation correction!

@aallan can we merge the png (I meant "png" earlier where I said "dng") commit and leave the other one? I'd want to double-check on that other commit before deciding on it.

**Comment by davidplowman** [comment]
> > @naushir Two commits here.
> > The first one wants to change the `libcamera-dev` package to `rpicam-dev`. This doesn't feel right to me, it's the "dev" version of the "libcamera" package that we want. Would you agree? Is there even an `rpicam-dev` package?
> > The second commit wants to add some png related packages. I assume these are ok.
> 
> hi @davidplowman. Just to be sure we're on the same page, I'm trying to change the package to `libcamera-dev`. `rpicam-dev` was originally there.

Ah, sorry messages crossed in the post. Indeed, rpicam-dev would be wrong. libcamera-dev would be correct. In which case, yes - we can merge both commits. Sorry for not noticing, haven't really got back in the driving seat after New Year. Thanks everyone!

**Review by aallan — APPROVED** [review]

**Pull request merged**
