### PR TITLE
Update net_tutorial.md

### PR DESCRIPTION
**Pull request by adduty**
Raspbian now supports NFSv4.1, which results in a much faster boot time. TCP is the standard protocol for NFSv4, and UDP is disabled by default for some NFS servers.

### CODE REVIEW

**Comment by andrum99** [comment]
Redhat and Fedora use TCP by default for NFS. Does debian do the same?

**Comment by adduty** [comment]
I am not sure, but it seems that TCP is the preferred protocol for NFSv4. See section 'TCP for Transport' in this doc: https://www.snia.org/sites/default/files/SNIA_An_Overview_of_NFSv4-3_0.pdf.

**Comment by andrum99** [comment]
If TCP is the preferred protocol for NFSv4 then why do you need to specify proto=tcp?

**Comment by andrum99** [comment]
If you can put wireshark on your network to see what is going on traffic-wise without proto=TCP that would be helpful, or find out how this works. I'm inclined to say that the version is unnecessary as well, as we should probably just let Raspbian choose its own preferred version. I suspect it will choose NFSv4.1

**Comment by adduty** [comment]
I have been monitoring the boot sequence from the TFTP/NFS server using tcpdump, and when vers=4.1 is specified without proto=tcp, I see no NFS traffic (sudo tcpdump port nfs or port rpcbind or port rpc or port sunrpc). If I do not specify a vers= or proto= option, the Pi defaults to using NFSv3 over UDP.

**Comment by andrum99** [comment]
NFSv4.1 doesn't use the old NFS port (port 111), it uses port 2049 so you're not going to see any traffic if you're only looking at port 111, rpcbind, rpc and sunrpc. I suspect tcpdump is calling port 111 nfs.

So we definitely need to specify vers=4.1, but the jury is still out on whether proto=TCP is required.

**Comment by adduty** [comment]
Yes, I know, but my tcpdump filter catches all NFSv3 and NFSv4 traffic (2049 will show from 'port nfs'). Using that same filter (sudo tcpdump port nfs or port rpcbind or port rpc or port sunrpc), I see the traffic when the Pi successfully boots using vers=4.1,proto=tcp.

**Comment by andrum99** [comment]
Good stuff. So your original suggestion has been shown to be correct.

**Comment by JamesH65** [comment]
So, we are happy with this change? But it does need to be rebased as their are conflicts. If @adduty can do that i can merge if everyone is happy.

**Comment by adduty** [comment]
I think I have rebased, but I don't actually use git very much, so I'm not sure if I did it correctly.

**Comment by andrum99** [comment]
> I think I have rebased, but I don't actually use git very much, so I'm not sure if I did it correctly.

Github says there are no conflicts, so it seems you did 👍

**Pull request merged**
