### PR TITLE
Update mac.md - dd progress

### PR DESCRIPTION
**Pull request by JamesH65**
Added some information of determining progress during dd.

### CODE REVIEW

**Comment by JamesH65** [comment]
replaces #341

**Comment by LornaLynch** [comment]
Ready for copy edit, @JamesH65?

**Comment by JamesH65** [comment]
Just noticed a typo that I have fixed. Flag up as Requires technical check (a sort of last ditch technical once over) once you are happy, I'll do that and merge.

**Comment by LornaLynch** [comment]
Diff copy checked :)

**Pull request merged**
