### PR TITLE
Include BCM2836 default configuration command.

### PR DESCRIPTION
**Pull request by frasersdev**
Hi,

I noticed the documentation here https://www.raspberrypi.org/documentation/linux/kernel/configuring.md doesn't instruct users how to load the default config for rPi2's so I have updated it.

### CODE REVIEW

**Comment by Ruffio** [comment]
@frasersdev what about RPi3?

**Comment by frasersdev** [comment]
@Ruffio My psychic powers are weak so please excuse my inability to predict future releases.  :)

updated for PI3.

**Comment by lurch** [comment]
Just to be super-picky:
Could you change 'compute module' to be capitalised as 'Compute Module' and change 'PI' to be capitalised as 'Pi'.
And I wonder if it might be worth expanding '(includes compute module)' to '(includes Compute Module and Pi Zero)' ?

**Comment by frasersdev** [comment]
@lurch ok try now.

**Comment by lurch** [comment]
Thanks :)

**Pull request merged**
