### PR TITLE
Corrected spelling mistake in documentation of connecting-a-monitor.adoc

### PR DESCRIPTION
**Pull request by ShivangVora1206**
The file named "connecting-a-monitor.adoc" in documentation\asciidoc\computers\getting-started had a spelling error where "television" was misspelled as "televison" and that spelling has been corrected in this request.

### CODE REVIEW

**Comment by ShivangVora1206** [comment]
I am new to github, since the base branch restricts merging to authorized users and I cannot merge the pull request does that mean the changes can only be made by someone authorized?

**Comment by ShivangVora1206** [comment]
Oh okay, but I followed the same steps you mentioned in this request as well.

**Comment by lurch** [comment]
GitHub sometimes gets a bit "iffy" about our workflow; I don't think it's much to worry about, given that the "Files changed" tab looks correct.

**Comment by aallan** [comment]
> GitHub sometimes gets a bit "iffy" about our workflow; I don't think it's much to worry about, given that the "Files changed" tab looks correct.

Yeah, they look like merges brought in from `master` perhaps? I'm not even sure it's Git as such, I think it's the same Github problem that gives the master branch look a bit odd in the Github UI. 🤷

**Comment by RuffaloLavoisier** [comment]
> in from `master` perhaps?

At least that's what I think. :smile:

**Pull request merged**
