### PR TITLE
Added documentation for --annotate, --annotateex

### PR DESCRIPTION
**Pull request by fullergalway**
Adds documentation for --annotate and --annotateex. This commit complements userland pull request  264 https://github.com/raspberrypi/userland/pull/264

### CODE REVIEW

**Comment by fullergalway** [comment]
Fixed unrelated broken link breaking travis build.

**Comment by fullergalway** [comment]
Updated to correspond with userland pull request https://github.com/raspberrypi/userland/pull/264

**Comment by lurch** [comment]
Could the `wireless-cli.md` link fix be moved into a separate PR?

**Comment by fullergalway** [comment]
Moved wireless-cli.md to a separate PR, and squashed two commits to one. Please wait on userland PR https://github.com/raspberrypi/userland/pull/264 before pulling this doco change. Thanks.

**Comment by lurch** [comment]
Merged now that the corresponding userland PR has been merged.

**Pull request merged**
