### PR TITLE
Jsavage patch 2

### PR DESCRIPTION
**Pull request by jsavage**
Re issue #285

### CODE REVIEW

**Comment by lurch** [comment]
Could you please separate out the Cron part of this patch into a separate PR, and then update this PR so it's only dealing with the SSH stuff?

**Comment by JamesH65** [comment]
@jsavage I have no objections to this set of patches, but it be much better to split as suggested by @Lurch above. once that's done I'll push to comms for checking and merging.

**Comment by JamesH65** [comment]
I've changed my mind on whether to merge this. I think it needs to be completely rebased against the current documentation as I suspect things have moved around and some of the issues may already be covered. 

So I'm going to close this PR unmerged in about a week unless there is a compelling argument why not (or a new PR!)

**Comment by JamesH65** [comment]
Closing - no response from originator.

**Pull request closed without merging**
